// packages/ui-react/src/mirror-text/mirror-text.tsx
import { createElement, type ElementType, Fragment } from "react";
import { cn } from "../lib/cn";
import { type MirrorTextDirection, mirrorText } from "./variants";

export type { MirrorTextDirection };

export interface MirrorTextProps {
	/** Shown as four stacked, clipped copies that stagger apart on hover. */
	text: string;
	as?: ElementType;
	direction?: MirrorTextDirection;
	/** How long each layer's slide takes, in ms. */
	durationMs?: number;
	/** Delay step between the four stacked layers, in ms. */
	staggerMs?: number;
	className?: string;
}

const LAYER_COUNT = 4;

export function MirrorText({
	text,
	as = "span",
	direction = "up",
	durationMs = 500,
	staggerMs = 67,
	className,
}: MirrorTextProps) {
	const { root, layer } = mirrorText({ direction });
	return createElement(
		as,
		{ "data-slot": "mirror-text", className: cn(root(), className) },
		<Fragment>
			<span className="sr-only">{text}</span>
			{Array.from({ length: LAYER_COUNT }, (_, index) => (
				<div
					key={index}
					aria-hidden
					className={cn("h-[0.6em] overflow-hidden", layer())}
					style={{
						transitionDuration: `${durationMs}ms`,
						transitionDelay: `${(LAYER_COUNT - 1 - index) * staggerMs}ms`,
					}}
				>
					<div className="inline-block leading-none">{text}</div>
				</div>
			))}
		</Fragment>,
	);
}

// packages/ui-svelte/src/lib/mirror-text/mirror-text.svelte
<script lang="ts">
import { cn } from "../lib/cn";
import { type MirrorTextDirection, mirrorText } from "./variants";

let {
	text,
	as = "span",
	direction = "up",
	durationMs = 500,
	staggerMs = 67,
	class: classProp,
}: {
	text: string;
	as?: string;
	direction?: MirrorTextDirection;
	/** How long each layer's slide takes, in ms. */
	durationMs?: number;
	/** Delay step between the four stacked layers, in ms. */
	staggerMs?: number;
	class?: string;
} = $props();

const classes = $derived(mirrorText({ direction }));
const LAYER_COUNT = 4;
const layers = Array.from({ length: LAYER_COUNT }, (_, index) => index);
</script>

<svelte:element this={as} data-slot="mirror-text" class={cn(classes.root(), classProp)}>
	<span class="sr-only">{text}</span>
	{#each layers as index (index)}
		<div
			aria-hidden="true"
			class={cn("h-[0.6em] overflow-hidden", classes.layer())}
			style="transition-duration: {durationMs}ms; transition-delay: {(LAYER_COUNT - 1 - index) * staggerMs}ms;"
		>
			<div class="inline-block leading-none">{text}</div>
		</div>
	{/each}
</svelte:element>
