// packages/demos/src/usage/svelte/command.svelte
<script lang="ts">
import {
	Command,
	CommandDialog,
	CommandEmpty,
	CommandGroup,
	CommandHeader,
	CommandInput,
	CommandItem,
	CommandList,
	CommandShortcut,
} from "@baby-ui/svelte";

let open = $state(false);
</script>

<button type="button" onclick={() => (open = true)}>Open palette</button>

<CommandDialog bind:open>
	<Command>
		<CommandHeader>Command</CommandHeader>
		<CommandInput />
		<CommandList>
			<CommandEmpty>Nothing matches that.</CommandEmpty>
			<CommandGroup heading="Actions">
				<CommandItem value="New project">
					New project
					<CommandShortcut>N</CommandShortcut>
				</CommandItem>
				<CommandItem value="Deploy" keywords="ship release">Deploy</CommandItem>
			</CommandGroup>
		</CommandList>
	</Command>
</CommandDialog>

// packages/demos/src/usage/react/command.tsx
"use client";

import {
	Command,
	CommandDialog,
	CommandEmpty,
	CommandGroup,
	CommandHeader,
	CommandInput,
	CommandItem,
	CommandList,
	CommandShortcut,
} from "@baby-ui/react";
import { useState } from "react";

export function Example() {
	const [open, setOpen] = useState(false);

	return (
		<>
			<button type="button" onClick={() => setOpen(true)}>
				Open palette
			</button>
			<CommandDialog open={open} onOpenChange={setOpen}>
				<Command>
					<CommandHeader>Command</CommandHeader>
					<CommandInput />
					<CommandList>
						<CommandEmpty>Nothing matches that.</CommandEmpty>
						<CommandGroup heading="Actions">
							<CommandItem value="New project">
								New project
								<CommandShortcut>N</CommandShortcut>
							</CommandItem>
							<CommandItem value="Deploy" keywords="ship release">
								Deploy
							</CommandItem>
						</CommandGroup>
					</CommandList>
				</Command>
			</CommandDialog>
		</>
	);
}
