// packages/demos/src/usage/svelte/tabs.svelte
<script lang="ts">
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@baby-ui/svelte";

let value = $state("overview");
</script>

<Tabs bind:value variant="underline">
	<TabsList>
		<TabsTrigger value="overview">Overview</TabsTrigger>
		<TabsTrigger value="activity">Activity</TabsTrigger>
	</TabsList>
	<TabsContent value="overview">Deployment health and traffic.</TabsContent>
	<TabsContent value="activity">Every deploy and who triggered it.</TabsContent>
</Tabs>

// packages/demos/src/usage/react/tabs.tsx
"use client";

import { Tabs, TabsContent, TabsList, TabsTrigger } from "@baby-ui/react";
import { useState } from "react";

export function Example() {
	const [value, setValue] = useState("overview");

	return (
		<Tabs value={value} onValueChange={setValue} variant="underline">
			<TabsList>
				<TabsTrigger value="overview">Overview</TabsTrigger>
				<TabsTrigger value="activity">Activity</TabsTrigger>
			</TabsList>
			<TabsContent value="overview">Deployment health and traffic.</TabsContent>
			<TabsContent value="activity">Every deploy and who triggered it.</TabsContent>
		</Tabs>
	);
}
