// packages/ui-react/src/pixel-image-trail/pixel-image-trail.tsx
"use client";

import { type ReactNode, useEffect, useRef } from "react";
import { cn } from "../lib/cn";
import {
	mountPixelTrail,
	type PixelImageTrailSize,
	type PixelImageTrailVariant,
	type PixelTrailOptions,
	pixelImageTrail,
} from "./pixel-trail";

export type { PixelImageTrailSize, PixelImageTrailVariant };

export interface PixelImageTrailProps {
	/** Image revealed square by square under the pointer. */
	src: string;
	/** Accessible description of the image. */
	alt: string;
	/** Edge of one square, in px (at least 12). */
	pixelSize?: number;
	/** Farthest distance, in px, for an occasional satellite square. */
	radius?: number;
	/** Time in ms before a trail square has fully faded. */
	fadeDuration?: number;
	/** Most trail squares kept at once; the oldest drop first. */
	maxPixels?: number;
	/** Dimmed fragments shown before any interaction. */
	initialPixels?: number;
	variant?: PixelImageTrailVariant;
	size?: PixelImageTrailSize;
	className?: string;
	children?: ReactNode;
}

/** A hidden image revealed in square fragments that trail the pointer and fade away. */
export function PixelImageTrail({
	src,
	alt,
	pixelSize = 36,
	radius = 58,
	fadeDuration = 900,
	maxPixels = 84,
	initialPixels = 24,
	variant = "fade",
	size,
	className,
	children,
}: PixelImageTrailProps) {
	const root = useRef<HTMLDivElement>(null);
	const canvas = useRef<HTMLCanvasElement>(null);
	const image = useRef<HTMLImageElement>(null);
	const trail = useRef<ReturnType<typeof mountPixelTrail>>(null);
	const s = pixelImageTrail({ variant, size });
	const options: PixelTrailOptions = {
		pixelSize,
		radius,
		fadeDuration,
		maxPixels,
		initialPixels,
		variant,
	};
	const latest = useRef(options);
	latest.current = options;

	useEffect(() => {
		if (!root.current || !canvas.current || !image.current) return;
		trail.current = mountPixelTrail(
			root.current,
			canvas.current,
			image.current,
			latest.current,
		);
		return () => trail.current?.destroy();
	}, []);

	useEffect(() => {
		trail.current?.update(latest.current);
	}, [pixelSize, radius, fadeDuration, maxPixels, initialPixels, variant]);

	return (
		<div ref={root} data-slot="pixel-image-trail" className={cn(s.root(), className)}>
			<img ref={image} src={src} alt={alt} draggable={false} className={s.image()} />
			<canvas ref={canvas} aria-hidden className={s.canvas()} />
			{children ? <div className={s.content()}>{children}</div> : null}
		</div>
	);
}

// packages/ui-svelte/src/lib/pixel-image-trail/pixel-image-trail.svelte
<script lang="ts">
import type { Snippet } from "svelte";
import { untrack } from "svelte";
import { cn } from "../lib/cn";
import {
	mountPixelTrail,
	type PixelImageTrailSize,
	type PixelImageTrailVariant,
	type PixelTrailOptions,
	pixelImageTrail,
} from "./pixel-trail";

let {
	src,
	alt,
	pixelSize = 36,
	radius = 58,
	fadeDuration = 900,
	maxPixels = 84,
	initialPixels = 24,
	variant = "fade",
	size,
	class: className,
	children,
}: {
	/** Image revealed square by square under the pointer. */
	src: string;
	/** Accessible description of the image. */
	alt: string;
	/** Edge of one square, in px (at least 12). */
	pixelSize?: number;
	/** Farthest distance, in px, for an occasional satellite square. */
	radius?: number;
	/** Time in ms before a trail square has fully faded. */
	fadeDuration?: number;
	/** Most trail squares kept at once; the oldest drop first. */
	maxPixels?: number;
	/** Dimmed fragments shown before any interaction. */
	initialPixels?: number;
	variant?: PixelImageTrailVariant;
	size?: PixelImageTrailSize;
	class?: string;
	children?: Snippet;
} = $props();

const s = $derived(pixelImageTrail({ variant, size }));
const options: PixelTrailOptions = $derived({
	pixelSize,
	radius,
	fadeDuration,
	maxPixels,
	initialPixels,
	variant,
});

let root = $state<HTMLDivElement>();
let canvas = $state<HTMLCanvasElement>();
let image = $state<HTMLImageElement>();
let trail: ReturnType<typeof mountPixelTrail> | undefined;

$effect(() => {
	if (!root || !canvas || !image) return;
	trail = mountPixelTrail(
		root,
		canvas,
		image,
		untrack(() => $state.snapshot(options)),
	);
	return () => trail?.destroy();
});

$effect(() => {
	const next = $state.snapshot(options);
	trail?.update(next);
});
</script>

<div bind:this={root} data-slot="pixel-image-trail" class={cn(s.root(), className)}>
	<img bind:this={image} {src} {alt} draggable="false" class={s.image()} />
	<canvas bind:this={canvas} aria-hidden="true" class={s.canvas()}></canvas>
	{#if children}
		<div class={s.content()}>{@render children()}</div>
	{/if}
</div>
