// packages/ui-svelte/src/lib/skeleton/skeleton.svelte
<script lang="ts">
import { cn } from "../lib/cn.js";

let {
	width = "100%",
	height = "1rem",
	shape = "line",
	class: classProp,
}: {
	width?: string;
	height?: string;
	shape?: "line" | "circle" | "block";
	class?: string;
} = $props();

const SHAPE = { line: "rounded-md", circle: "rounded-full", block: "rounded-xl" };
</script>

<div
	aria-hidden="true"
	style:width
	style:height
	class={cn("skeleton-shimmer bg-card", SHAPE[shape], classProp)}
></div>

// packages/ui-react/src/skeleton/skeleton.tsx
import { cn } from "../lib/cn";

const SHAPE = { line: "rounded-md", circle: "rounded-full", block: "rounded-xl" };

export interface SkeletonProps {
	width?: string;
	height?: string;
	shape?: "line" | "circle" | "block";
	className?: string;
}

export function Skeleton({
	width = "100%",
	height = "1rem",
	shape = "line",
	className,
}: SkeletonProps) {
	return (
		<div
			aria-hidden
			style={{ width, height }}
			className={cn("skeleton-shimmer bg-card", SHAPE[shape], className)}
		/>
	);
}
