// packages/demos/src/usage/react/skeleton.tsx
import { Skeleton } from "@baby-ui/react";

export function Example() {
	return (
		<div className="flex items-center gap-3">
			<Skeleton shape="circle" width="2.5rem" height="2.5rem" />
			<div className="flex flex-1 flex-col gap-2">
				<Skeleton width="60%" />
				<Skeleton width="40%" />
			</div>
		</div>
	);
}

// packages/ui-svelte/src/lib/skeleton/skeleton.svelte
<script lang="ts">
import { cn } from "../lib/cn.js";

let {
	width = "100%",
	height = "1rem",
	shape = "line",
	class: classProp,
}: {
	width?: string;
	height?: string;
	shape?: "line" | "circle" | "block";
	class?: string;
} = $props();

const SHAPE = { line: "rounded-md", circle: "rounded-full", block: "rounded-xl" };
</script>

<div
	aria-hidden="true"
	style:width
	style:height
	class={cn("skeleton-shimmer bg-card", SHAPE[shape], classProp)}
></div>
