// packages/ui-svelte/src/lib/wave-reveal/wave-reveal.svelte
<script lang="ts">
import { cn } from "../lib/cn";
import {
	type WaveRevealDirection,
	type WaveRevealMode,
	waveAnimationClass,
	waveReveal,
} from "./variants";

let {
	text,
	direction = "down",
	mode = "letter",
	blur = true,
	staggerMs = 50,
	class: classProp,
}: {
	text: string;
	direction?: WaveRevealDirection;
	mode?: WaveRevealMode;
	blur?: boolean;
	staggerMs?: number;
	class?: string;
} = $props();

const classes = $derived(waveReveal({ direction }));
const words = $derived(text.trim().split(/\s+/));
const animClass = $derived(waveAnimationClass(direction, blur));

function delayFor(index: number) {
	return `${index * staggerMs}ms`;
}
</script>

<div data-slot="wave-reveal" class={cn(classes.root(), classProp)}>
	<span class="sr-only">{text}</span>
	<span aria-hidden="true" class="contents">
		{#each words as word, wordIndex (`${wordIndex}-${word}`)}
			{@const baseIndex = words.slice(0, wordIndex).reduce((n, w) => n + (mode === "word" ? 1 : w.length), 0)}
			<span class="contents">
				{#if mode === "word"}
					<span class={cn(classes.unit(), animClass)} style="animation-delay: {delayFor(baseIndex)}">
						{word}
					</span>
				{:else}
					{#each word.split("") as letter, letterIndex (letterIndex)}
						<span
							class={cn(classes.unit(), animClass)}
							style="animation-delay: {delayFor(baseIndex + letterIndex)}"
						>
							{letter === " " ? " " : letter}
						</span>
					{/each}
				{/if}
				{#if wordIndex < words.length - 1}{" "}{/if}
			</span>
		{/each}
	</span>
</div>

// packages/ui-react/src/wave-reveal/wave-reveal.tsx
import { cn } from "../lib/cn";
import {
	type WaveRevealDirection,
	type WaveRevealMode,
	waveAnimationClass,
	waveReveal,
} from "./variants";

export type { WaveRevealDirection, WaveRevealMode };

export interface WaveRevealProps {
	text: string;
	direction?: WaveRevealDirection;
	/** Stagger per letter, or per whole word. */
	mode?: WaveRevealMode;
	/** Adds a blur-to-sharp resolve alongside the fade/drift. */
	blur?: boolean;
	/** Delay step between units, in ms. */
	staggerMs?: number;
	className?: string;
}

export function WaveReveal({
	text,
	direction = "down",
	mode = "letter",
	blur = true,
	staggerMs = 50,
	className,
}: WaveRevealProps) {
	const { root, unit } = waveReveal({ direction });
	const words = text.trim().split(/\s+/);
	const animClass = waveAnimationClass(direction, blur);
	let unitIndex = 0;

	return (
		<div data-slot="wave-reveal" className={cn(root(), className)}>
			<span className="sr-only">{text}</span>
			<span aria-hidden className="contents">
				{words.map((word, wordIndex) => (
					<span key={`${wordIndex}-${word}`} className="contents">
						{mode === "word" ? (
							<span
								className={cn(unit(), animClass)}
								style={{ animationDelay: `${unitIndex++ * staggerMs}ms` }}
							>
								{word}
							</span>
						) : (
							word.split("").map((letter, letterIndex) => (
								<span
									key={`${wordIndex}-${letterIndex}`}
									className={cn(unit(), animClass)}
									style={{ animationDelay: `${unitIndex++ * staggerMs}ms` }}
								>
									{letter === " " ? " " : letter}
								</span>
							))
						)}
						{wordIndex < words.length - 1 ? " " : null}
					</span>
				))}
			</span>
		</div>
	);
}
