// packages/ui-react/src/mask-text/mask-text.tsx
"use client";

import {
	type CSSProperties,
	type PointerEvent as ReactPointerEvent,
	useState,
} from "react";
import { cn } from "../lib/cn";
import { type MaskTextSize, maskText } from "./variants";

export type { MaskTextSize };

export interface MaskTextProps {
	/** Shown through the cursor-following mask. */
	revealText: string;
	/** Shown underneath, everywhere the mask isn't. */
	baseText: string;
	/** Mask diameter on hover, in pixels. */
	revealSize?: number;
	/** How long the mask grows/shrinks on hover, in ms. */
	durationMs?: number;
	size?: MaskTextSize;
	className?: string;
}

export function MaskText({
	revealText,
	baseText,
	revealSize = 240,
	durationMs = 500,
	size = "md",
	className,
}: MaskTextProps) {
	const { root, base, reveal } = maskText({ size });
	const [pos, setPos] = useState({ x: "50%", y: "50%" });
	const [hovered, setHovered] = useState(false);

	function onMove(event: ReactPointerEvent<HTMLDivElement>) {
		const rect = event.currentTarget.getBoundingClientRect();
		setPos({ x: `${event.clientX - rect.left}px`, y: `${event.clientY - rect.top}px` });
	}

	return (
		<div
			data-slot="mask-text"
			className={cn(root(), className)}
			onPointerMove={onMove}
			onPointerEnter={() => setHovered(true)}
			onPointerLeave={() => setHovered(false)}
		>
			<span className={base()}>{baseText}</span>
			<span
				aria-hidden
				className={reveal()}
				style={
					{
						"--mt-x": pos.x,
						"--mt-y": pos.y,
						"--mt-size": hovered ? `${revealSize}px ${revealSize}px` : "0px 0px",
						"--mt-duration": `${durationMs}ms`,
					} as CSSProperties
				}
			>
				{revealText}
			</span>
		</div>
	);
}

// packages/ui-svelte/src/lib/mask-text/mask-text.svelte
<script lang="ts">
import { cn } from "../lib/cn";
import { type MaskTextSize, maskText } from "./variants";

let {
	revealText,
	baseText,
	revealSize = 240,
	durationMs = 500,
	size = "md",
	class: classProp,
}: {
	revealText: string;
	baseText: string;
	revealSize?: number;
	/** How long the mask grows/shrinks on hover, in ms. */
	durationMs?: number;
	size?: MaskTextSize;
	class?: string;
} = $props();

const classes = $derived(maskText({ size }));
let x = $state("50%");
let y = $state("50%");
let hovered = $state(false);

function onMove(event: PointerEvent & { currentTarget: HTMLDivElement }) {
	const rect = event.currentTarget.getBoundingClientRect();
	x = `${event.clientX - rect.left}px`;
	y = `${event.clientY - rect.top}px`;
}
</script>

<!-- svelte-ignore a11y_no_static_element_interactions -- decorative pointer-follow mask, no click/keyboard semantics -->
<div
	data-slot="mask-text"
	class={cn(classes.root(), classProp)}
	onpointermove={onMove}
	onpointerenter={() => {
		hovered = true;
	}}
	onpointerleave={() => {
		hovered = false;
	}}
>
	<span class={classes.base()}>{baseText}</span>
	<span
		aria-hidden="true"
		class={classes.reveal()}
		style="--mt-x: {x}; --mt-y: {y}; --mt-size: {hovered
			? `${revealSize}px ${revealSize}px`
			: '0px 0px'}; --mt-duration: {durationMs}ms;"
	>
		{revealText}
	</span>
</div>
