// packages/ui-react/src/draggable-marquee/draggable-marquee.tsx
"use client";

import { type ReactNode, useEffect, useRef, useState } from "react";
import { cn } from "../lib/cn";
import { createMarquee } from "./marquee";
import {
	type DraggableMarqueeDirection,
	type DraggableMarqueeGap,
	draggableMarquee,
} from "./variants";

export type { DraggableMarqueeDirection, DraggableMarqueeGap };

export interface DraggableMarqueeProps {
	/** One set of items; it repeats as often as the width needs. */
	children: ReactNode;
	/** Drift in px per frame; 0 holds still until dragged. */
	speed?: number;
	direction?: DraggableMarqueeDirection;
	gap?: DraggableMarqueeGap;
	pauseOnHover?: boolean;
	/** Share of a throw's velocity kept each frame, 0 to 1. */
	friction?: number;
	/** Accessible name of the region. */
	label?: string;
	className?: string;
}

export function DraggableMarquee({
	children,
	speed = 1,
	direction = "left",
	gap = "md",
	pauseOnHover = false,
	friction = 0.975,
	label = "Scrolling gallery. Drag, or use the left and right arrow keys.",
	className,
}: DraggableMarqueeProps) {
	const rootRef = useRef<HTMLDivElement>(null);
	const trackRef = useRef<HTMLDivElement>(null);
	const marqueeRef = useRef<ReturnType<typeof createMarquee>>(null);
	const [copies, setCopies] = useState(2);
	const s = draggableMarquee({ gap, direction });
	const options = { speed, direction, pauseOnHover, friction, onCopies: setCopies };

	useEffect(() => {
		if (!rootRef.current || !trackRef.current) return;
		const marquee = createMarquee(rootRef.current, trackRef.current, options);
		marqueeRef.current = marquee;
		return () => marquee.destroy();
		// Options flow through update(); recreating would reset the track's position.
	}, []);

	useEffect(() => {
		marqueeRef.current?.update(options);
	});

	return (
		<section
			ref={rootRef}
			data-slot="draggable-marquee"
			aria-label={label}
			aria-roledescription="marquee"
			// biome-ignore lint/a11y/noNoninteractiveTabindex: focus is how arrow keys reach the track
			tabIndex={0}
			className={cn(s.root(), className)}
		>
			<div ref={trackRef} className={s.track()}>
				{Array.from({ length: copies }, (_, copy) => (
					<div
						key={copy}
						aria-hidden={copy > 0 || undefined}
						inert={copy > 0}
						className={s.copy()}
					>
						{children}
					</div>
				))}
			</div>
		</section>
	);
}

// packages/ui-svelte/src/lib/draggable-marquee/draggable-marquee.svelte
<script lang="ts">
import type { Snippet } from "svelte";
import { untrack } from "svelte";
import { cn } from "../lib/cn";
import { createMarquee } from "./marquee";
import {
	type DraggableMarqueeDirection,
	type DraggableMarqueeGap,
	draggableMarquee,
} from "./variants";

let {
	children,
	speed = 1,
	direction = "left",
	gap = "md",
	pauseOnHover = false,
	friction = 0.975,
	label = "Scrolling gallery. Drag, or use the left and right arrow keys.",
	class: classProp,
}: {
	/** One set of items; it repeats as often as the width needs. */
	children: Snippet;
	/** Drift in px per frame; 0 holds still until dragged. */
	speed?: number;
	direction?: DraggableMarqueeDirection;
	gap?: DraggableMarqueeGap;
	pauseOnHover?: boolean;
	/** Share of a throw's velocity kept each frame, 0 to 1. */
	friction?: number;
	/** Accessible name of the region. */
	label?: string;
	class?: string;
} = $props();

let root: HTMLElement | undefined = $state();
let track: HTMLDivElement | undefined = $state();
let copies = $state(2);
let marquee: ReturnType<typeof createMarquee> | undefined;
const s = $derived(draggableMarquee({ gap, direction }));
const onCopies = (count: number) => (copies = count);
const options = $derived({ speed, direction, pauseOnHover, friction, onCopies });

$effect(() => {
	const el = root;
	const row = track;
	if (!el || !row) return;
	// Options flow through update(); recreating would reset the track's position.
	marquee = untrack(() => createMarquee(el, row, options));
	return () => marquee?.destroy();
});

$effect(() => {
	marquee?.update(options);
});
</script>

<!-- svelte-ignore a11y_no_noninteractive_tabindex -- focus is how arrow keys reach the track -->
<section
	bind:this={root}
	data-slot="draggable-marquee"
	aria-label={label}
	aria-roledescription="marquee"
	tabindex="0"
	class={cn(s.root(), classProp)}
>
	<div bind:this={track} class={s.track()}>
		{#each { length: copies } as _, copy (copy)}
			<div aria-hidden={copy > 0 || undefined} inert={copy > 0} class={s.copy()}>
				{@render children()}
			</div>
		{/each}
	</div>
</section>
