// packages/ui-react/src/scroll-reveal/scroll-reveal.tsx
"use client";

import { type CSSProperties, useEffect, useRef } from "react";
import { cn } from "../lib/cn";
import { type ScrollRevealSize, scrollReveal } from "./variants";

export type { ScrollRevealSize };

export interface ScrollRevealProps {
	/** The text to reveal word by word as the container scrolls. */
	text: string;
	/** Opacity of words not yet reached by the scroll position. */
	minOpacity?: number;
	/** Also blurs unreached words, sharpening as they're reached. */
	blur?: boolean;
	size?: ScrollRevealSize;
	className?: string;
}

export function ScrollReveal({
	text,
	minOpacity = 0.5,
	blur = true,
	size = "md",
	className,
}: ScrollRevealProps) {
	const words = text.trim().split(/\s+/);
	const containerRef = useRef<HTMLDivElement>(null);

	useEffect(() => {
		const el = containerRef.current;
		if (!el) return;
		let raf = 0;
		function onScroll() {
			cancelAnimationFrame(raf);
			raf = requestAnimationFrame(() => {
				if (!el) return;
				const maxScroll = el.scrollHeight - el.clientHeight;
				const progress = maxScroll > 0 ? el.scrollTop / maxScroll : 0;
				el.style.setProperty("--sr-progress", String(progress));
			});
		}
		el.addEventListener("scroll", onScroll, { passive: true });
		return () => {
			el.removeEventListener("scroll", onScroll);
			cancelAnimationFrame(raf);
		};
	}, []);

	return (
		<div
			ref={containerRef}
			data-slot="scroll-reveal"
			className={cn(scrollReveal({ size }), className)}
			style={{ "--sr-min": minOpacity } as CSSProperties}
		>
			<div className="sticky top-0 flex h-full w-full items-center justify-center">
				<div className="flex h-fit w-full flex-wrap justify-center gap-x-[0.35em] p-8">
					{words.map((word, index) => (
						<span
							key={`${index}-${word}`}
							data-blur={blur}
							className="scroll-reveal-word"
							style={
								{
									"--sr-t": `clamp(0, calc((var(--sr-progress, 0) - ${index / words.length}) * ${words.length}), 1)`,
								} as CSSProperties
							}
						>
							{word}
						</span>
					))}
				</div>
			</div>
			{words.map((_, index) => (
				<div key={index} className="h-32" aria-hidden />
			))}
		</div>
	);
}

// packages/ui-svelte/src/lib/scroll-reveal/scroll-reveal.svelte
<script lang="ts">
import { cn } from "../lib/cn";
import { type ScrollRevealSize, scrollReveal } from "./variants";

let {
	text,
	minOpacity = 0.5,
	blur = true,
	size = "md",
	class: classProp,
}: {
	/** The text to reveal word by word as the container scrolls. */
	text: string;
	/** Opacity of words not yet reached by the scroll position. */
	minOpacity?: number;
	/** Also blurs unreached words, sharpening as they're reached. */
	blur?: boolean;
	size?: ScrollRevealSize;
	class?: string;
} = $props();

const words = $derived(text.trim().split(/\s+/));
let el = $state<HTMLDivElement>();

$effect(() => {
	const node = el;
	if (!node) return;
	let raf = 0;
	function onScroll() {
		cancelAnimationFrame(raf);
		raf = requestAnimationFrame(() => {
			if (!node) return;
			const maxScroll = node.scrollHeight - node.clientHeight;
			const progress = maxScroll > 0 ? node.scrollTop / maxScroll : 0;
			node.style.setProperty("--sr-progress", String(progress));
		});
	}
	node.addEventListener("scroll", onScroll, { passive: true });
	return () => {
		node.removeEventListener("scroll", onScroll);
		cancelAnimationFrame(raf);
	};
});
</script>

<div
	bind:this={el}
	data-slot="scroll-reveal"
	class={cn(scrollReveal({ size }), classProp)}
	style="--sr-min: {minOpacity};"
>
	<div class="sticky top-0 flex h-full w-full items-center justify-center">
		<div class="flex h-fit w-full flex-wrap justify-center gap-x-[0.35em] p-8">
			{#each words as word, index (index + word)}
				<span
					data-blur={blur}
					class="scroll-reveal-word"
					style="--sr-t: clamp(0, calc((var(--sr-progress, 0) - {index / words.length}) * {words.length}), 1);"
				>
					{word}
				</span>
			{/each}
		</div>
	</div>
	{#each words as _, index (index)}
		<div class="h-32" aria-hidden="true"></div>
	{/each}
</div>
