// packages/ui-react/src/og-changelog/og-changelog.tsx
import { cn } from "../lib/cn";
import {
	OG_CHANGELOG_ICONS,
	type OgChangelogKind,
	type OgChangelogMode,
	type OgChangelogTone,
	ogChangelog,
	ogChangelogMarker,
} from "./variants";

export type { OgChangelogKind, OgChangelogMode, OgChangelogTone };

export interface OgChangelogHighlight {
	kind: OgChangelogKind;
	text: string;
	/** Marker text; defaults to the capitalised kind. */
	label?: string;
}

export interface OgChangelogProps {
	/** Release version, e.g. "v2.4.0"; also drawn as the background numeral. */
	version: string;
	headline: string;
	/** Product name shown top left. */
	site: string;
	logo?: string;
	/** Pre-formatted release date. */
	date?: string;
	/** Up to three entries; extra entries are dropped. */
	highlights?: OgChangelogHighlight[];
	mode?: OgChangelogMode;
	tone?: OgChangelogTone;
	className?: string;
}

/** A 1200x630 release card. Render it to PNG with takumi-js (see the docs recipe). */
export function OgChangelog({
	version,
	headline,
	site,
	logo,
	date,
	highlights,
	mode = "light",
	tone = "neutral",
	className,
}: OgChangelogProps) {
	const s = ogChangelog({ mode, tone });
	const items = highlights?.slice(0, 3) ?? [];
	return (
		<div data-slot="og-changelog" className={cn(s.root(), className)}>
			<div className={s.ghost()}>{version}</div>
			<div className={s.stub()}>
				<div className={s.brand()}>
					{logo ? <img src={logo} alt="" className={s.logo()} /> : null}
					<span className={s.site()}>{site}</span>
				</div>
				<div className={s.pill()}>
					<span className={s.pillText()}>{version}</span>
				</div>
				{date ? <div className={s.date()}>{date}</div> : null}
				<div className={s.rail()}>
					<span className={s.railHead()} />
					<span className={s.railLine()} />
					<span className={s.railDot()} />
					<span className={s.railLine()} />
					<span className={s.railDot()} />
					<span className={s.railLine()} />
					<span className={s.railDot()} />
				</div>
			</div>
			<div className={cn(s.notch(), "-top-7")} />
			<div className={cn(s.notch(), "-bottom-7")} />
			<div className={s.main()}>
				<h1 className={s.headline()}>{headline}</h1>
				{items.length ? (
					<div className={s.list()}>
						{items.map((item, i) => {
							const m = ogChangelogMarker({ kind: item.kind });
							return (
								<div key={`${i}-${item.text}`} className={s.item()}>
									<span className={m.marker()}>
										<svg
											viewBox="0 0 24 24"
											fill="none"
											stroke="currentColor"
											strokeWidth="2"
											strokeLinecap="round"
											strokeLinejoin="round"
											className={m.icon()}
											aria-hidden="true"
										>
											{OG_CHANGELOG_ICONS[item.kind].map((d) => (
												<path key={d} d={d} />
											))}
										</svg>
										{item.label ?? item.kind.charAt(0).toUpperCase() + item.kind.slice(1)}
									</span>
									<span className={s.text()}>{item.text}</span>
								</div>
							);
						})}
					</div>
				) : null}
			</div>
		</div>
	);
}

// packages/ui-svelte/src/lib/og-changelog/og-changelog.svelte
<script lang="ts">
import { cn } from "../lib/cn";
import {
	OG_CHANGELOG_ICONS,
	type OgChangelogKind,
	type OgChangelogMode,
	type OgChangelogTone,
	ogChangelog,
	ogChangelogMarker,
} from "./variants";

let {
	version,
	headline,
	site,
	logo,
	date,
	highlights,
	mode = "light",
	tone = "neutral",
	class: className,
}: {
	/** Release version, e.g. "v2.4.0"; also drawn as the background numeral. */
	version: string;
	headline: string;
	/** Product name shown top left. */
	site: string;
	logo?: string;
	/** Pre-formatted release date. */
	date?: string;
	/** Up to three entries; `label` defaults to the capitalised kind. */
	highlights?: { kind: OgChangelogKind; text: string; label?: string }[];
	mode?: OgChangelogMode;
	tone?: OgChangelogTone;
	class?: string;
} = $props();

const s = $derived(ogChangelog({ mode, tone }));
const items = $derived(highlights?.slice(0, 3) ?? []);
</script>

<div data-slot="og-changelog" class={cn(s.root(), className)}>
	<div class={s.ghost()}>{version}</div>
	<div class={s.stub()}>
		<div class={s.brand()}>
			{#if logo}<img src={logo} alt="" class={s.logo()} />{/if}
			<span class={s.site()}>{site}</span>
		</div>
		<div class={s.pill()}>
			<span class={s.pillText()}>{version}</span>
		</div>
		{#if date}<div class={s.date()}>{date}</div>{/if}
		<div class={s.rail()}>
			<span class={s.railHead()}></span>
			<span class={s.railLine()}></span>
			<span class={s.railDot()}></span>
			<span class={s.railLine()}></span>
			<span class={s.railDot()}></span>
			<span class={s.railLine()}></span>
			<span class={s.railDot()}></span>
		</div>
	</div>
	<div class={cn(s.notch(), "-top-7")}></div>
	<div class={cn(s.notch(), "-bottom-7")}></div>
	<div class={s.main()}>
		<h1 class={s.headline()}>{headline}</h1>
		{#if items.length}
			<div class={s.list()}>
				{#each items as item, i (`${i}-${item.text}`)}
					{@const m = ogChangelogMarker({ kind: item.kind })}
					<div class={s.item()}>
						<span class={m.marker()}>
							<svg
								viewBox="0 0 24 24"
								fill="none"
								stroke="currentColor"
								stroke-width="2"
								stroke-linecap="round"
								stroke-linejoin="round"
								class={m.icon()}
								aria-hidden="true"
							>
								{#each OG_CHANGELOG_ICONS[item.kind] as d (d)}<path {d} />{/each}
							</svg>{item.label ?? item.kind.charAt(0).toUpperCase() + item.kind.slice(1)}</span>
						<span class={s.text()}>{item.text}</span>
					</div>
				{/each}
			</div>
		{/if}
	</div>
</div>
