// packages/ui-react/src/og-stats-metrics/og-stats-metrics.tsx
import { cn } from "../lib/cn";
import { AREA_H, AREA_W, sparklinePath } from "./sparkline";
import {
	type OgStatsMetricsMode,
	type OgStatsMetricsTone,
	type OgStatsMetricsTrend,
	ogStatsMetrics,
} from "./variants";

export type { OgStatsMetricsMode, OgStatsMetricsTone, OgStatsMetricsTrend };

export interface OgStatsMetricsStat {
	label: string;
	/** Pre-formatted, e.g. "$1.2M". */
	value: string;
	/** Pre-formatted, e.g. "+18%". Shown on the hero stat only. */
	delta?: string;
	trend?: OgStatsMetricsTrend;
}

export interface OgStatsMetricsProps {
	headline: string;
	/** First entry is the hero number; the next two print as one plain line; extras are dropped. */
	stats: OgStatsMetricsStat[];
	site?: string;
	logo?: string;
	/** Pre-formatted, e.g. "Q3 2026". */
	period?: string;
	/** Raw values drawn as the soft area shape behind the card. */
	sparkline?: number[];
	mode?: OgStatsMetricsMode;
	tone?: OgStatsMetricsTone;
	className?: string;
}

const UP = "M12 5l8 12h-16z";
const DOWN = "M12 19l8 -12h-16z";
const SEP = "  ·  ";

/** A 1200x630 card led by one big metric. Render it to PNG with takumi-js (see the docs recipe). */
export function OgStatsMetrics({
	headline,
	stats,
	site,
	logo,
	period,
	sparkline,
	mode = "light",
	tone = "neutral",
	className,
}: OgStatsMetricsProps) {
	const s = ogStatsMetrics({ mode, tone });
	const spark = sparkline ? sparklinePath(sparkline) : null;
	const [hero, ...rest] = stats;
	const secondary = rest
		.slice(0, 2)
		.map((stat) => `${stat.value} ${stat.label}`)
		.join(SEP);
	return (
		<div data-slot="og-stats-metrics" className={cn(s.root(), className)}>
			{spark ? (
				<svg
					aria-hidden="true"
					width={AREA_W}
					height={AREA_H}
					viewBox={`0 0 ${AREA_W} ${AREA_H}`}
					fill="none"
					className={s.area()}
				>
					<polygon points={spark.area} fill="currentColor" fillOpacity="0.12" />
					<polyline
						points={spark.line}
						stroke="currentColor"
						strokeOpacity="0.4"
						strokeWidth="5"
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
				</svg>
			) : null}
			{site || logo || period ? (
				<div className={s.header()}>
					<div className={s.brand()}>
						{logo ? <img src={logo} alt="" className={s.logo()} /> : null}
						{site ? <span className={s.site()}>{site}</span> : null}
					</div>
					{period ? <span className={s.period()}>{period}</span> : null}
				</div>
			) : null}
			<div className={s.body()}>
				{hero ? (
					<>
						<span className={s.label()}>{hero.label}</span>
						<div className={s.hero()}>
							<span className={s.value()}>{hero.value}</span>
							{hero.delta ? (
								<span className={s.delta({ trend: hero.trend ?? "up" })}>
									<svg
										aria-hidden="true"
										width="24"
										height="24"
										viewBox="0 0 24 24"
										fill="currentColor"
										className={s.deltaIcon()}
									>
										<path d={hero.trend === "down" ? DOWN : UP} />
									</svg>
									<span className={s.deltaText()}>{hero.delta}</span>
								</span>
							) : null}
						</div>
					</>
				) : null}
				<h1 className={s.headline()}>{headline}</h1>
				{secondary ? <span className={s.secondary()}>{secondary}</span> : null}
			</div>
		</div>
	);
}

// packages/ui-svelte/src/lib/og-stats-metrics/og-stats-metrics.svelte
<script lang="ts">
import { cn } from "../lib/cn";
import { AREA_H, AREA_W, sparklinePath } from "./sparkline";
import {
	type OgStatsMetricsMode,
	type OgStatsMetricsTone,
	type OgStatsMetricsTrend,
	ogStatsMetrics,
} from "./variants";

let {
	headline,
	stats,
	site,
	logo,
	period,
	sparkline,
	mode = "light",
	tone = "neutral",
	class: className,
}: {
	headline: string;
	/** First entry is the hero number; the next two print as one plain line; extras are dropped. */
	stats: { label: string; value: string; delta?: string; trend?: OgStatsMetricsTrend }[];
	site?: string;
	logo?: string;
	/** Pre-formatted, e.g. "Q3 2026". */
	period?: string;
	/** Raw values drawn as the soft area shape behind the card. */
	sparkline?: number[];
	mode?: OgStatsMetricsMode;
	tone?: OgStatsMetricsTone;
	class?: string;
} = $props();

const UP = "M12 5l8 12h-16z";
const DOWN = "M12 19l8 -12h-16z";
const SEP = "  ·  ";

const s = $derived(ogStatsMetrics({ mode, tone }));
const spark = $derived(sparkline ? sparklinePath(sparkline) : null);
const hero = $derived(stats[0]);
const secondary = $derived(
	stats
		.slice(1, 3)
		.map((stat) => `${stat.value} ${stat.label}`)
		.join(SEP),
);
</script>

<div data-slot="og-stats-metrics" class={cn(s.root(), className)}>
	{#if spark}
		<svg
			aria-hidden="true"
			width={AREA_W}
			height={AREA_H}
			viewBox="0 0 {AREA_W} {AREA_H}"
			fill="none"
			class={s.area()}
		>
			<polygon points={spark.area} fill="currentColor" fill-opacity="0.12" />
			<polyline
				points={spark.line}
				stroke="currentColor"
				stroke-opacity="0.4"
				stroke-width="5"
				stroke-linecap="round"
				stroke-linejoin="round"
			/>
		</svg>
	{/if}
	{#if site || logo || period}
		<div class={s.header()}>
			<div class={s.brand()}>
				{#if logo}<img src={logo} alt="" class={s.logo()} />{/if}
				{#if site}<span class={s.site()}>{site}</span>{/if}
			</div>
			{#if period}<span class={s.period()}>{period}</span>{/if}
		</div>
	{/if}
	<div class={s.body()}>
		{#if hero}
			<span class={s.label()}>{hero.label}</span>
			<div class={s.hero()}>
				<span class={s.value()}>{hero.value}</span>
				{#if hero.delta}
					<span class={s.delta({ trend: hero.trend ?? "up" })}>
						<svg
							aria-hidden="true"
							width="24"
							height="24"
							viewBox="0 0 24 24"
							fill="currentColor"
							class={s.deltaIcon()}
						>
							<path d={hero.trend === "down" ? DOWN : UP} />
						</svg>
						<span class={s.deltaText()}>{hero.delta}</span>
					</span>
				{/if}
			</div>
		{/if}
		<h1 class={s.headline()}>{headline}</h1>
		{#if secondary}<span class={s.secondary()}>{secondary}</span>{/if}
	</div>
</div>
