// packages/demos/src/usage/svelte/chart-brush.svelte
<script lang="ts">
import { ChartBrush } from "@baby-ui/svelte";
import {
	CartesianGrid,
	type ChartConfig,
	ChartContainer,
	XAxis,
	YAxis,
} from "@baby-ui/svelte/chart";
import { Line, LineChart } from "@baby-ui/svelte/line-chart";

const data = Array.from({ length: 60 }, (_, i) => ({
	date: new Date(Date.UTC(2026, 0, 1 + i)),
	orders: 120 + Math.round(40 * Math.sin(i / 5)),
}));

const config = {
	orders: { label: "Orders", color: "var(--chart-1)" },
} satisfies ChartConfig;

let range = $state<[Date, Date]>();
</script>

<ChartContainer {config} title="Orders" aspect="auto" class="h-96">
	<LineChart {data} xDomain={range}>
		<CartesianGrid />
		<YAxis />
		<XAxis />
		<Line dataKey="orders" />
	</LineChart>
	<ChartBrush {data} dataKeys={["orders"]} bind:range />
</ChartContainer>

// packages/demos/src/react/chart-brush.tsx
"use client";

import {
	CartesianGrid,
	ChartBrush,
	type ChartBrushVariant,
	type ChartConfig,
	ChartContainer,
	ChartTooltip,
	Line,
	LineChart,
	XAxis,
	YAxis,
} from "@baby-ui/react";
import { useState } from "react";
import { VISITORS, VISITORS_CONFIG } from "../data/visitors";

type Props = Record<string, unknown>;

const config = VISITORS_CONFIG satisfies ChartConfig;
const first = VISITORS[7]?.date ?? new Date();
const last = VISITORS[21]?.date ?? new Date();

export function ChartBrushDemo({ props }: { props: Props }) {
	const [range, setRange] = useState<[Date, Date]>([first, last]);
	return (
		<div className="w-full max-w-3xl">
			<ChartContainer
				config={config}
				title="Daily visitors"
				aspect="auto"
				className="h-96"
			>
				<LineChart data={VISITORS} xDomain={range}>
					<CartesianGrid />
					<YAxis />
					<XAxis />
					<Line dataKey="desktop" />
					<Line dataKey="mobile" />
					<ChartTooltip />
				</LineChart>
				<ChartBrush
					data={VISITORS}
					dataKeys={["desktop", "mobile"]}
					range={range}
					onRangeChange={setRange}
					variant={(props.variant as ChartBrushVariant) ?? "area"}
					height={Number(props.height ?? 64)}
				/>
			</ChartContainer>
		</div>
	);
}
