// packages/ui-react/src/light-caustics/light-caustics.tsx
"use client";

import type { ReactNode } from "react";
import { cn } from "../lib/cn";
import { useCanvasEngine } from "../lib/use-canvas-engine";
import { type LightCausticsOptions, mountLightCaustics } from "./caustics";
import {
	LIGHT_CAUSTICS_COLORS,
	LIGHT_CAUSTICS_SPEED,
	type LightCausticsPosition,
	type LightCausticsSpeed,
	type LightCausticsTone,
	lightCaustics,
} from "./variants";

export type { LightCausticsPosition, LightCausticsSpeed, LightCausticsTone };

export interface LightCausticsProps {
	tone?: LightCausticsTone;
	speed?: LightCausticsSpeed;
	position?: LightCausticsPosition;
	/** Effect strength, 0 to 2. */
	intensity?: number;
	/** Film grain, 0 to 1. */
	grain?: number;
	className?: string;
	children?: ReactNode;
}

/** Rippling underwater caustic filaments over a tinted base, drawn in WebGL from theme tokens. */
export function LightCaustics({
	tone = "ocean",
	speed = "normal",
	position = "absolute",
	intensity = 1,
	grain = 0,
	className,
	children,
}: LightCausticsProps) {
	const options: LightCausticsOptions = {
		colors: LIGHT_CAUSTICS_COLORS[tone],
		speed: LIGHT_CAUSTICS_SPEED[speed],
		intensity,
		grain,
	};
	const { root, canvas, webgl } = useCanvasEngine(mountLightCaustics, options, [
		tone,
		speed,
		intensity,
		grain,
	]);
	const s = lightCaustics({ tone, speed, position, webgl });

	return (
		<div ref={root} data-slot="light-caustics" className={cn(s.root(), className)}>
			<div aria-hidden className={s.fallback()} />
			<canvas ref={canvas} aria-hidden className={s.canvas()} />
			{children ? <div className={s.content()}>{children}</div> : null}
		</div>
	);
}

// packages/ui-svelte/src/lib/light-caustics/light-caustics.svelte
<script lang="ts">
import type { Snippet } from "svelte";
import { canvasEngine } from "../lib/canvas-engine.svelte";
import { cn } from "../lib/cn";
import { type LightCausticsOptions, mountLightCaustics } from "./caustics";
import {
	LIGHT_CAUSTICS_COLORS,
	LIGHT_CAUSTICS_SPEED,
	type LightCausticsPosition,
	type LightCausticsSpeed,
	type LightCausticsTone,
	lightCaustics,
} from "./variants";

let {
	tone = "ocean",
	speed = "normal",
	position = "absolute",
	intensity = 1,
	grain = 0,
	class: classProp,
	children,
}: {
	tone?: LightCausticsTone;
	speed?: LightCausticsSpeed;
	position?: LightCausticsPosition;
	/** Effect strength, 0 to 2. */
	intensity?: number;
	/** Film grain, 0 to 1. */
	grain?: number;
	class?: string;
	children?: Snippet;
} = $props();

let root: HTMLDivElement | undefined = $state();
let canvas: HTMLCanvasElement | undefined = $state();
const gl = canvasEngine(
	mountLightCaustics,
	() => ({ root, canvas }),
	() => options,
);
const s = $derived(lightCaustics({ tone, speed, position, webgl: gl.webgl }));
const options: LightCausticsOptions = $derived({
	colors: LIGHT_CAUSTICS_COLORS[tone],
	speed: LIGHT_CAUSTICS_SPEED[speed],
	intensity,
	grain,
});
</script>

<div bind:this={root} data-slot="light-caustics" class={cn(s.root(), classProp)}>
	<div aria-hidden="true" class={s.fallback()}></div>
	<canvas bind:this={canvas} aria-hidden="true" class={s.canvas()}></canvas>
	{#if children}
		<div class={s.content()}>{@render children()}</div>
	{/if}
</div>
