// packages/ui-svelte/src/lib/orbit-hero/orbit-hero.svelte
<script lang="ts" generics="T">
import type { Snippet } from "svelte";
import { untrack } from "svelte";
import type { HTMLAttributes } from "svelte/elements";
import Badge from "../badge/badge.svelte";
import Button from "../button/button.svelte";
import { cn } from "../lib/cn";
import {
	ORBIT_HERO_LABELS,
	ORBIT_HERO_TONES,
	ORBIT_INNER_RADIUS,
	ORBIT_OUTER_RADIUS,
	orbitDelay,
	orbitPlace,
	spinOrbits,
} from "./orbit";
import type {
	OrbitHeroAction,
	OrbitHeroGroup,
	OrbitHeroLabels,
	OrbitHeroTone,
} from "./types";
import { type OrbitHeroSize, type OrbitHeroVariant, orbitHero } from "./variants";

type Props = Omit<HTMLAttributes<HTMLElement>, "title"> & {
	headline: string;
	/** A second, muted headline line. */
	subheading?: string;
	description?: string;
	/** Pill above the headline. */
	badge?: string;
	/** The first is the primary action; the rest are outlined. */
	actions?: OrbitHeroAction[];
	/** Item sets for the rings; the centre's top half cycles through them. */
	groups: OrbitHeroGroup<T>[];
	/** Draws one ring item, usually a 24px-grid icon; it is sized to 32px. */
	item: Snippet<[T]>;
	tones?: OrbitHeroTone[];
	/** Bindable index into `groups`. */
	group?: number;
	onGroupChange?: (group: number) => void;
	/** Bindable index into `tones`. */
	tone?: number;
	onToneChange?: (tone: number) => void;
	/** Ms between automatic changes, alternating group and tone; 0 stops them. */
	interval?: number;
	labels?: Partial<OrbitHeroLabels>;
	variant?: OrbitHeroVariant;
	size?: OrbitHeroSize;
};

let {
	headline,
	subheading,
	description,
	badge,
	actions = [],
	groups,
	item,
	tones = ORBIT_HERO_TONES,
	group = $bindable(0),
	onGroupChange,
	tone = $bindable(0),
	onToneChange,
	interval = 4000,
	labels: labelsProp,
	variant = "panel",
	size = "screen",
	class: classProp,
	style,
	...rest
}: Props = $props();

const wrap = (index: number, length: number) =>
	length ? ((index % length) + length) % length : 0;
const reducedMotion = () => matchMedia("(prefers-reduced-motion: reduce)").matches;

const noiseId = $props.id();
const s = $derived(orbitHero({ variant, size }));
const labels = $derived({ ...ORBIT_HERO_LABELS, ...labelsProp });
const groupIndex = $derived(wrap(group, groups.length));
const toneIndex = $derived(wrap(tone, tones.length));
const current = $derived(groups[groupIndex]);
const currentTone = $derived(tones[toneIndex]);
const live = $derived(
	actions.filter((a) => a.href !== undefined || a.onClick !== undefined),
);
const counts = $derived(groups.map((g) => g.count ?? g.outer.length + g.inner.length));
const maxCount = $derived(Math.max(1, ...counts));

// The value shown before the last change, and a counter that re-keys the swap animation.
let groupSwap = $state({ at: -1, from: -1, beat: 0 });
let toneSwap = $state({ at: -1, from: -1, beat: 0 });
$effect.pre(() => {
	const g = groupIndex;
	untrack(() => {
		if (groupSwap.at === -1) groupSwap = { at: g, from: -1, beat: 0 };
		else if (groupSwap.at !== g)
			groupSwap = { at: g, from: groupSwap.at, beat: groupSwap.beat + 1 };
	});
});
$effect.pre(() => {
	const t = toneIndex;
	untrack(() => {
		if (toneSwap.at === -1) toneSwap = { at: t, from: -1, beat: 0 };
		else if (toneSwap.at !== t)
			toneSwap = { at: t, from: toneSwap.at, beat: toneSwap.beat + 1 };
	});
});
const previous = $derived(groups[groupSwap.from]);
const previousTone = $derived(tones[toneSwap.from]);
const swapping = $derived(groupSwap.beat > 0 && previous !== undefined);
const inClass = $derived(groupSwap.beat > 0 ? "orbit-hero-in" : "");

function nextGroup() {
	group = wrap(groupIndex + 1, groups.length);
	onGroupChange?.(group);
}

function nextTone() {
	tone = wrap(toneIndex + 1, tones.length);
	onToneChange?.(tone);
}

$effect(() => {
	if (!interval || reducedMotion()) return;
	let cycle = 0;
	const id = setInterval(() => {
		if (cycle % 2 === 0) nextGroup();
		else nextTone();
		cycle += 1;
	}, interval);
	return () => clearInterval(id);
});

let stage: HTMLDivElement | undefined = $state();
let outer: HTMLDivElement | undefined = $state();
let inner: HTMLDivElement | undefined = $state();
$effect(() => {
	if (!stage || !outer || !inner || reducedMotion()) return;
	return spinOrbits(stage, outer, inner);
});
</script>

{#snippet ring(items: T[], radius: number, reverse: boolean, cls: string)}
	{#each items as entry, i (i)}
		<span
			class={cn(s.item(), cls)}
			style:translate={orbitPlace(i, items.length, radius)}
			style:--orbit-delay={orbitDelay(reverse ? items.length - i - 1 : i)}
		>
			{@render item(entry)}
		</span>
	{/each}
{/snippet}

<section
	data-slot="orbit-hero"
	class={cn(s.root(), classProp)}
	style={[style, currentTone ? `--orbit-tone: ${currentTone.color}` : ""].filter(Boolean).join(";")}
	{...rest}
>
	<div class={s.panel()}>
		<svg aria-hidden="true" class={s.noise()}>
			<filter id={noiseId}>
				<feTurbulence type="fractalNoise" baseFrequency="0.54" numOctaves="4" stitchTiles="stitch" />
				<feColorMatrix type="saturate" values="0" />
				<feComponentTransfer>
					<feFuncR type="linear" slope="0.61" />
					<feFuncG type="linear" slope="0.61" />
					<feFuncB type="linear" slope="0.61" />
					<feFuncA type="linear" slope="1" />
				</feComponentTransfer>
				<feComponentTransfer>
					<feFuncR type="linear" slope="3" intercept="-1" />
					<feFuncG type="linear" slope="3" intercept="-1" />
					<feFuncB type="linear" slope="3" intercept="-1" />
				</feComponentTransfer>
			</filter>
			<rect width="100%" height="100%" filter="url(#{noiseId})" />
		</svg>
		<div aria-hidden="true" class={s.glow()}></div>
		<div aria-hidden="true" class={s.glowWarm()}></div>
		<div aria-hidden="true" class={s.vignette()}></div>

		<div class={s.content()}>
			{#if badge}
				<Badge variant="outline" class={s.badge()}>{badge}</Badge>
			{/if}
			<h1 class={s.title()}>
				{headline}
				{#if subheading}<br /><span class={s.subheading()}>{subheading}</span>{/if}
			</h1>
			{#if description}<p class={s.description()}>{description}</p>{/if}
			{#if live.length}
				<div class={s.actions()}>
					{#each live as action, i (i)}
						{#if action.href !== undefined}
							<Button
								href={action.href}
								target={action.target}
								rel={action.target === "_blank" ? "noopener noreferrer" : undefined}
								variant={i === 0 ? "default" : "outline"}
								size="lg"
								onclick={action.onClick}
							>
								{action.label}
							</Button>
						{:else}
							<Button variant={i === 0 ? "default" : "outline"} size="lg" onclick={action.onClick}>
								{action.label}
							</Button>
						{/if}
					{/each}
				</div>
			{/if}
		</div>

		<div bind:this={stage} class={s.stage()}>
			{#if current}
				<div aria-hidden="true" class={s.readouts()}>
					<div class={s.countReadout()}>
						<div class={s.readoutRow()}>
							<span class={s.readoutLabel()}>{current.label}</span>
							{#key groupSwap.beat}
								<span class={s.readoutValue()}>{counts[groupIndex]}</span>
							{/key}
						</div>
						<div class={s.bars()}>
							{#each counts as count, i (i)}
								<span
									data-active={i === groupIndex}
									class={s.bar()}
									style:height="{Math.max(3, (count / maxCount) * 28)}px"
								></span>
							{/each}
						</div>
					</div>
					<div class={s.toneReadout()}>
						<div class={s.readoutRow()}>
							<span class={s.swatch()}></span>
							<span class={s.readoutLabel()}>Tone</span>
							{#key toneSwap.beat}
								<span class={s.toneValue()}>{currentTone?.label}</span>
							{/key}
						</div>
					</div>
				</div>
			{/if}

			<div class={s.wheel()}>
				<div class={s.visual()}>
					<div class={s.ringBox()}><div class={s.ringOuter()}></div></div>
					<div class={s.ringBox()}><div class={s.ringMiddle()}></div></div>
					<div class={s.ringBox()}><div class={s.ringInner()}></div></div>

					<div aria-hidden="true" class={s.orbits()}>
						<div bind:this={outer} class={s.orbit()}>
							{#key groupSwap.beat}
								{#if swapping && previous}
									{@render ring(previous.outer, ORBIT_OUTER_RADIUS, false, "orbit-hero-out")}
								{/if}
								{#if current}
									{@render ring(current.outer, ORBIT_OUTER_RADIUS, false, inClass)}
								{/if}
							{/key}
						</div>
						<div bind:this={inner} class={s.orbit()}>
							{#key groupSwap.beat}
								{#if swapping && previous}
									{@render ring(previous.inner, ORBIT_INNER_RADIUS, true, "orbit-hero-out")}
								{/if}
								{#if current}
									{@render ring(current.inner, ORBIT_INNER_RADIUS, true, inClass)}
								{/if}
							{/key}
						</div>
					</div>

					<div class={s.controlsBox()}>
						<div class={s.controls()}>
							<Button
								variant="ghost"
								class={s.groupControl()}
								aria-label="{labels.group}, currently {current?.label ?? ''}"
								onclick={nextGroup}
							>
								{#key groupSwap.beat}
									{#if swapping && previous}
										<span class={cn(s.groupLabel(), "orbit-hero-label-out")}>{previous.label}</span>
									{/if}
									<span class={cn(s.groupLabel(), groupSwap.beat > 0 && "orbit-hero-label-in")}>
										{current?.label}
									</span>
								{/key}
							</Button>
							<Button
								variant="ghost"
								class={s.toneControl()}
								aria-label="{labels.tone}, currently {currentTone?.label ?? ''}"
								onclick={nextTone}
							>
								{#key toneSwap.beat}
									{#if toneSwap.beat > 0 && previousTone}
										<span class={cn(s.toneLabel(), "orbit-hero-label-out")}>{previousTone.label}</span>
									{/if}
									<span class={cn(s.toneLabel(), toneSwap.beat > 0 && "orbit-hero-label-in")}>
										{currentTone?.label}
									</span>
								{/key}
							</Button>
						</div>
					</div>

					{#key groupSwap.beat + toneSwap.beat}
						{#if groupSwap.beat + toneSwap.beat > 0}
							<span aria-hidden="true" class={s.ripple()}></span>
						{/if}
					{/key}
				</div>
			</div>
		</div>
	</div>
</section>

// packages/ui-react/src/orbit-hero/orbit-hero.tsx
"use client";

import {
	type CSSProperties,
	type HTMLAttributes,
	type ReactNode,
	useCallback,
	useEffect,
	useId,
	useRef,
	useState,
} from "react";
import { Badge } from "../badge/badge";
import { Button } from "../button/button";
import { cn } from "../lib/cn";
import {
	ORBIT_HERO_LABELS,
	ORBIT_HERO_TONES,
	ORBIT_INNER_RADIUS,
	ORBIT_OUTER_RADIUS,
	orbitDelay,
	orbitPlace,
	spinOrbits,
} from "./orbit";
import type {
	OrbitHeroAction,
	OrbitHeroGroup,
	OrbitHeroLabels,
	OrbitHeroTone,
} from "./types";
import { type OrbitHeroSize, type OrbitHeroVariant, orbitHero } from "./variants";

export type {
	OrbitHeroAction,
	OrbitHeroGroup,
	OrbitHeroLabels,
	OrbitHeroSize,
	OrbitHeroTone,
	OrbitHeroVariant,
};

export interface OrbitHeroProps<T> extends Omit<HTMLAttributes<HTMLElement>, "title"> {
	headline: string;
	/** A second, muted headline line. */
	subheading?: string;
	description?: string;
	/** Pill above the headline. */
	badge?: string;
	/** The first is the primary action; the rest are outlined. */
	actions?: OrbitHeroAction[];
	/** Item sets for the rings; the centre's top half cycles through them. */
	groups: OrbitHeroGroup<T>[];
	/** Draws one ring item, usually a 24px-grid icon; it is sized to 32px. */
	renderItem: (item: T) => ReactNode;
	tones?: OrbitHeroTone[];
	/** Index into `groups`. Controlled when set. */
	group?: number;
	defaultGroup?: number;
	onGroupChange?: (group: number) => void;
	/** Index into `tones`. Controlled when set. */
	tone?: number;
	defaultTone?: number;
	onToneChange?: (tone: number) => void;
	/** Ms between automatic changes, alternating group and tone; 0 stops them. */
	interval?: number;
	labels?: Partial<OrbitHeroLabels>;
	variant?: OrbitHeroVariant;
	size?: OrbitHeroSize;
}

function useControlled(
	prop: number | undefined,
	initial: number,
	onChange?: (v: number) => void,
) {
	const [inner, setInner] = useState(initial);
	const value = prop ?? inner;
	const notify = useRef(onChange);
	notify.current = onChange;
	const controlled = prop !== undefined;
	const set = useCallback(
		(next: number) => {
			if (!controlled) setInner(next);
			notify.current?.(next);
		},
		[controlled],
	);
	return [value, set] as const;
}

/** The value shown before the last change, and a counter that re-keys the swap animation. */
function useSwap(value: number) {
	const [swap, setSwap] = useState({ at: value, from: -1, beat: 0 });
	if (swap.at !== value) {
		const next = { at: value, from: swap.at, beat: swap.beat + 1 };
		setSwap(next);
		return next;
	}
	return swap;
}

const reducedMotion = () => matchMedia("(prefers-reduced-motion: reduce)").matches;
const wrap = (index: number, length: number) =>
	length ? ((index % length) + length) % length : 0;

export function OrbitHero<T>({
	headline,
	subheading,
	description,
	badge,
	actions = [],
	groups,
	renderItem,
	tones = ORBIT_HERO_TONES,
	group: groupProp,
	defaultGroup = 0,
	onGroupChange,
	tone: toneProp,
	defaultTone = 0,
	onToneChange,
	interval = 4000,
	labels: labelsProp,
	variant = "panel",
	size = "screen",
	className,
	style,
	...props
}: OrbitHeroProps<T>) {
	const s = orbitHero({ variant, size });
	const labels = { ...ORBIT_HERO_LABELS, ...labelsProp };
	const noiseId = useId();
	const [groupRaw, setGroup] = useControlled(groupProp, defaultGroup, onGroupChange);
	const [toneRaw, setTone] = useControlled(toneProp, defaultTone, onToneChange);
	const groupIndex = wrap(groupRaw, groups.length);
	const toneIndex = wrap(toneRaw, tones.length);
	const groupSwap = useSwap(groupIndex);
	const toneSwap = useSwap(toneIndex);
	const current = groups[groupIndex];
	const previous = groups[groupSwap.from];
	const tone = tones[toneIndex];
	const live = actions.filter((a) => a.href !== undefined || a.onClick !== undefined);
	const counts = groups.map((g) => g.count ?? g.outer.length + g.inner.length);
	const maxCount = Math.max(1, ...counts);

	const nextGroup = () => setGroup(wrap(groupIndex + 1, groups.length));
	const nextTone = () => setTone(wrap(toneIndex + 1, tones.length));
	const advance = useRef({ nextGroup, nextTone });
	advance.current = { nextGroup, nextTone };

	useEffect(() => {
		if (!interval || reducedMotion()) return;
		let cycle = 0;
		const id = setInterval(() => {
			if (cycle % 2 === 0) advance.current.nextGroup();
			else advance.current.nextTone();
			cycle += 1;
		}, interval);
		return () => clearInterval(id);
	}, [interval]);

	const stageRef = useRef<HTMLDivElement>(null);
	const outerRef = useRef<HTMLDivElement>(null);
	const innerRef = useRef<HTMLDivElement>(null);
	useEffect(() => {
		const [stage, outer, inner] = [stageRef.current, outerRef.current, innerRef.current];
		if (!stage || !outer || !inner || reducedMotion()) return;
		return spinOrbits(stage, outer, inner);
	}, []);

	const ring = (items: T[], radius: number, reverse: boolean, cls: string) =>
		items.map((item, i) => (
			<span
				// biome-ignore lint/suspicious/noArrayIndexKey: ring slots are positional and items can repeat.
				key={i}
				className={cn(s.item(), cls)}
				style={
					{
						translate: orbitPlace(i, items.length, radius),
						"--orbit-delay": orbitDelay(reverse ? items.length - i - 1 : i),
					} as CSSProperties
				}
			>
				{renderItem(item)}
			</span>
		));

	const rings = (g: OrbitHeroGroup<T>, which: "outer" | "inner", cls: string) =>
		which === "outer"
			? ring(g.outer, ORBIT_OUTER_RADIUS, false, cls)
			: ring(g.inner, ORBIT_INNER_RADIUS, true, cls);

	const swapping = groupSwap.beat > 0 && previous !== undefined;
	const inClass = groupSwap.beat > 0 ? "orbit-hero-in" : "";

	return (
		<section
			data-slot="orbit-hero"
			className={cn(s.root(), className)}
			style={{ ...style, "--orbit-tone": tone?.color } as CSSProperties}
			{...props}
		>
			<div className={s.panel()}>
				<svg aria-hidden className={s.noise()}>
					<filter id={noiseId}>
						<feTurbulence
							type="fractalNoise"
							baseFrequency="0.54"
							numOctaves={4}
							stitchTiles="stitch"
						/>
						<feColorMatrix type="saturate" values="0" />
						<feComponentTransfer>
							<feFuncR type="linear" slope="0.61" />
							<feFuncG type="linear" slope="0.61" />
							<feFuncB type="linear" slope="0.61" />
							<feFuncA type="linear" slope="1" />
						</feComponentTransfer>
						<feComponentTransfer>
							<feFuncR type="linear" slope="3" intercept="-1" />
							<feFuncG type="linear" slope="3" intercept="-1" />
							<feFuncB type="linear" slope="3" intercept="-1" />
						</feComponentTransfer>
					</filter>
					<rect width="100%" height="100%" filter={`url(#${noiseId})`} />
				</svg>
				<div aria-hidden className={s.glow()} />
				<div aria-hidden className={s.glowWarm()} />
				<div aria-hidden className={s.vignette()} />

				<div className={s.content()}>
					{badge ? (
						<Badge variant="outline" className={s.badge()}>
							{badge}
						</Badge>
					) : null}
					<h1 className={s.title()}>
						{headline}
						{subheading ? (
							<>
								<br />
								<span className={s.subheading()}>{subheading}</span>
							</>
						) : null}
					</h1>
					{description ? <p className={s.description()}>{description}</p> : null}
					{live.length ? (
						<div className={s.actions()}>
							{live.map((action, i) => {
								const v = i === 0 ? "default" : "outline";
								return action.href !== undefined ? (
									<Button
										// biome-ignore lint/suspicious/noArrayIndexKey: actions render in a fixed order and can repeat.
										key={i}
										href={action.href}
										target={action.target}
										rel={action.target === "_blank" ? "noopener noreferrer" : undefined}
										variant={v}
										size="lg"
										onClick={action.onClick}
									>
										{action.label}
									</Button>
								) : (
									<Button
										// biome-ignore lint/suspicious/noArrayIndexKey: actions render in a fixed order and can repeat.
										key={i}
										variant={v}
										size="lg"
										onClick={action.onClick}
									>
										{action.label}
									</Button>
								);
							})}
						</div>
					) : null}
				</div>

				<div ref={stageRef} className={s.stage()}>
					{current ? (
						<div aria-hidden className={s.readouts()}>
							<div className={s.countReadout()}>
								<div className={s.readoutRow()}>
									<span className={s.readoutLabel()}>{current.label}</span>
									<span key={groupSwap.beat} className={s.readoutValue()}>
										{counts[groupIndex]}
									</span>
								</div>
								<div className={s.bars()}>
									{counts.map((count, i) => (
										<span
											// biome-ignore lint/suspicious/noArrayIndexKey: one bar per group, in group order.
											key={i}
											data-active={i === groupIndex}
											className={s.bar()}
											style={{ height: `${Math.max(3, (count / maxCount) * 28)}px` }}
										/>
									))}
								</div>
							</div>
							<div className={s.toneReadout()}>
								<div className={s.readoutRow()}>
									<span className={s.swatch()} />
									<span className={s.readoutLabel()}>Tone</span>
									<span key={toneSwap.beat} className={s.toneValue()}>
										{tone?.label}
									</span>
								</div>
							</div>
						</div>
					) : null}

					<div className={s.wheel()}>
						<div className={s.visual()}>
							<div className={s.ringBox()}>
								<div className={s.ringOuter()} />
							</div>
							<div className={s.ringBox()}>
								<div className={s.ringMiddle()} />
							</div>
							<div className={s.ringBox()}>
								<div className={s.ringInner()} />
							</div>

							<div aria-hidden className={s.orbits()}>
								<div ref={outerRef} className={s.orbit()}>
									{swapping ? (
										<span key={`out-${groupSwap.beat}`}>
											{rings(previous, "outer", "orbit-hero-out")}
										</span>
									) : null}
									{current ? (
										<span key={`in-${groupSwap.beat}`}>
											{rings(current, "outer", inClass)}
										</span>
									) : null}
								</div>
								<div ref={innerRef} className={s.orbit()}>
									{swapping ? (
										<span key={`out-${groupSwap.beat}`}>
											{rings(previous, "inner", "orbit-hero-out")}
										</span>
									) : null}
									{current ? (
										<span key={`in-${groupSwap.beat}`}>
											{rings(current, "inner", inClass)}
										</span>
									) : null}
								</div>
							</div>

							<div className={s.controlsBox()}>
								<div className={s.controls()}>
									<Button
										variant="ghost"
										className={s.groupControl()}
										aria-label={`${labels.group}, currently ${current?.label ?? ""}`}
										onClick={nextGroup}
									>
										{swapping ? (
											<span
												key={`out-${groupSwap.beat}`}
												className={cn(s.groupLabel(), "orbit-hero-label-out")}
											>
												{previous.label}
											</span>
										) : null}
										<span
											key={`in-${groupSwap.beat}`}
											className={cn(
												s.groupLabel(),
												groupSwap.beat > 0 && "orbit-hero-label-in",
											)}
										>
											{current?.label}
										</span>
									</Button>
									<Button
										variant="ghost"
										className={s.toneControl()}
										aria-label={`${labels.tone}, currently ${tone?.label ?? ""}`}
										onClick={nextTone}
									>
										{toneSwap.beat > 0 && tones[toneSwap.from] ? (
											<span
												key={`out-${toneSwap.beat}`}
												className={cn(s.toneLabel(), "orbit-hero-label-out")}
											>
												{tones[toneSwap.from]?.label}
											</span>
										) : null}
										<span
											key={`in-${toneSwap.beat}`}
											className={cn(
												s.toneLabel(),
												toneSwap.beat > 0 && "orbit-hero-label-in",
											)}
										>
											{tone?.label}
										</span>
									</Button>
								</div>
							</div>

							{groupSwap.beat + toneSwap.beat > 0 ? (
								<span
									aria-hidden
									key={groupSwap.beat + toneSwap.beat}
									className={s.ripple()}
								/>
							) : null}
						</div>
					</div>
				</div>
			</div>
		</section>
	);
}
