// packages/ui-react/src/flight-status-card/flight-status-card.tsx
import type { CSSProperties } from "react";
import { Badge } from "../badge/badge";
import { Card, CardAction, CardContent, CardHeader, CardTitle } from "../card/card";
import { cn } from "../lib/cn";
import {
	clampProgress,
	FLIGHT_STATUS_LABELS,
	type FlightStatus,
	type FlightStatusLabels,
	MATRIX_DOT,
	MATRIX_HEIGHT,
	MATRIX_WIDTH,
	matrixDots,
} from "./types";
import {
	FLIGHT_STATUS_TONE,
	FLIGHT_TONE_BADGE,
	type FlightStatusDisplay,
	type FlightStatusTone,
	flightStatusCard,
} from "./variants";

export type { FlightStatus, FlightStatusDisplay, FlightStatusLabels, FlightStatusTone };

export interface FlightStatusCardProps {
	departureCode: string;
	arrivalCode: string;
	departureCity: string;
	arrivalCity: string;
	departureTime: string;
	arrivalTime: string;
	status: FlightStatus;
	/** Share of the route flown, 0 to 100. */
	progress: number;
	/** Flight number shown as the card title. */
	flight?: string;
	/** Headline of the side panel, e.g. an arrival estimate. */
	eta?: string;
	etaNote?: string;
	/** Accent line under the side panel, e.g. the next cabin service. */
	nextEvent?: string;
	/** Text at the right end of the progress track. */
	remaining?: string;
	/** Overrides the tone the status picks. */
	tone?: FlightStatusTone;
	display?: FlightStatusDisplay;
	labels?: Partial<FlightStatusLabels>;
	className?: string;
}

type Styles = ReturnType<typeof flightStatusCard>;

function Code({
	code,
	display,
	s,
}: {
	code: string;
	display: FlightStatusDisplay;
	s: Styles;
}) {
	if (display === "text") {
		return (
			<span className={s.code()} aria-hidden>
				{code}
			</span>
		);
	}
	return (
		<span className={s.code()} aria-hidden>
			{[...code].map((char, i) => (
				<svg
					key={`${char}-${i}`}
					aria-hidden
					viewBox={`0 0 ${MATRIX_WIDTH} ${MATRIX_HEIGHT}`}
					className={s.char()}
					style={{ "--flight-status-delay": `${i * 90}ms` } as CSSProperties}
				>
					{matrixDots(char).map((dot) => (
						<circle
							key={`${dot.x}-${dot.y}`}
							cx={dot.x}
							cy={dot.y}
							r={MATRIX_DOT / 2}
							className={dot.on ? s.dotOn() : s.dotOff()}
						/>
					))}
				</svg>
			))}
		</span>
	);
}

/** Flight route, status and progress; every value is a prop the caller keeps current. */
export function FlightStatusCard({
	departureCode,
	arrivalCode,
	departureCity,
	arrivalCity,
	departureTime,
	arrivalTime,
	status,
	progress,
	flight,
	eta,
	etaNote,
	nextEvent,
	remaining,
	tone,
	display = "matrix",
	labels,
	className,
}: FlightStatusCardProps) {
	const text = { ...FLIGHT_STATUS_LABELS, ...labels };
	const activeTone = tone ?? FLIGHT_STATUS_TONE[status];
	const s = flightStatusCard({ tone: activeTone, display });
	const pct = clampProgress(progress);
	const panel = eta || etaNote || nextEvent;

	return (
		<Card
			data-slot="flight-status-card"
			data-status={status}
			className={cn(s.root(), className)}
		>
			<CardHeader>
				{flight ? (
					<CardTitle className="font-mono tracking-wide">{flight}</CardTitle>
				) : null}
				<CardAction>
					<Badge variant={FLIGHT_TONE_BADGE[activeTone]} dot>
						{text[status]}
					</Badge>
				</CardAction>
			</CardHeader>
			<CardContent className="flex flex-col gap-5">
				<div className={s.top()}>
					<div className={s.route()}>
						<span className="sr-only">
							{`${departureCode} ${departureCity} ${text.to} ${arrivalCode} ${arrivalCity}`}
						</span>
						<div className={s.endpoint()}>
							<Code code={departureCode} display={display} s={s} />
							<span className={s.city()}>{departureCity}</span>
							<span className={s.time()}>{departureTime}</span>
						</div>
						<svg
							viewBox="0 0 24 24"
							fill="none"
							stroke="currentColor"
							strokeWidth="2"
							strokeLinecap="round"
							strokeLinejoin="round"
							aria-hidden
							className={s.arrow()}
						>
							<path d="M5 12h14" />
							<path d="M13 18l6 -6" />
							<path d="M13 6l6 6" />
						</svg>
						<div className={cn(s.endpoint(), "items-end text-right")}>
							<Code code={arrivalCode} display={display} s={s} />
							<span className={s.city()}>{arrivalCity}</span>
							<span className={s.time()}>{arrivalTime}</span>
						</div>
					</div>
					{panel ? (
						<div className={s.eta()}>
							{eta ? <span className={s.etaValue()}>{eta}</span> : null}
							{etaNote ? <span className={s.etaNote()}>{etaNote}</span> : null}
							{nextEvent ? <span className={s.event()}>{nextEvent}</span> : null}
						</div>
					) : null}
				</div>
				<div
					role="progressbar"
					aria-label={text.progress}
					aria-valuemin={0}
					aria-valuemax={100}
					aria-valuenow={Math.round(pct)}
					aria-valuetext={remaining}
					className={s.track()}
				>
					<div className={s.reveal()}>
						<div className={s.fill()} style={{ width: `${pct}%` }}>
							<span className={s.plane()}>
								<svg
									viewBox="0 0 24 24"
									fill="none"
									stroke="currentColor"
									strokeWidth="2"
									strokeLinecap="round"
									strokeLinejoin="round"
									aria-hidden
								>
									<path d="M16 10h4a2 2 0 0 1 0 4h-4l-4 7h-3l2 -7h-4l-2 2h-3l2 -4l-2 -4h3l2 2h4l-2 -7h3z" />
								</svg>
							</span>
						</div>
					</div>
					{remaining ? (
						<span className={s.remaining()} aria-hidden>
							{remaining}
						</span>
					) : null}
				</div>
			</CardContent>
		</Card>
	);
}

// packages/ui-svelte/src/lib/flight-status-card/flight-status-card.svelte
<script lang="ts">
import Badge from "../badge/badge.svelte";
import Card from "../card/card.svelte";
import CardAction from "../card/card-action.svelte";
import CardContent from "../card/card-content.svelte";
import CardHeader from "../card/card-header.svelte";
import CardTitle from "../card/card-title.svelte";
import { cn } from "../lib/cn";
import {
	clampProgress,
	FLIGHT_STATUS_LABELS,
	type FlightStatus,
	type FlightStatusLabels,
	MATRIX_DOT,
	MATRIX_HEIGHT,
	MATRIX_WIDTH,
	matrixDots,
} from "./types";
import {
	FLIGHT_STATUS_TONE,
	FLIGHT_TONE_BADGE,
	type FlightStatusDisplay,
	type FlightStatusTone,
	flightStatusCard,
} from "./variants";

let {
	departureCode,
	arrivalCode,
	departureCity,
	arrivalCity,
	departureTime,
	arrivalTime,
	status,
	progress,
	flight,
	eta,
	etaNote,
	nextEvent,
	remaining,
	tone,
	display = "matrix",
	labels,
	class: classProp,
}: {
	departureCode: string;
	arrivalCode: string;
	departureCity: string;
	arrivalCity: string;
	departureTime: string;
	arrivalTime: string;
	status: FlightStatus;
	/** Share of the route flown, 0 to 100. */
	progress: number;
	/** Flight number shown as the card title. */
	flight?: string;
	/** Headline of the side panel, e.g. an arrival estimate. */
	eta?: string;
	etaNote?: string;
	/** Accent line under the side panel, e.g. the next cabin service. */
	nextEvent?: string;
	/** Text at the right end of the progress track. */
	remaining?: string;
	/** Overrides the tone the status picks. */
	tone?: FlightStatusTone;
	display?: FlightStatusDisplay;
	labels?: Partial<FlightStatusLabels>;
	class?: string;
} = $props();

const text = $derived({ ...FLIGHT_STATUS_LABELS, ...labels });
const activeTone = $derived(tone ?? FLIGHT_STATUS_TONE[status]);
const s = $derived(flightStatusCard({ tone: activeTone, display }));
const pct = $derived(clampProgress(progress));
const panel = $derived(Boolean(eta || etaNote || nextEvent));
</script>

{#snippet code(value: string)}
	{#if display === "text"}
		<span class={s.code()} aria-hidden="true">{value}</span>
	{:else}
		<span class={s.code()} aria-hidden="true">
			{#each [...value] as char, i (`${char}-${i}`)}
				<svg
					viewBox="0 0 {MATRIX_WIDTH} {MATRIX_HEIGHT}"
					class={s.char()}
					style:--flight-status-delay="{i * 90}ms"
				>
					{#each matrixDots(char) as dot (`${dot.x}-${dot.y}`)}
						<circle
							cx={dot.x}
							cy={dot.y}
							r={MATRIX_DOT / 2}
							class={dot.on ? s.dotOn() : s.dotOff()}
						/>
					{/each}
				</svg>
			{/each}
		</span>
	{/if}
{/snippet}

<Card data-slot="flight-status-card" data-status={status} class={cn(s.root(), classProp)}>
	<CardHeader>
		{#if flight}<CardTitle class="font-mono tracking-wide">{flight}</CardTitle>{/if}
		<CardAction>
			<Badge variant={FLIGHT_TONE_BADGE[activeTone]} dot>{text[status]}</Badge>
		</CardAction>
	</CardHeader>
	<CardContent class="flex flex-col gap-5">
		<div class={s.top()}>
			<div class={s.route()}>
				<span class="sr-only">
					{`${departureCode} ${departureCity} ${text.to} ${arrivalCode} ${arrivalCity}`}
				</span>
				<div class={s.endpoint()}>
					{@render code(departureCode)}
					<span class={s.city()}>{departureCity}</span>
					<span class={s.time()}>{departureTime}</span>
				</div>
				<svg
					viewBox="0 0 24 24"
					fill="none"
					stroke="currentColor"
					stroke-width="2"
					stroke-linecap="round"
					stroke-linejoin="round"
					aria-hidden="true"
					class={s.arrow()}
				>
					<path d="M5 12h14" />
					<path d="M13 18l6 -6" />
					<path d="M13 6l6 6" />
				</svg>
				<div class={cn(s.endpoint(), "items-end text-right")}>
					{@render code(arrivalCode)}
					<span class={s.city()}>{arrivalCity}</span>
					<span class={s.time()}>{arrivalTime}</span>
				</div>
			</div>
			{#if panel}
				<div class={s.eta()}>
					{#if eta}<span class={s.etaValue()}>{eta}</span>{/if}
					{#if etaNote}<span class={s.etaNote()}>{etaNote}</span>{/if}
					{#if nextEvent}<span class={s.event()}>{nextEvent}</span>{/if}
				</div>
			{/if}
		</div>
		<div
			role="progressbar"
			aria-label={text.progress}
			aria-valuemin={0}
			aria-valuemax={100}
			aria-valuenow={Math.round(pct)}
			aria-valuetext={remaining}
			class={s.track()}
		>
			<div class={s.reveal()}>
				<div class={s.fill()} style:width="{pct}%">
					<span class={s.plane()}>
						<svg
							viewBox="0 0 24 24"
							fill="none"
							stroke="currentColor"
							stroke-width="2"
							stroke-linecap="round"
							stroke-linejoin="round"
							aria-hidden="true"
						>
							<path
								d="M16 10h4a2 2 0 0 1 0 4h-4l-4 7h-3l2 -7h-4l-2 2h-3l2 -4l-2 -4h3l2 2h4l-2 -7h3z"
							/>
						</svg>
					</span>
				</div>
			</div>
			{#if remaining}
				<span class={s.remaining()} aria-hidden="true">{remaining}</span>
			{/if}
		</div>
	</CardContent>
</Card>
