// packages/ui-react/src/github-stats/github-stats.tsx
"use client";

import { type ReactNode, useState } from "react";
import { Avatar, AvatarFallback, AvatarImage } from "../avatar";
import { Badge } from "../badge/badge";
import { Bar, BarChart, BarTooltip, BarXAxis, BarYAxis } from "../bar-chart";
import { ChartContainer, ChartTooltipContent } from "../chart";
import { Empty, EmptyDescription, EmptyHeader, EmptyTitle } from "../empty/empty";
import { GithubCalendar } from "../github-calendar";
import { cn } from "../lib/cn";
import { RollingDigits } from "../rolling-digits/rolling-digits";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "../select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "../tabs";
import {
	contributionInsights,
	contributionYears,
	formatChange,
	formatCount,
	formatDay,
	formatPercent,
	GITHUB_COUNT_KEYS,
	GITHUB_STATS_LABELS,
	type GithubStatsData,
	type GithubStatsLabels,
	type GithubStatsView,
	initials,
	mixShares,
	sameDaysChange,
	weeklyContributions,
	yearTotal,
} from "./core";
import {
	GITHUB_MIX_FILL,
	GITHUB_STATS_LAYOUT,
	type GithubStatsVariant,
	githubStats,
} from "./variants";

export type { GithubStatsData, GithubStatsLabels, GithubStatsVariant, GithubStatsView };

export interface GithubStatsProps {
	data: GithubStatsData;
	variant?: GithubStatsVariant;
	/** Controlled year (`"2026"`); pair with `onYearChange`. Defaults to the newest. */
	year?: string;
	defaultYear?: string;
	onYearChange?: (year: string) => void;
	view?: GithubStatsView;
	defaultView?: GithubStatsView;
	onViewChange?: (view: GithubStatsView) => void;
	locale?: string;
	labels?: Partial<GithubStatsLabels>;
	className?: string;
}

const REPO_LIMIT = 5;

/** A year on GitHub: the total and its trend, the facts behind it, the calendar, and where it went. */
export function GithubStats({
	data,
	variant = "default",
	year: yearProp,
	defaultYear,
	onYearChange,
	view: viewProp,
	defaultView = "days",
	onViewChange,
	locale,
	labels: labelsProp,
	className,
}: GithubStatsProps) {
	const labels = { ...GITHUB_STATS_LABELS, ...labelsProp };
	const styles = githubStats({ variant });
	const layout = GITHUB_STATS_LAYOUT[variant];
	const years = contributionYears(data.contributions);
	const [ownYear, setOwnYear] = useState(defaultYear ?? years[0] ?? "");
	const [ownView, setOwnView] = useState<GithubStatsView>(defaultView);
	const year = yearProp ?? ownYear;
	const view = viewProp ?? ownView;
	const days = data.contributions[year] ?? [];
	const total = yearTotal(days);
	const facts = contributionInsights(days);
	const change = sameDaysChange(data.contributions, year);

	const setYear = (next: string) => {
		if (yearProp === undefined) setOwnYear(next);
		onYearChange?.(next);
	};
	const setView = (next: string) => {
		if (next !== "days" && next !== "weeks") return;
		if (viewProp === undefined) setOwnView(next);
		onViewChange?.(next);
	};

	if (years.length === 0) {
		return (
			<div
				data-slot="github-stats"
				data-variant={variant}
				className={cn(styles.root(), className)}
			>
				<Empty variant="outline" size="sm" role="status">
					<EmptyHeader>
						<EmptyTitle>{labels.emptyTitle}</EmptyTitle>
						<EmptyDescription>{labels.emptyDescription}</EmptyDescription>
					</EmptyHeader>
				</Empty>
			</div>
		);
	}

	return (
		<div
			data-slot="github-stats"
			data-variant={variant}
			className={cn(styles.root(), className)}
		>
			<Tabs value={view} onValueChange={setView} variant="segment" size="sm">
				<header className={styles.head()}>
					<div className="min-w-0">
						<p className={styles.eyebrow()}>{labels.eyebrow}</p>
						<p className={styles.hero()}>
							{layout.animate ? (
								<RollingDigits
									variant="count"
									value={total}
									format={(value) => formatCount(Math.round(value), locale)}
									durationMs={900}
									size="md"
									className={cn("font-bold text-foreground", styles.heroValue())}
								/>
							) : (
								<span className={styles.heroValue()}>{formatCount(total, locale)}</span>
							)}
							<span className={styles.heroUnit()}>{labels.totalIn(year)}</span>
						</p>
						{change ? (
							<p className={styles.trendRow()}>
								<Badge
									size="sm"
									variant={
										change.ratio === null || change.ratio === 0
											? "secondary"
											: change.ratio > 0
												? "success"
												: "destructive"
									}
									className={styles.trend()}
								>
									<TrendArrow ratio={change.ratio} />
									{change.ratio === null
										? labels.newLabel
										: formatChange(change.ratio, locale)}
								</Badge>
								<span className={styles.compare()}>
									{labels.compare(change.previousYear)}
								</span>
							</p>
						) : null}
					</div>
					<div className={styles.controls()}>
						<TabsList aria-label={labels.view}>
							<TabsTrigger value="days">{labels.days}</TabsTrigger>
							<TabsTrigger value="weeks">{labels.weeks}</TabsTrigger>
						</TabsList>
						{years.length > 1 ? (
							<Select
								value={year}
								onValueChange={setYear}
								items={years.map((y) => ({ value: y, label: y }))}
							>
								<SelectTrigger aria-label={labels.year} className={styles.yearTrigger()}>
									<SelectValue />
								</SelectTrigger>
								<SelectContent>
									{years.map((y) => (
										<SelectItem key={y} value={y} className="font-mono text-xs">
											{y}
										</SelectItem>
									))}
								</SelectContent>
							</Select>
						) : null}
					</div>
				</header>

				<dl className={styles.insights()}>
					<Fact label={labels.longestStreak} styles={styles}>
						{labels.dayCount(facts.longestStreak)}
					</Fact>
					<Fact label={labels.currentStreak} styles={styles}>
						{labels.dayCount(facts.currentStreak)}
					</Fact>
					<Fact label={labels.bestDay} styles={styles}>
						{facts.best ? (
							<>
								{formatCount(facts.best.count, locale)}{" "}
								<span className={styles.insightNote()}>
									{formatDay(facts.best.date, locale)}
								</span>
							</>
						) : (
							"–"
						)}
					</Fact>
					<Fact label={labels.activeDays} styles={styles}>
						{formatCount(facts.activeDays, locale)}{" "}
						<span className={styles.insightNote()}>/ {days.length}</span>
					</Fact>
				</dl>

				<div className={styles.calendar()}>
					<TabsContent value="days" className={styles.panel()}>
						<GithubCalendar
							key={year}
							days={days}
							size={layout.calendar}
							tone="success"
							showTotal={false}
							locale={locale}
						/>
					</TabsContent>
					<TabsContent value="weeks" className={styles.panel()}>
						{view === "weeks" ? (
							<WeeklyChart days={days} labels={labels} locale={locale} />
						) : null}
					</TabsContent>
				</div>
			</Tabs>

			<dl className={styles.counts()}>
				{GITHUB_COUNT_KEYS.map((key) => (
					<div key={key} className={styles.count()}>
						<dt className={styles.countLabel()}>{labels[key]}</dt>
						<dd className="order-first">
							{layout.animate ? (
								<RollingDigits
									variant="count"
									value={data.counts[key]}
									format={(value) => formatCount(Math.round(value), locale)}
									durationMs={1200}
									size="md"
									className={cn("font-bold text-foreground", styles.countValue())}
								/>
							) : (
								<span className={styles.countValue()}>
									{formatCount(data.counts[key], locale)}
								</span>
							)}
						</dd>
					</div>
				))}
			</dl>

			{layout.footer && (data.mix || data.repositories?.length) ? (
				<div className={styles.footer()}>
					{data.mix ? (
						<Mix data={data} labels={labels} locale={locale} styles={styles} />
					) : (
						<span />
					)}
					{data.repositories?.length ? (
						<Where data={data} labels={labels} styles={styles} />
					) : null}
				</div>
			) : null}
		</div>
	);
}

type Styles = ReturnType<typeof githubStats>;

function Fact({
	label,
	styles,
	children,
}: {
	label: string;
	styles: Styles;
	children: ReactNode;
}) {
	return (
		<div className={styles.insight()}>
			<dt className={styles.insightLabel()}>{label}</dt>
			<dd className={styles.insightValue()}>{children}</dd>
		</div>
	);
}

/** One bar of the whole, in a fixed order and shade per kind, with every share written out. */
function Mix({
	data,
	labels,
	locale,
	styles,
}: {
	data: GithubStatsData;
	labels: GithubStatsLabels;
	locale?: string;
	styles: Styles;
}) {
	if (!data.mix) return null;
	const shares = mixShares(data.mix);
	return (
		<section className={styles.mix()}>
			<h3 className={styles.sectionTitle()}>{labels.mixTitle}</h3>
			<div className={styles.mixBar()} aria-hidden="true">
				{shares.map(({ key, share }) =>
					share > 0 ? (
						<span
							key={key}
							className={styles.mixSegment()}
							style={{ flexGrow: share, background: GITHUB_MIX_FILL[key] }}
						/>
					) : null,
				)}
			</div>
			<ul className={styles.mixLegend()}>
				{shares.map(({ key, share }) => (
					<li key={key} className={styles.mixItem()}>
						<span
							aria-hidden="true"
							className={styles.mixSwatch()}
							style={{ background: GITHUB_MIX_FILL[key] }}
						/>
						<span className={styles.mixLabel()}>{labels[key]}</span>
						<span className={styles.mixValue()}>{formatPercent(share, locale)}</span>
					</li>
				))}
			</ul>
		</section>
	);
}

function Where({
	data,
	labels,
	styles,
}: {
	data: GithubStatsData;
	labels: GithubStatsLabels;
	styles: Styles;
}) {
	const repositories = data.repositories ?? [];
	const hidden = repositories.length - REPO_LIMIT;
	return (
		<section className={styles.where()}>
			<h3 className={styles.sectionTitle()}>{labels.contributedTo}</h3>
			<ul className={styles.repoList()}>
				{repositories.slice(0, REPO_LIMIT).map((repo) => (
					<li key={repo.url} className="min-w-0">
						<a
							href={repo.url}
							target="_blank"
							rel="noopener noreferrer"
							className={styles.repo()}
						>
							<span className={styles.repoOwner()}>{repo.owner}/</span>
							<span className={styles.repoName()}>{repo.name}</span>
						</a>
					</li>
				))}
			</ul>
			{hidden > 0 ? (
				data.profileUrl ? (
					<a
						href={data.profileUrl}
						target="_blank"
						rel="noopener noreferrer"
						className={styles.more()}
					>
						{labels.more(hidden)}
					</a>
				) : (
					<p className={styles.more()}>{labels.more(hidden)}</p>
				)
			) : null}
			{data.organizations?.length ? (
				<p className={styles.orgs()}>
					{labels.alongside}
					{data.organizations.map((org) => (
						<a
							key={org.url}
							href={org.url}
							target="_blank"
							rel="noopener noreferrer"
							className={styles.org()}
						>
							<Avatar size="sm" shape="square" className={styles.orgAvatar()}>
								<AvatarImage src={org.avatarUrl} alt="" />
								<AvatarFallback>{initials(org.name)}</AvatarFallback>
							</Avatar>
							{org.name}
						</a>
					))}
				</p>
			) : null}
		</section>
	);
}

function WeeklyChart({
	days,
	labels,
	locale,
}: {
	days: GithubStatsData["contributions"][string];
	labels: GithubStatsLabels;
	locale?: string;
}) {
	const rows = weeklyContributions(days).map((week) => ({
		label: formatDay(week.date, locale),
		count: week.count,
	}));
	return (
		<ChartContainer
			config={{ count: { label: labels.contributions, color: "var(--success)" } }}
			title={`${labels.contributions}: ${labels.weeks.toLowerCase()}`}
			locale={locale}
			aspect="wide"
		>
			<BarChart data={rows} xKey="label">
				<Bar dataKey="count" />
				<BarXAxis maxLabels={8} />
				<BarYAxis tickFormatter={(value) => formatCount(value, locale)} />
				<BarTooltip
					content={
						<ChartTooltipContent
							labelFormatter={(label) => `${labels.weekOf} ${label}`}
							formatter={(value) => formatCount(Number(value), locale)}
						/>
					}
				/>
			</BarChart>
		</ChartContainer>
	);
}

function TrendArrow({ ratio }: { ratio: number | null }) {
	const d =
		ratio === null || ratio === 0
			? "M2.5 6h7"
			: ratio > 0
				? "M6 9.5v-7M3 5.5l3-3 3 3"
				: "M6 2.5v7M3 6.5l3 3 3-3";
	return (
		<svg
			viewBox="0 0 12 12"
			fill="none"
			stroke="currentColor"
			strokeWidth={1.75}
			strokeLinecap="round"
			strokeLinejoin="round"
			aria-hidden="true"
		>
			<path d={d} />
		</svg>
	);
}

// packages/ui-svelte/src/lib/github-stats/github-stats.svelte
<script lang="ts">
import Avatar from "../avatar/avatar.svelte";
import AvatarFallback from "../avatar/avatar-fallback.svelte";
import AvatarImage from "../avatar/avatar-image.svelte";
import Badge from "../badge/badge.svelte";
import { Bar, BarChart, BarTooltip, BarXAxis, BarYAxis } from "../bar-chart";
import { ChartContainer, ChartTooltipContent } from "../chart";
import Empty from "../empty/empty.svelte";
import EmptyDescription from "../empty/empty-description.svelte";
import EmptyHeader from "../empty/empty-header.svelte";
import EmptyTitle from "../empty/empty-title.svelte";
import GithubCalendar from "../github-calendar/github-calendar.svelte";
import { cn } from "../lib/cn";
import RollingDigits from "../rolling-digits/rolling-digits.svelte";
import Select from "../select/select.svelte";
import SelectContent from "../select/select-content.svelte";
import SelectItem from "../select/select-item.svelte";
import SelectTrigger from "../select/select-trigger.svelte";
import SelectValue from "../select/select-value.svelte";
import Tabs from "../tabs/tabs.svelte";
import TabsContent from "../tabs/tabs-content.svelte";
import TabsList from "../tabs/tabs-list.svelte";
import TabsTrigger from "../tabs/tabs-trigger.svelte";
import {
	contributionInsights,
	contributionYears,
	formatChange,
	formatCount,
	formatDay,
	formatPercent,
	GITHUB_COUNT_KEYS,
	GITHUB_STATS_LABELS,
	type GithubStatsData,
	type GithubStatsLabels,
	type GithubStatsView,
	initials,
	mixShares,
	sameDaysChange,
	weeklyContributions,
	yearTotal,
} from "./core";
import {
	GITHUB_MIX_FILL,
	GITHUB_STATS_LAYOUT,
	type GithubStatsVariant,
	githubStats,
} from "./variants";

let {
	data,
	variant = "default",
	year = $bindable(),
	onYearChange,
	view = $bindable("days"),
	onViewChange,
	locale,
	labels: labelsProp,
	class: classProp,
}: {
	data: GithubStatsData;
	variant?: GithubStatsVariant;
	/** Bindable year (`"2026"`); the newest with data when unset. */
	year?: string;
	onYearChange?: (year: string) => void;
	view?: GithubStatsView;
	onViewChange?: (view: GithubStatsView) => void;
	locale?: string;
	labels?: Partial<GithubStatsLabels>;
	class?: string;
} = $props();

const REPO_LIMIT = 5;

const labels = $derived({ ...GITHUB_STATS_LABELS, ...labelsProp });
const styles = $derived(githubStats({ variant }));
const layout = $derived(GITHUB_STATS_LAYOUT[variant]);
const years = $derived(contributionYears(data.contributions));
const activeYear = $derived(year ?? years[0] ?? "");
const days = $derived(data.contributions[activeYear] ?? []);
const total = $derived(yearTotal(days));
const facts = $derived(contributionInsights(days));
const change = $derived(sameDaysChange(data.contributions, activeYear));
const yearItems = $derived(years.map((y) => ({ value: y, label: y })));
const repositories = $derived(data.repositories ?? []);
const hiddenRepos = $derived(repositories.length - REPO_LIMIT);
const shares = $derived(data.mix ? mixShares(data.mix) : []);
const weekRows = $derived(
	weeklyContributions(days).map((week) => ({
		label: formatDay(week.date, locale),
		count: week.count,
	})),
);
const trendVariant = $derived(
	!change || change.ratio === null || change.ratio === 0
		? "secondary"
		: change.ratio > 0
			? "success"
			: "destructive",
);
const trendPath = $derived(
	trendVariant === "success"
		? "M6 9.5v-7M3 5.5l3-3 3 3"
		: trendVariant === "destructive"
			? "M6 2.5v7M3 6.5l3 3 3-3"
			: "M2.5 6h7",
);

function setYear(next: string) {
	year = next;
	onYearChange?.(next);
}

function setView(next: string) {
	if (next !== "days" && next !== "weeks") return;
	view = next;
	onViewChange?.(next);
}

const countFormat = (value: number) => formatCount(Math.round(value), locale);
</script>

<!-- A year on GitHub: the total and its trend, the facts behind it, the calendar, and where it went. -->
<div data-slot="github-stats" data-variant={variant} class={cn(styles.root(), classProp)}>
	{#if years.length === 0}
		<Empty variant="outline" size="sm" role="status">
			<EmptyHeader>
				<EmptyTitle>{labels.emptyTitle}</EmptyTitle>
				<EmptyDescription>{labels.emptyDescription}</EmptyDescription>
			</EmptyHeader>
		</Empty>
	{:else}
		<Tabs bind:value={() => view, setView} variant="segment" size="sm">
			<header class={styles.head()}>
				<div class="min-w-0">
					<p class={styles.eyebrow()}>{labels.eyebrow}</p>
					<p class={styles.hero()}>
						{#if layout.animate}
							<RollingDigits variant="count" value={total} format={countFormat} durationMs={900} size="md" class={cn("font-bold text-foreground", styles.heroValue())} />
						{:else}
							<span class={styles.heroValue()}>{formatCount(total, locale)}</span>
						{/if}
						<span class={styles.heroUnit()}>{labels.totalIn(activeYear)}</span>
					</p>
					{#if change}
						<p class={styles.trendRow()}>
							<Badge size="sm" variant={trendVariant} class={styles.trend()}>
								<svg
									viewBox="0 0 12 12"
									fill="none"
									stroke="currentColor"
									stroke-width="1.75"
									stroke-linecap="round"
									stroke-linejoin="round"
									aria-hidden="true"
								>
									<path d={trendPath} />
								</svg>
								{change.ratio === null ? labels.newLabel : formatChange(change.ratio, locale)}
							</Badge>
							<span class={styles.compare()}>{labels.compare(change.previousYear)}</span>
						</p>
					{/if}
				</div>
				<div class={styles.controls()}>
					<TabsList aria-label={labels.view}>
						<TabsTrigger value="days">{labels.days}</TabsTrigger>
						<TabsTrigger value="weeks">{labels.weeks}</TabsTrigger>
					</TabsList>
					{#if years.length > 1}
						<Select bind:value={() => activeYear, setYear} items={yearItems}>
							<SelectTrigger aria-label={labels.year} class={styles.yearTrigger()}>
								<SelectValue />
							</SelectTrigger>
							<SelectContent>
								{#each years as y (y)}
									<SelectItem value={y} label={y} class="font-mono text-xs">{y}</SelectItem>
								{/each}
							</SelectContent>
						</Select>
					{/if}
				</div>
			</header>

			<dl class={styles.insights()}>
				<div class={styles.insight()}>
					<dt class={styles.insightLabel()}>{labels.longestStreak}</dt>
					<dd class={styles.insightValue()}>{labels.dayCount(facts.longestStreak)}</dd>
				</div>
				<div class={styles.insight()}>
					<dt class={styles.insightLabel()}>{labels.currentStreak}</dt>
					<dd class={styles.insightValue()}>{labels.dayCount(facts.currentStreak)}</dd>
				</div>
				<div class={styles.insight()}>
					<dt class={styles.insightLabel()}>{labels.bestDay}</dt>
					<dd class={styles.insightValue()}>
						{#if facts.best}
							{formatCount(facts.best.count, locale)}
							<span class={styles.insightNote()}>{formatDay(facts.best.date, locale)}</span>
						{:else}
							–
						{/if}
					</dd>
				</div>
				<div class={styles.insight()}>
					<dt class={styles.insightLabel()}>{labels.activeDays}</dt>
					<dd class={styles.insightValue()}>
						{formatCount(facts.activeDays, locale)}
						<span class={styles.insightNote()}>/ {days.length}</span>
					</dd>
				</div>
			</dl>

			<div class={styles.calendar()}>
				<TabsContent value="days" class={styles.panel()}>
					{#key activeYear}
						<GithubCalendar
							{days}
							size={layout.calendar}
							tone="success"
							showTotal={false}
							{locale}
						/>
					{/key}
				</TabsContent>
				<TabsContent value="weeks" class={styles.panel()}>
					{#if view === "weeks"}
					<ChartContainer
						config={{ count: { label: labels.contributions, color: "var(--success)" } }}
						title="{labels.contributions}: {labels.weeks.toLowerCase()}"
						{locale}
						aspect="wide"
					>
						<BarChart data={weekRows} xKey="label">
							<Bar dataKey="count" />
							<BarXAxis maxLabels={8} />
							<BarYAxis tickFormatter={(value) => formatCount(value, locale)} />
							<BarTooltip>
								{#snippet content()}
									<ChartTooltipContent>
										{#snippet formatter({ value })}
											{formatCount(value, locale)}
										{/snippet}
										{#snippet labelFormatter({ label })}
											{labels.weekOf} {label}
										{/snippet}
									</ChartTooltipContent>
								{/snippet}
							</BarTooltip>
						</BarChart>
					</ChartContainer>
					{/if}
				</TabsContent>
			</div>
		</Tabs>

		<dl class={styles.counts()}>
			{#each GITHUB_COUNT_KEYS as key (key)}
				<div class={styles.count()}>
					<dt class={styles.countLabel()}>{labels[key]}</dt>
					<dd class="order-first">
						{#if layout.animate}
							<RollingDigits
								variant="count"
								value={data.counts[key]}
								format={countFormat}
								durationMs={1200}
								size="md"
								class={cn("font-bold text-foreground", styles.countValue())}
							/>
						{:else}
							<span class={styles.countValue()}>{formatCount(data.counts[key], locale)}</span>
						{/if}
					</dd>
				</div>
			{/each}
		</dl>

		{#if layout.footer && (data.mix || repositories.length)}
			<div class={styles.footer()}>
				{#if data.mix}
					<!-- One bar of the whole, in a fixed order and shade per kind, with every share written out. -->
					<section class={styles.mix()}>
						<h3 class={styles.sectionTitle()}>{labels.mixTitle}</h3>
						<div class={styles.mixBar()} aria-hidden="true">
							{#each shares as { key, share } (key)}
								{#if share > 0}
									<span
										class={styles.mixSegment()}
										style:flex-grow={share}
										style:background={GITHUB_MIX_FILL[key]}
									></span>
								{/if}
							{/each}
						</div>
						<ul class={styles.mixLegend()}>
							{#each shares as { key, share } (key)}
								<li class={styles.mixItem()}>
									<span
										aria-hidden="true"
										class={styles.mixSwatch()}
										style:background={GITHUB_MIX_FILL[key]}
									></span>
									<span class={styles.mixLabel()}>{labels[key]}</span>
									<span class={styles.mixValue()}>{formatPercent(share, locale)}</span>
								</li>
							{/each}
						</ul>
					</section>
				{:else}
					<span></span>
				{/if}
				{#if repositories.length}
					<section class={styles.where()}>
						<h3 class={styles.sectionTitle()}>{labels.contributedTo}</h3>
						<ul class={styles.repoList()}>
							{#each repositories.slice(0, REPO_LIMIT) as repo (repo.url)}
								<li class="min-w-0">
									<a href={repo.url} target="_blank" rel="noopener noreferrer" class={styles.repo()}>
										<span class={styles.repoOwner()}>{repo.owner}/</span>
										<span class={styles.repoName()}>{repo.name}</span>
									</a>
								</li>
							{/each}
						</ul>
						{#if hiddenRepos > 0}
							{#if data.profileUrl}
								<a href={data.profileUrl} target="_blank" rel="noopener noreferrer" class={styles.more()}>
									{labels.more(hiddenRepos)}
								</a>
							{:else}
								<p class={styles.more()}>{labels.more(hiddenRepos)}</p>
							{/if}
						{/if}
						{#if data.organizations?.length}
							<p class={styles.orgs()}>
								{labels.alongside}
								{#each data.organizations as org (org.url)}
									<a href={org.url} target="_blank" rel="noopener noreferrer" class={styles.org()}>
										<Avatar size="sm" shape="square" class={styles.orgAvatar()}>
											<AvatarImage src={org.avatarUrl} alt="" />
											<AvatarFallback>{initials(org.name)}</AvatarFallback>
										</Avatar>
										{org.name}
									</a>
								{/each}
							</p>
						{/if}
					</section>
				{/if}
			</div>
		{/if}
	{/if}
</div>
