// packages/ui-svelte/src/lib/swap-text/swap-text.svelte
<script lang="ts">
import { cn } from "../lib/cn";
import {
	flipTiming,
	type SwapTextMotion,
	type SwapTextSize,
	swapChars,
	swapText,
	swapTextFlip,
} from "./variants";

let {
	initialText,
	finalText,
	active: activeProp,
	defaultActive = false,
	onActiveChange,
	supportsHover = true,
	disableClick = false,
	durationMs = 1000,
	staggerMs = 44,
	size = "lg",
	motion = "slide",
	class: classProp,
}: {
	initialText: string;
	finalText: string;
	active?: boolean;
	defaultActive?: boolean;
	onActiveChange?: (active: boolean) => void;
	supportsHover?: boolean;
	disableClick?: boolean;
	/** How long the swap takes, in ms (per letter for `flip`). */
	durationMs?: number;
	/** Delay between neighbouring letters for `flip`, in ms. */
	staggerMs?: number;
	size?: SwapTextSize;
	motion?: SwapTextMotion;
	class?: string;
} = $props();

// svelte-ignore state_referenced_locally -- intentional one-time seed, matching React's useState(initialValue)
let internalActive = $state(defaultActive);
const active = $derived(activeProp ?? internalActive);
const longer = $derived(finalText.length > initialText.length ? finalText : null);

function setActive(next: boolean) {
	if (activeProp === undefined) internalActive = next;
	onActiveChange?.(next);
}

const LAYER = "block transition-transform ease-[var(--ease-out)]";
const flip = (layer: "first" | "second") =>
	swapTextFlip({ layer, active, hover: supportsHover });
</script>

{#snippet letters(text: string, layer: "first" | "second")}
	{@const chars = swapChars(text)}
	<span aria-hidden="true" class={flip(layer).layer()}>
		{#each chars as c, i (i)}
			<span class={flip(layer).char()} style="--i: {i}; --n: {chars.length}">{c}</span>
		{/each}
	</span>
{/snippet}

{#if motion === "flip"}
	<div data-slot="swap-text" class={cn("relative text-foreground", classProp)}>
		<button
			type="button"
			disabled={disableClick}
			aria-label={active ? finalText : initialText}
			aria-pressed={active}
			onclick={() => !disableClick && setActive(!active)}
			class={cn(swapText({ size, motion }), "group/swap")}
		>
			<span
				class={flip("first").stage()}
				style="--swap-duration: {flipTiming(durationMs).letter}ms; --swap-stagger: {staggerMs}ms; --swap-lag: {flipTiming(durationMs).lag}ms"
			>
				{@render letters(initialText, "first")}
				{@render letters(finalText, "second")}
			</span>
		</button>
	</div>
{:else}

<div data-slot="swap-text" class={cn("relative overflow-hidden text-foreground", classProp)}>
	<button
		type="button"
		disabled={disableClick}
		onclick={() => !disableClick && setActive(!active)}
		class={cn(swapText({ size }), "group/swap")}
	>
		<span
			class={cn(LAYER, "flex flex-col", {
				"-translate-y-full": active,
				"group-hover/swap:-translate-y-full": supportsHover,
			})}
			style="transition-duration: {durationMs}ms;"
		>
			{initialText}
			{#if longer}<span class="invisible h-0">{longer}</span>{/if}
		</span>
		<span
			class={cn(LAYER, "absolute top-full", {
				"-translate-y-full": active,
				"group-hover/swap:-translate-y-full": supportsHover,
			})}
			style="transition-duration: {durationMs}ms;"
		>
			{finalText}
		</span>
	</button>
</div>
{/if}

// packages/ui-react/src/swap-text/swap-text.tsx
"use client";

import { type CSSProperties, useState } from "react";
import { cn } from "../lib/cn";
import {
	flipTiming,
	type SwapTextMotion,
	type SwapTextSize,
	swapChars,
	swapText,
	swapTextFlip,
} from "./variants";

export type { SwapTextMotion, SwapTextSize };

export interface SwapTextProps {
	initialText: string;
	finalText: string;
	/** Controlled: which text is showing. Omit to let the component own it. */
	active?: boolean;
	defaultActive?: boolean;
	onActiveChange?: (active: boolean) => void;
	/** Toggle on hover as well as click. */
	supportsHover?: boolean;
	disableClick?: boolean;
	/** How long the swap takes, in ms (per letter for `flip`). */
	durationMs?: number;
	/** Delay between neighbouring letters for `flip`, in ms. */
	staggerMs?: number;
	size?: SwapTextSize;
	motion?: SwapTextMotion;
	className?: string;
}

const LAYER = "block transition-transform ease-[var(--ease-out)]";

export function SwapText({
	initialText,
	finalText,
	active: activeProp,
	defaultActive = false,
	onActiveChange,
	supportsHover = true,
	disableClick = false,
	durationMs = 1000,
	staggerMs = 44,
	size = "lg",
	motion = "slide",
	className,
}: SwapTextProps) {
	const [internalActive, setInternalActive] = useState(defaultActive);
	const active = activeProp ?? internalActive;

	function setActive(next: boolean) {
		if (activeProp === undefined) setInternalActive(next);
		onActiveChange?.(next);
	}

	const longer = finalText.length > initialText.length ? finalText : null;

	if (motion === "flip") {
		const flip = (layer: "first" | "second") =>
			swapTextFlip({ layer, active, hover: supportsHover });
		const letters = (text: string, layer: "first" | "second") => {
			const chars = swapChars(text);
			return (
				<span aria-hidden className={flip(layer).layer()}>
					{chars.map((c, i) => (
						<span
							key={i}
							className={flip(layer).char()}
							style={{ "--i": i, "--n": chars.length } as CSSProperties}
						>
							{c}
						</span>
					))}
				</span>
			);
		};
		return (
			<div data-slot="swap-text" className={cn("relative text-foreground", className)}>
				<button
					type="button"
					disabled={disableClick}
					aria-label={active ? finalText : initialText}
					aria-pressed={active}
					onClick={() => !disableClick && setActive(!active)}
					className={cn(swapText({ size, motion }), "group/swap")}
				>
					<span
						className={flip("first").stage()}
						style={
							{
								"--swap-duration": `${flipTiming(durationMs).letter}ms`,
								"--swap-stagger": `${staggerMs}ms`,
								"--swap-lag": `${flipTiming(durationMs).lag}ms`,
							} as CSSProperties
						}
					>
						{letters(initialText, "first")}
						{letters(finalText, "second")}
					</span>
				</button>
			</div>
		);
	}

	return (
		<div
			data-slot="swap-text"
			className={cn("relative overflow-hidden text-foreground", className)}
		>
			<button
				type="button"
				disabled={disableClick}
				onClick={() => !disableClick && setActive(!active)}
				className={cn(swapText({ size }), "group/swap")}
			>
				<span
					className={cn(LAYER, "flex flex-col", {
						"-translate-y-full": active,
						"group-hover/swap:-translate-y-full": supportsHover,
					})}
					style={{ transitionDuration: `${durationMs}ms` }}
				>
					{initialText}
					{longer ? <span className="invisible h-0">{longer}</span> : null}
				</span>
				<span
					className={cn(LAYER, "absolute top-full", {
						"-translate-y-full": active,
						"group-hover/swap:-translate-y-full": supportsHover,
					})}
					style={{ transitionDuration: `${durationMs}ms` }}
				>
					{finalText}
				</span>
			</button>
		</div>
	);
}
