// packages/ui-react/src/overview-card/overview-card.tsx
"use client";

import { type ReactNode, useMemo, useState } from "react";
import { Area, AreaChart } from "../area-chart/area-chart";
import { Badge } from "../badge/badge";
import {
	Card,
	CardAction,
	CardContent,
	CardDescription,
	CardHeader,
	CardTitle,
} from "../card/card";
import { ChartContainer } from "../chart/chart";
import { type ChartStatus, type Datum, toDate } from "../chart/core";
import { Counter } from "../counter/counter";
import { cn } from "../lib/cn";
import { Line, LineChart } from "../line-chart/line-chart";
import { ToggleGroup, ToggleGroupItem } from "../toggle-group/toggle-group";
import { type OverviewCardChart, type OverviewCardSize, overviewCard } from "./variants";

export type { OverviewCardChart, OverviewCardSize };

export interface OverviewCardPeriod {
	value: string;
	label: string;
}

export interface OverviewCardProps {
	title: string;
	description?: string;
	data: Datum[];
	dataKey: string;
	xKey?: string;
	/** Headline at rest, e.g. the period total. */
	value: number;
	/** Caption under the headline at rest, e.g. "This month". */
	label: string;
	/** Change over the whole period, in percent. */
	trend: number;
	chart?: OverviewCardChart;
	size?: OverviewCardSize;
	/** Series colour; defaults to the first chart slot. */
	color?: string;
	/** Period switcher options; omit to hide the toggle entirely. */
	periods?: OverviewCardPeriod[];
	period?: string;
	onPeriodChange?: (period: string) => void;
	locale?: string;
	formatValue?: (value: number) => string;
	/** Caption for a hovered point. Defaults to the point's short date. */
	formatLabel?: (date: Date) => string;
	status?: ChartStatus;
	activeIndex?: number | null;
	onActiveIndexChange?: (index: number | null) => void;
	className?: string;
	children?: ReactNode;
}

/** A bigger sibling of StatCard: a period switcher up top, the chart is the main event. */
export function OverviewCard({
	title,
	description,
	data,
	dataKey,
	xKey = "date",
	value,
	label,
	trend,
	chart = "area",
	size = "md",
	color = "var(--chart-1)",
	periods,
	period,
	onPeriodChange,
	locale,
	formatValue,
	formatLabel,
	status = "ready",
	activeIndex: activeIndexProp,
	onActiveIndexChange,
	className,
	children,
}: OverviewCardProps) {
	const [internal, setInternal] = useState<number | null>(null);
	const activeIndex = activeIndexProp !== undefined ? activeIndexProp : internal;
	const setActive = (index: number | null) => {
		if (activeIndexProp === undefined) setInternal(index);
		onActiveIndexChange?.(index);
	};
	const number = useMemo(
		() =>
			formatValue ?? new Intl.NumberFormat(locale, { maximumFractionDigits: 0 }).format,
		[formatValue, locale],
	);
	const day = useMemo(
		() => new Intl.DateTimeFormat(locale, { month: "short", day: "numeric" }),
		[locale],
	);
	const percent = useMemo(
		() =>
			new Intl.NumberFormat(locale, {
				style: "percent",
				maximumFractionDigits: 1,
				signDisplay: "exceptZero",
			}),
		[locale],
	);

	const datum = activeIndex !== null ? data[activeIndex] : undefined;
	const hovered = datum?.[dataKey];
	const shownValue = typeof hovered === "number" ? hovered : value;
	const shownLabel = datum
		? (formatLabel ?? ((d: Date) => day.format(d)))(toDate(datum[xKey]))
		: label;
	const up = trend >= 0;
	const styles = overviewCard({ size, chart });
	const config = { [dataKey]: { label: title, color } };
	const margin = { top: 8, right: 0, bottom: 0, left: 0 };

	return (
		<Card data-slot="overview-card" className={cn(styles.root(), className)}>
			<CardHeader className={styles.header()}>
				<div>
					<CardTitle className={styles.title()}>{title}</CardTitle>
					{description ? (
						<CardDescription className={styles.description()}>
							{description}
						</CardDescription>
					) : null}
				</div>
				{periods && periods.length > 0 ? (
					<CardAction>
						<ToggleGroup
							type="single"
							size="sm"
							value={period ?? ""}
							onValueChange={(next) => onPeriodChange?.(next as string)}
							label={`${title} period`}
						>
							{periods.map((p) => (
								<ToggleGroupItem key={p.value} value={p.value}>
									{p.label}
								</ToggleGroupItem>
							))}
						</ToggleGroup>
					</CardAction>
				) : null}
			</CardHeader>
			<CardContent className={styles.body()}>
				<div className={styles.headline()}>
					<Counter
						value={shownValue}
						format={number}
						size="lg"
						durationMs={400}
						triggerOnView={false}
					/>
					<span className={styles.label()}>{shownLabel}</span>
					<Badge variant={up ? "success" : "destructive"} size="sm">
						<svg aria-hidden="true" viewBox="0 0 12 12" className="size-3" fill="none">
							<path
								d={up ? "M3 9 9 3M4.5 3H9v4.5" : "M3 3l6 6M9 4.5V9H4.5"}
								stroke="currentColor"
								strokeWidth={1.5}
								strokeLinecap="round"
								strokeLinejoin="round"
							/>
						</svg>
						{percent.format(trend / 100)}
					</Badge>
				</div>
				<div className={styles.chart()}>
					<ChartContainer config={config} title={title} aspect="auto" locale={locale}>
						{chart === "line" ? (
							<LineChart
								data={data}
								xKey={xKey}
								margin={margin}
								status={status}
								activeIndex={activeIndex}
								onActiveIndexChange={setActive}
							>
								<Line dataKey={dataKey} curve="monotone" strokeWidth={2} />
								{children}
							</LineChart>
						) : (
							<AreaChart
								data={data}
								xKey={xKey}
								margin={margin}
								status={status}
								activeIndex={activeIndex}
								onActiveIndexChange={setActive}
							>
								<Area dataKey={dataKey} curve="monotone" fillOpacity={0.35} />
								{children}
							</AreaChart>
						)}
					</ChartContainer>
				</div>
			</CardContent>
		</Card>
	);
}

// packages/ui-svelte/src/lib/overview-card/overview-card.svelte
<script lang="ts">
import type { Snippet } from "svelte";
import Area from "../area-chart/area.svelte";
import AreaChart from "../area-chart/area-chart.svelte";
import Badge from "../badge/badge.svelte";
import Card from "../card/card.svelte";
import CardAction from "../card/card-action.svelte";
import CardContent from "../card/card-content.svelte";
import CardDescription from "../card/card-description.svelte";
import CardHeader from "../card/card-header.svelte";
import CardTitle from "../card/card-title.svelte";
import ChartContainer from "../chart/chart-container.svelte";
import { type ChartStatus, type Datum, toDate } from "../chart/core";
import Counter from "../counter/counter.svelte";
import { cn } from "../lib/cn";
import Line from "../line-chart/line.svelte";
import LineChart from "../line-chart/line-chart.svelte";
import ToggleGroup from "../toggle-group/toggle-group.svelte";
import ToggleGroupItem from "../toggle-group/toggle-group-item.svelte";
import { type OverviewCardChart, type OverviewCardSize, overviewCard } from "./variants";

let {
	title,
	description,
	data,
	dataKey,
	xKey = "date",
	value,
	label,
	trend,
	chart = "area",
	size = "md",
	color = "var(--chart-1)",
	periods,
	period = $bindable(periods?.[0]?.value),
	onPeriodChange,
	locale,
	formatValue,
	formatLabel,
	status = "ready",
	activeIndex = $bindable(null),
	onActiveIndexChange,
	class: className,
	children,
}: {
	title: string;
	description?: string;
	data: Datum[];
	dataKey: string;
	xKey?: string;
	/** Headline at rest, e.g. the period total. */
	value: number;
	/** Caption under the headline at rest, e.g. "This month". */
	label: string;
	/** Change over the whole period, in percent. */
	trend: number;
	chart?: OverviewCardChart;
	size?: OverviewCardSize;
	/** Series colour; defaults to the first chart slot. */
	color?: string;
	/** Period switcher options; omit to hide the toggle entirely. */
	periods?: { value: string; label: string }[];
	period?: string;
	onPeriodChange?: (period: string) => void;
	locale?: string;
	formatValue?: (value: number) => string;
	/** Caption for a hovered point. Defaults to the point's short date. */
	formatLabel?: (date: Date) => string;
	status?: ChartStatus;
	activeIndex?: number | null;
	onActiveIndexChange?: (index: number | null) => void;
	class?: string;
	children?: Snippet;
} = $props();

const number = $derived(
	formatValue ?? new Intl.NumberFormat(locale, { maximumFractionDigits: 0 }).format,
);
const day = $derived(new Intl.DateTimeFormat(locale, { month: "short", day: "numeric" }));
const percent = $derived(
	new Intl.NumberFormat(locale, {
		style: "percent",
		maximumFractionDigits: 1,
		signDisplay: "exceptZero",
	}),
);
const datum = $derived(activeIndex !== null ? data[activeIndex] : undefined);
const shownValue = $derived.by(() => {
	const hovered = datum?.[dataKey];
	return typeof hovered === "number" ? hovered : value;
});
const shownLabel = $derived(
	datum ? (formatLabel ?? ((d: Date) => day.format(d)))(toDate(datum[xKey])) : label,
);
const up = $derived(trend >= 0);
const styles = $derived(overviewCard({ size, chart }));
const config = $derived({ [dataKey]: { label: title, color } });
const margin = { top: 8, right: 0, bottom: 0, left: 0 };

function setActive(index: number | null) {
	activeIndex = index;
	onActiveIndexChange?.(index);
}

function setPeriod(next: string) {
	period = next;
	onPeriodChange?.(next);
}
</script>

<Card data-slot="overview-card" class={cn(styles.root(), className)}>
	<CardHeader class={styles.header()}>
		<div>
			<CardTitle class={styles.title()}>{title}</CardTitle>
			{#if description}
				<CardDescription class={styles.description()}>{description}</CardDescription>
			{/if}
		</div>
		{#if periods && periods.length > 0}
			<CardAction>
				<ToggleGroup
					type="single"
					size="sm"
					bind:value={() => period ?? "", (v) => setPeriod(v as string)}
					label="{title} period"
				>
					{#each periods as p (p.value)}
						<ToggleGroupItem value={p.value}>{p.label}</ToggleGroupItem>
					{/each}
				</ToggleGroup>
			</CardAction>
		{/if}
	</CardHeader>
	<CardContent class={styles.body()}>
		<div class={styles.headline()}>
			<Counter value={shownValue} format={number} size="lg" durationMs={400} triggerOnView={false} />
			<span class={styles.label()}>{shownLabel}</span>
			<Badge variant={up ? "success" : "destructive"} size="sm">
				<svg aria-hidden="true" viewBox="0 0 12 12" class="size-3" fill="none">
					<path
						d={up ? "M3 9 9 3M4.5 3H9v4.5" : "M3 3l6 6M9 4.5V9H4.5"}
						stroke="currentColor"
						stroke-width={1.5}
						stroke-linecap="round"
						stroke-linejoin="round"
					/>
				</svg>
				{percent.format(trend / 100)}
			</Badge>
		</div>
		<div class={styles.chart()}>
			<ChartContainer {config} {title} aspect="auto" {locale}>
				{#if chart === "line"}
					<LineChart {data} {xKey} {margin} {status} bind:activeIndex={() => activeIndex, setActive}>
						<Line {dataKey} curve="monotone" strokeWidth={2} />
						{@render children?.()}
					</LineChart>
				{:else}
					<AreaChart {data} {xKey} {margin} {status} bind:activeIndex={() => activeIndex, setActive}>
						<Area {dataKey} curve="monotone" fillOpacity={0.35} />
						{@render children?.()}
					</AreaChart>
				{/if}
			</ChartContainer>
		</div>
	</CardContent>
</Card>
