// packages/ui-react/src/music-player/music-player.tsx
"use client";

import { type ReactNode, useEffect, useRef, useState } from "react";
import { Button } from "../button/button";
import { cn } from "../lib/cn";
import { Slider } from "../slider/slider";
import {
	clampUnit,
	formatTime,
	MUSIC_PLAYER_LABELS,
	type MusicPlayerLabels,
	SEEK_TOLERANCE,
} from "./types";
import { type MusicPlayerLayout, musicPlayer } from "./variants";

export type { MusicPlayerLabels, MusicPlayerLayout };

export interface MusicPlayerProps {
	title: string;
	artist: string;
	/** Cover art URL, shown as the record face. */
	cover: string;
	coverAlt?: string;
	/** Track length in seconds. */
	duration: number;
	/** Audio URL; when set the player drives a real `<audio>` element, otherwise it only renders. */
	src?: string;
	playing?: boolean;
	defaultPlaying?: boolean;
	onPlayingChange?: (playing: boolean) => void;
	/** Playhead in seconds. */
	position?: number;
	defaultPosition?: number;
	onPositionChange?: (position: number) => void;
	/** 0 to 1. */
	volume?: number;
	defaultVolume?: number;
	onVolumeChange?: (volume: number) => void;
	/** Shows a previous-track button when set. */
	onPrevious?: () => void;
	/** Shows a next-track button when set. */
	onNext?: () => void;
	layout?: MusicPlayerLayout;
	labels?: Partial<MusicPlayerLabels>;
	className?: string;
}

function useControlled<T>(
	prop: T | undefined,
	initial: T,
	onChange?: (value: T) => void,
) {
	const [inner, setInner] = useState(initial);
	const value = prop ?? inner;
	const set = (next: T) => {
		if (prop === undefined) setInner(next);
		onChange?.(next);
	};
	return [value, set] as const;
}

function Icon({ filled = false, children }: { filled?: boolean; children: ReactNode }) {
	return (
		<svg
			viewBox="0 0 24 24"
			fill={filled ? "currentColor" : "none"}
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
			aria-hidden
		>
			{children}
		</svg>
	);
}

/** A record-deck player whose playing state, playhead and volume are all caller-controllable. */
export function MusicPlayer({
	title,
	artist,
	cover,
	coverAlt = "",
	duration,
	src,
	playing: playingProp,
	defaultPlaying = false,
	onPlayingChange,
	position: positionProp,
	defaultPosition = 0,
	onPositionChange,
	volume: volumeProp,
	defaultVolume = 1,
	onVolumeChange,
	onPrevious,
	onNext,
	layout = "vinyl",
	labels,
	className,
}: MusicPlayerProps) {
	const text = { ...MUSIC_PLAYER_LABELS, ...labels };
	const s = musicPlayer({ layout });
	const [playing, setPlaying] = useControlled(
		playingProp,
		defaultPlaying,
		onPlayingChange,
	);
	const [position, setPosition] = useControlled(
		positionProp,
		defaultPosition,
		onPositionChange,
	);
	const [volume, setVolume] = useControlled(volumeProp, defaultVolume, onVolumeChange);
	const lastVolume = useRef(volume > 0 ? volume : 1);
	const audio = useRef<HTMLAudioElement>(null);
	const setPlayingRef = useRef(setPlaying);
	setPlayingRef.current = setPlaying;

	const level = clampUnit(volume);
	const length = Math.max(0, duration);
	const at = Math.min(length, Math.max(0, position));

	useEffect(() => {
		const el = audio.current;
		if (!el) return;
		if (playing) el.play().catch(() => setPlayingRef.current(false));
		else el.pause();
	}, [playing, src]);

	useEffect(() => {
		if (audio.current) audio.current.volume = level;
	}, [level, src]);

	useEffect(() => {
		const el = audio.current;
		if (el && Math.abs(el.currentTime - at) > SEEK_TOLERANCE) el.currentTime = at;
	}, [at, src]);

	const toggleMute = () => {
		if (level > 0) {
			lastVolume.current = level;
			setVolume(0);
		} else setVolume(lastVolume.current);
	};

	return (
		<div
			data-slot="music-player"
			data-layout={layout}
			data-playing={playing}
			className={cn(s.root(), className)}
		>
			{src ? (
				// biome-ignore lint/a11y/useMediaCaption: a music track has no caption file to point at.
				<audio
					ref={audio}
					src={src}
					preload="metadata"
					className="hidden"
					onTimeUpdate={(e) => setPosition(e.currentTarget.currentTime)}
					onEnded={() => setPlaying(false)}
				/>
			) : null}
			<div className={s.frame()}>
				<div className={s.deck()}>
					<div className={s.disc()} data-playing={playing}>
						<img src={cover} alt={coverAlt} className={s.cover()} draggable={false} />
						<div aria-hidden className={s.grooves()} />
						<div aria-hidden className={s.label()}>
							<div className={s.pin()} />
						</div>
					</div>
					<div aria-hidden className={s.sheen()} />
					<div aria-hidden className={s.arm()} data-playing={playing}>
						<div className={s.armBase()} />
						<div className={s.armStick()}>
							<div className={s.needle()} />
						</div>
					</div>
				</div>
				<div className={s.body()}>
					<div className={s.meta()}>
						<span className={s.title()}>{title}</span>
						<span className={s.artist()}>{artist}</span>
					</div>
					<div className={s.scrub()}>
						<Slider
							size="sm"
							label={text.seek}
							min={0}
							max={length}
							step={1}
							value={at}
							onValueChange={(v) => setPosition(v as number)}
						/>
						<div className={s.times()} aria-hidden>
							<span>{formatTime(at)}</span>
							<span>-{formatTime(length - at)}</span>
						</div>
					</div>
					<div className={s.controls()}>
						<div className={s.transport()}>
							{onPrevious ? (
								<Button
									variant="ghost"
									size="icon"
									aria-label={text.previous}
									onClick={onPrevious}
								>
									<Icon>
										<path d="M20 5v14l-12 -7z" />
										<path d="M4 5l0 14" />
									</Icon>
								</Button>
							) : null}
							<Button
								size="icon-lg"
								className="rounded-full"
								aria-label={playing ? text.pause : text.play}
								onClick={() => setPlaying(!playing)}
							>
								{playing ? (
									<Icon filled>
										<path d="M6 6a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v12a1 1 0 0 1 -1 1h-2a1 1 0 0 1 -1 -1z" />
										<path d="M14 6a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v12a1 1 0 0 1 -1 1h-2a1 1 0 0 1 -1 -1z" />
									</Icon>
								) : (
									<Icon filled>
										<path d="M7 4v16l13 -8z" />
									</Icon>
								)}
							</Button>
							{onNext ? (
								<Button
									variant="ghost"
									size="icon"
									aria-label={text.next}
									onClick={onNext}
								>
									<Icon>
										<path d="M4 5v14l12 -7z" />
										<path d="M20 5l0 14" />
									</Icon>
								</Button>
							) : null}
						</div>
						<div className={s.volume()}>
							<Button
								variant="ghost"
								size="icon-sm"
								aria-label={level > 0 ? text.mute : text.unmute}
								onClick={toggleMute}
							>
								<Icon>
									<path d="M6 15h-2a1 1 0 0 1 -1 -1v-4a1 1 0 0 1 1 -1h2l3.5 -4.5a.8 .8 0 0 1 1.5 .5v14a.8 .8 0 0 1 -1.5 .5l-3.5 -4.5" />
									{level > 0 ? (
										<>
											<path d="M15 8a5 5 0 0 1 0 8" />
											<path d="M17.7 5a9 9 0 0 1 0 14" />
										</>
									) : (
										<path d="M16 10l4 4m0 -4l-4 4" />
									)}
								</Icon>
							</Button>
							<Slider
								size="sm"
								label={text.volume}
								min={0}
								max={100}
								step={1}
								value={Math.round(level * 100)}
								onValueChange={(v) => setVolume((v as number) / 100)}
							/>
						</div>
					</div>
				</div>
			</div>
		</div>
	);
}

// packages/ui-svelte/src/lib/music-player/music-player.svelte
<script lang="ts">
import Button from "../button/button.svelte";
import { cn } from "../lib/cn";
import Slider from "../slider/slider.svelte";
import {
	clampUnit,
	formatTime,
	MUSIC_PLAYER_LABELS,
	type MusicPlayerLabels,
	SEEK_TOLERANCE,
} from "./types";
import { type MusicPlayerLayout, musicPlayer } from "./variants";

let {
	title,
	artist,
	cover,
	coverAlt = "",
	duration,
	src,
	playing = $bindable(false),
	onPlayingChange,
	position = $bindable(0),
	onPositionChange,
	volume = $bindable(1),
	onVolumeChange,
	onPrevious,
	onNext,
	layout = "vinyl",
	labels,
	class: classProp,
}: {
	title: string;
	artist: string;
	/** Cover art URL, shown as the record face. */
	cover: string;
	coverAlt?: string;
	/** Track length in seconds. */
	duration: number;
	/** Audio URL; when set the player drives a real `<audio>` element, otherwise it only renders. */
	src?: string;
	playing?: boolean;
	onPlayingChange?: (playing: boolean) => void;
	/** Playhead in seconds. */
	position?: number;
	onPositionChange?: (position: number) => void;
	/** 0 to 1. */
	volume?: number;
	onVolumeChange?: (volume: number) => void;
	/** Shows a previous-track button when set. */
	onPrevious?: () => void;
	/** Shows a next-track button when set. */
	onNext?: () => void;
	layout?: MusicPlayerLayout;
	labels?: Partial<MusicPlayerLabels>;
	class?: string;
} = $props();

const text = $derived({ ...MUSIC_PLAYER_LABELS, ...labels });
const s = $derived(musicPlayer({ layout }));
const level = $derived(clampUnit(volume));
const length = $derived(Math.max(0, duration));
const at = $derived(Math.min(length, Math.max(0, position)));

let audio = $state<HTMLAudioElement>();
let lastVolume = 1;

function setPlaying(next: boolean) {
	playing = next;
	onPlayingChange?.(next);
}
function setPosition(next: number) {
	position = next;
	onPositionChange?.(next);
}
function setVolume(next: number) {
	volume = next;
	onVolumeChange?.(next);
}
function toggleMute() {
	if (level > 0) {
		lastVolume = level;
		setVolume(0);
	} else setVolume(lastVolume);
}

$effect(() => {
	const el = audio;
	if (!el) return;
	if (playing) el.play().catch(() => setPlaying(false));
	else el.pause();
});

$effect(() => {
	if (audio) audio.volume = level;
});

$effect(() => {
	const el = audio;
	if (el && Math.abs(el.currentTime - at) > SEEK_TOLERANCE) el.currentTime = at;
});
</script>

<div
	data-slot="music-player"
	data-layout={layout}
	data-playing={playing}
	class={cn(s.root(), classProp)}
>
	{#if src}
		<audio
			bind:this={audio}
			{src}
			preload="metadata"
			class="hidden"
			ontimeupdate={(e) => setPosition(e.currentTarget.currentTime)}
			onended={() => setPlaying(false)}
		></audio>
	{/if}
	<div class={s.frame()}>
		<div class={s.deck()}>
			<div class={s.disc()} data-playing={playing}>
				<img src={cover} alt={coverAlt} class={s.cover()} draggable="false" />
				<div aria-hidden="true" class={s.grooves()}></div>
				<div aria-hidden="true" class={s.label()}>
					<div class={s.pin()}></div>
				</div>
			</div>
			<div aria-hidden="true" class={s.sheen()}></div>
			<div aria-hidden="true" class={s.arm()} data-playing={playing}>
				<div class={s.armBase()}></div>
				<div class={s.armStick()}>
					<div class={s.needle()}></div>
				</div>
			</div>
		</div>
		<div class={s.body()}>
			<div class={s.meta()}>
				<span class={s.title()}>{title}</span>
				<span class={s.artist()}>{artist}</span>
			</div>
			<div class={s.scrub()}>
				<Slider
					size="sm"
					label={text.seek}
					min={0}
					max={length}
					step={1}
					value={at}
					onValueChange={(v) => setPosition(v as number)}
				/>
				<div class={s.times()} aria-hidden="true">
					<span>{formatTime(at)}</span>
					<span>-{formatTime(length - at)}</span>
				</div>
			</div>
			<div class={s.controls()}>
				<div class={s.transport()}>
					{#if onPrevious}
						<Button variant="ghost" size="icon" aria-label={text.previous} onclick={onPrevious}>
							<svg
								viewBox="0 0 24 24"
								fill="none"
								stroke="currentColor"
								stroke-width="2"
								stroke-linecap="round"
								stroke-linejoin="round"
								aria-hidden="true"
							>
								<path d="M20 5v14l-12 -7z" />
								<path d="M4 5l0 14" />
							</svg>
						</Button>
					{/if}
					<Button
						size="icon-lg"
						class="rounded-full"
						aria-label={playing ? text.pause : text.play}
						onclick={() => setPlaying(!playing)}
					>
						<svg
							viewBox="0 0 24 24"
							fill="currentColor"
							stroke="currentColor"
							stroke-width="2"
							stroke-linecap="round"
							stroke-linejoin="round"
							aria-hidden="true"
						>
							{#if playing}
								<path
									d="M6 6a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v12a1 1 0 0 1 -1 1h-2a1 1 0 0 1 -1 -1z"
								/>
								<path
									d="M14 6a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v12a1 1 0 0 1 -1 1h-2a1 1 0 0 1 -1 -1z"
								/>
							{:else}
								<path d="M7 4v16l13 -8z" />
							{/if}
						</svg>
					</Button>
					{#if onNext}
						<Button variant="ghost" size="icon" aria-label={text.next} onclick={onNext}>
							<svg
								viewBox="0 0 24 24"
								fill="none"
								stroke="currentColor"
								stroke-width="2"
								stroke-linecap="round"
								stroke-linejoin="round"
								aria-hidden="true"
							>
								<path d="M4 5v14l12 -7z" />
								<path d="M20 5l0 14" />
							</svg>
						</Button>
					{/if}
				</div>
				<div class={s.volume()}>
					<Button
						variant="ghost"
						size="icon-sm"
						aria-label={level > 0 ? text.mute : text.unmute}
						onclick={toggleMute}
					>
						<svg
							viewBox="0 0 24 24"
							fill="none"
							stroke="currentColor"
							stroke-width="2"
							stroke-linecap="round"
							stroke-linejoin="round"
							aria-hidden="true"
						>
							<path
								d="M6 15h-2a1 1 0 0 1 -1 -1v-4a1 1 0 0 1 1 -1h2l3.5 -4.5a.8 .8 0 0 1 1.5 .5v14a.8 .8 0 0 1 -1.5 .5l-3.5 -4.5"
							/>
							{#if level > 0}
								<path d="M15 8a5 5 0 0 1 0 8" />
								<path d="M17.7 5a9 9 0 0 1 0 14" />
							{:else}
								<path d="M16 10l4 4m0 -4l-4 4" />
							{/if}
						</svg>
					</Button>
					<Slider
						size="sm"
						label={text.volume}
						min={0}
						max={100}
						step={1}
						value={Math.round(level * 100)}
						onValueChange={(v) => setVolume((v as number) / 100)}
					/>
				</div>
			</div>
		</div>
	</div>
</div>
