// packages/ui-react/src/hover-card/hover-card.tsx
"use client";

import type { ReactNode } from "react";
import { useEffect, useId, useRef, useState } from "react";
import { type AnchorPlacement, anchor } from "../lib/anchor";
import { cn } from "../lib/cn";

export interface HoverCardProps {
	trigger: ReactNode;
	children: ReactNode;
	placement?: AnchorPlacement;
	openDelay?: number;
	closeDelay?: number;
	className?: string;
}

export function HoverCard({
	trigger,
	children,
	placement = "bottom-start",
	openDelay = 300,
	closeDelay = 150,
	className,
}: HoverCardProps) {
	const id = useId();
	const [open, setOpen] = useState(false);
	const wrapper = useRef<HTMLSpanElement>(null);
	const floating = useRef<HTMLDivElement>(null);
	const timer = useRef<ReturnType<typeof setTimeout>>(undefined);

	function schedule(next: boolean) {
		clearTimeout(timer.current);
		timer.current = setTimeout(() => setOpen(next), next ? openDelay : closeDelay);
	}

	useEffect(() => {
		if (!open || !wrapper.current || !floating.current) return;
		return anchor(wrapper.current, floating.current, { placement, gap: 8 });
	}, [open, placement]);

	return (
		<>
			{/* biome-ignore lint/a11y/noStaticElementInteractions: the child carries the semantics; this only measures */}
			<span
				ref={wrapper}
				className="inline-flex"
				aria-describedby={open ? id : undefined}
				onPointerEnter={() => schedule(true)}
				onPointerLeave={() => schedule(false)}
				onFocus={() => schedule(true)}
				onBlur={() => schedule(false)}
			>
				{trigger}
			</span>

			{open ? (
				<div
					ref={floating}
					id={id}
					role="dialog"
					tabIndex={-1}
					onPointerEnter={() => schedule(true)}
					onPointerLeave={() => schedule(false)}
					className={cn(
						"anchored z-50 w-64 rounded-xl border border-border bg-popover p-3 text-sm shadow-2xl",
						className,
					)}
				>
					{children}
				</div>
			) : null}
		</>
	);
}

// packages/ui-svelte/src/lib/hover-card/hover-card.svelte
<script lang="ts">
import type { Snippet } from "svelte";
import { type AnchorPlacement, anchor } from "../lib/anchor";
import { cn } from "../lib/cn";

let {
	trigger,
	children,
	placement = "bottom-start",
	openDelay = 300,
	closeDelay = 150,
	class: classProp,
}: {
	trigger: Snippet;
	children: Snippet;
	placement?: AnchorPlacement;
	openDelay?: number;
	closeDelay?: number;
	class?: string;
} = $props();

const id = $props.id();
let open = $state(false);
let wrapper = $state<HTMLSpanElement>();
let floating = $state<HTMLDivElement>();
let timer: ReturnType<typeof setTimeout>;

function schedule(next: boolean) {
	clearTimeout(timer);
	timer = setTimeout(() => (open = next), next ? openDelay : closeDelay);
}

$effect(() => {
	if (!open || !wrapper || !floating) return;
	return anchor(wrapper, floating, { placement, gap: 8 });
});
</script>

<!-- svelte-ignore a11y_no_static_element_interactions -->
<span
	bind:this={wrapper}
	class="inline-flex"
	onpointerenter={() => schedule(true)}
	onpointerleave={() => schedule(false)}
	onfocusin={() => schedule(true)}
	onfocusout={() => schedule(false)}
	aria-describedby={open ? id : undefined}
>
	{@render trigger()}
</span>

{#if open}
	<div
		bind:this={floating}
		{id}
		role="dialog"
		tabindex="-1"
		onpointerenter={() => schedule(true)}
		onpointerleave={() => schedule(false)}
		class={cn(
			"anchored z-50 w-64 rounded-xl border border-border bg-popover p-3 text-sm shadow-2xl",
			classProp,
		)}
	>
		{@render children()}
	</div>
{/if}
