// packages/ui-react/src/particle-text/particle-text.tsx
"use client";

import { useEffect, useRef } from "react";
import { cn } from "../lib/cn";
import {
	mountParticles,
	type ParticleOptions,
	type ParticleTextShape,
	type ParticleTextSize,
	particleText,
} from "./particles";

export type { ParticleTextShape, ParticleTextSize };

export interface ParticleTextProps {
	text: string;
	/** Largest font size in px; shrinks to fit narrow containers. */
	fontSize?: number;
	/** Radius of each particle, in px. */
	particleSize?: number;
	/** Sampling step in px: lower means more particles. */
	density?: number;
	/** How hard the pointer pushes particles inside `radius`. */
	strength?: number;
	/** Pointer influence radius, in px. */
	radius?: number;
	/** Spring pull back home per frame, 0 to 1. */
	returnSpeed?: number;
	shape?: ParticleTextShape;
	size?: ParticleTextSize;
	className?: string;
}

/** Text drawn as canvas particles that scatter from the pointer and spring back into place. */
export function ParticleText({
	text,
	fontSize = 120,
	particleSize = 1.5,
	density = 6,
	strength = 15,
	radius = 120,
	returnSpeed = 0.08,
	shape = "circle",
	size,
	className,
}: ParticleTextProps) {
	const root = useRef<HTMLDivElement>(null);
	const canvas = useRef<HTMLCanvasElement>(null);
	const field = useRef<ReturnType<typeof mountParticles>>(null);
	const s = particleText({ shape, size });
	const options: ParticleOptions = {
		text,
		fontSize,
		particleSize,
		density,
		strength,
		radius,
		returnSpeed,
		shape,
	};
	const latest = useRef(options);
	latest.current = options;

	useEffect(() => {
		if (!root.current || !canvas.current) return;
		field.current = mountParticles(root.current, canvas.current, latest.current);
		return () => field.current?.destroy();
	}, []);

	useEffect(() => {
		field.current?.update(latest.current);
	}, [text, fontSize, particleSize, density, strength, radius, returnSpeed, shape]);

	return (
		<div ref={root} data-slot="particle-text" className={cn(s.root(), className)}>
			<span className={s.srOnly()}>{text}</span>
			<canvas ref={canvas} aria-hidden className={s.canvas()} />
		</div>
	);
}

// packages/ui-svelte/src/lib/particle-text/particle-text.svelte
<script lang="ts">
import { untrack } from "svelte";
import { cn } from "../lib/cn";
import {
	mountParticles,
	type ParticleOptions,
	type ParticleTextShape,
	type ParticleTextSize,
	particleText,
} from "./particles";

let {
	text,
	fontSize = 120,
	particleSize = 1.5,
	density = 6,
	strength = 15,
	radius = 120,
	returnSpeed = 0.08,
	shape = "circle",
	size,
	class: className,
}: {
	text: string;
	/** Largest font size in px; shrinks to fit narrow containers. */
	fontSize?: number;
	/** Radius of each particle, in px. */
	particleSize?: number;
	/** Sampling step in px: lower means more particles. */
	density?: number;
	/** How hard the pointer pushes particles inside `radius`. */
	strength?: number;
	/** Pointer influence radius, in px. */
	radius?: number;
	/** Spring pull back home per frame, 0 to 1. */
	returnSpeed?: number;
	shape?: ParticleTextShape;
	size?: ParticleTextSize;
	class?: string;
} = $props();

const s = $derived(particleText({ shape, size }));
const options: ParticleOptions = $derived({
	text,
	fontSize,
	particleSize,
	density,
	strength,
	radius,
	returnSpeed,
	shape,
});

let root = $state<HTMLDivElement>();
let canvas = $state<HTMLCanvasElement>();
let field: ReturnType<typeof mountParticles> | undefined;

$effect(() => {
	if (!root || !canvas) return;
	// Mount once; later option changes go through update() below.
	field = mountParticles(
		root,
		canvas,
		untrack(() => $state.snapshot(options)),
	);
	return () => field?.destroy();
});

$effect(() => {
	const next = $state.snapshot(options);
	field?.update(next);
});
</script>

<div bind:this={root} data-slot="particle-text" class={cn(s.root(), className)}>
	<span class={s.srOnly()}>{text}</span>
	<canvas bind:this={canvas} aria-hidden="true" class={s.canvas()}></canvas>
</div>
