// packages/ui-react/src/chart-series/dash-tail.tsx
"use client";

import { type CSSProperties, useId } from "react";
import { useCartesian } from "../chart/frame";
import { cn } from "../lib/cn";

const PAD = 10;

export interface DashTailProps {
	d: string;
	/** Plot x where the stroke turns dashed, e.g. the start of an incomplete period. */
	fromX: number;
	stroke: string;
	strokeWidth: number;
	className?: string;
	style?: CSSProperties;
}

/** The same path twice, clipped either side of `fromX`: solid before, dashed after. */
export function DashTail({
	d,
	fromX,
	stroke,
	strokeWidth,
	className,
	style,
}: DashTailProps) {
	const { innerWidth, innerHeight } = useCartesian();
	const id = useId().replace(/:/g, "");
	const height = innerHeight + PAD * 2;
	return (
		<g data-slot="chart-dash-tail" className={className} style={style}>
			<defs>
				<clipPath id={`${id}-solid`}>
					<rect x={-PAD} y={-PAD} width={Math.max(0, fromX + PAD)} height={height} />
				</clipPath>
				<clipPath id={`${id}-dash`}>
					<rect
						x={fromX}
						y={-PAD}
						width={Math.max(0, innerWidth - fromX + PAD)}
						height={height}
					/>
				</clipPath>
			</defs>
			<path
				d={d}
				clipPath={`url(#${id}-solid)`}
				stroke={stroke}
				strokeWidth={strokeWidth}
				className="fill-none [stroke-linecap:round]"
			/>
			<path
				data-slot="chart-dash-tail-dashed"
				d={d}
				clipPath={`url(#${id}-dash)`}
				stroke={stroke}
				strokeWidth={strokeWidth}
				className={cn("fill-none [stroke-dasharray:6_4]")}
			/>
		</g>
	);
}

// packages/ui-svelte/src/lib/chart-series/dash-tail.svelte
<svelte:options namespace="svg" />

<script lang="ts">
import { useCartesian } from "../chart/context";

let {
	d,
	fromX,
	stroke,
	strokeWidth,
	class: className,
	style,
}: {
	d: string;
	/** Plot x where the stroke turns dashed, e.g. the start of an incomplete period. */
	fromX: number;
	stroke: string;
	strokeWidth: number;
	class?: string;
	style?: string;
} = $props();

const PAD = 10;
const plot = useCartesian();
const uid = $props.id();
const height = $derived(plot.innerHeight + PAD * 2);
</script>

<g data-slot="chart-dash-tail" class={className} {style}>
	<defs>
		<clipPath id="{uid}-solid">
			<rect x={-PAD} y={-PAD} width={Math.max(0, fromX + PAD)} {height} />
		</clipPath>
		<clipPath id="{uid}-dash">
			<rect x={fromX} y={-PAD} width={Math.max(0, plot.innerWidth - fromX + PAD)} {height} />
		</clipPath>
	</defs>
	<path
		{d}
		clip-path="url(#{uid}-solid)"
		{stroke}
		stroke-width={strokeWidth}
		class="fill-none [stroke-linecap:round]"
	/>
	<path
		data-slot="chart-dash-tail-dashed"
		{d}
		clip-path="url(#{uid}-dash)"
		{stroke}
		stroke-width={strokeWidth}
		class="fill-none [stroke-dasharray:6_4]"
	/>
</g>
