// packages/demos/src/react/chat-composer.tsx
"use client";

import { ChatComposer, type ChatTopic } from "@baby-ui/react";

type Props = Record<string, unknown>;

const TOPICS: ChatTopic[] = [
	{
		key: "flavors",
		label: "Flavors",
		initialPrompt: "Compare mint chip to last summer",
		messages: [
			{
				label: "Sales History",
				sub: "Flavor Data",
				time: "4s",
				body: "Pulled 3 summers of mint chip sales for comparison.",
			},
			{
				label: "Comparison",
				sub: "Trend Detection",
				time: "2s",
				body: "Mint chip is up 12% with stronger weekend peaks.",
			},
		],
	},
	{
		key: "suppliers",
		label: "Suppliers",
		initialPrompt: "Which suppliers are behind schedule?",
		messages: [
			{
				label: "Supplier Status",
				sub: "Order Tracking",
				time: "3s",
				body: "2 of 14 suppliers have shipments running late this week.",
			},
			{
				label: "Root Cause",
				sub: "Delay Analysis",
				time: "5s",
				body: "Cone King's delay traces back to a packaging shortage, expected clear by Friday.",
			},
		],
	},
];

export function ChatComposerDemo({ props: _props }: { props: Props }) {
	return <ChatComposer topics={TOPICS} placeholder="Prompt or tag a flavor with @" />;
}

// packages/demos/src/usage/svelte/chat-composer.svelte
<script lang="ts">
import { ChatComposer, type ChatTopic } from "@baby-ui/svelte";

const TOPICS: ChatTopic[] = [
	{
		key: "flavors",
		label: "Flavors",
		initialPrompt: "Compare mint chip to last summer",
		messages: [
			{
				label: "Sales History",
				sub: "Flavor Data",
				time: "4s",
				body: "Pulled 3 summers of data.",
			},
		],
	},
];
</script>

<ChatComposer topics={TOPICS} />
