// packages/demos/src/usage/react/fisheye-infinite-grid.tsx
import { FisheyeInfiniteGrid } from "@baby-ui/react";

const items = [
	{ src: "/work/one.jpg", alt: "Studio portrait", title: "Portrait", caption: "2024" },
	{ src: "/work/two.jpg", alt: "Coastline at dawn", title: "Coast", caption: "2025" },
];

export function Example() {
	return <FisheyeInfiniteGrid items={items} />;
}

// packages/demos/src/usage/svelte/fisheye-infinite-grid.svelte
<script lang="ts">
import { FisheyeInfiniteGrid } from "@baby-ui/svelte";

const items = [
	{ src: "/work/one.jpg", alt: "Studio portrait", title: "Portrait", caption: "2024" },
	{ src: "/work/two.jpg", alt: "Coastline at dawn", title: "Coast", caption: "2025" },
];
</script>

<FisheyeInfiniteGrid {items} />
