// packages/demos/src/usage/react/form.tsx
import {
	Form,
	FormButton,
	FormControl,
	FormField,
	FormFieldErrors,
	FormLabel,
	Input,
} from "@baby-ui/react";
import { useForm } from "@tanstack/react-form";
import { z } from "zod";

const schema = z.object({ email: z.email("Enter a valid email.") });

export function Example() {
	const form = useForm({
		defaultValues: { email: "" },
		validators: { onSubmit: schema },
		onSubmit: ({ value }) => console.log(value),
	});

	return (
		<Form form={form}>
			<form.Field name="email">
				{(field) => (
					<FormField field={field}>
						<FormLabel>Email</FormLabel>
						<FormControl>
							{(props) => (
								<Input
									{...props}
									type="email"
									value={field.state.value}
									onChange={(e) => field.handleChange(e.currentTarget.value)}
								/>
							)}
						</FormControl>
						<FormFieldErrors />
					</FormField>
				)}
			</form.Field>
			<FormButton>Save</FormButton>
		</Form>
	);
}

// packages/demos/src/usage/svelte/form.svelte
<script lang="ts">
import {
	Form,
	FormButton,
	FormControl,
	FormField,
	FormFieldErrors,
	FormLabel,
} from "@baby-ui/svelte/form";
import { Input } from "@baby-ui/svelte/input";
import { createForm } from "@tanstack/svelte-form";
import { z } from "zod";

const schema = z.object({ email: z.email("Enter a valid email.") });

const form = createForm(() => ({
	defaultValues: { email: "" },
	validators: { onSubmit: schema },
	onSubmit: ({ value }) => console.log(value),
}));
</script>

<Form {form}>
	<form.Field name="email">
		{#snippet children(field)}
			<FormField {field}>
				<FormLabel>Email</FormLabel>
				<FormControl>
					{#snippet child({ props })}
						<Input
							{...props}
							type="email"
							value={field.state.value}
							oninput={(e) => field.handleChange(e.currentTarget.value)}
						/>
					{/snippet}
				</FormControl>
				<FormFieldErrors />
			</FormField>
		{/snippet}
	</form.Field>
	<FormButton>Save</FormButton>
</Form>
