// packages/demos/src/usage/react/hover-card.tsx
import { HoverCard, HoverCardContent, HoverCardTrigger } from "@baby-ui/react";

export function Example() {
	return (
		<HoverCard>
			<HoverCardTrigger>
				<a href="/about">baby-ui</a>
			</HoverCardTrigger>
			<HoverCardContent>
				<p className="text-sm">
					A registry of React and Svelte components built from one spec.
				</p>
			</HoverCardContent>
		</HoverCard>
	);
}

// packages/demos/src/usage/svelte/hover-card.svelte
<script lang="ts">
import { HoverCard, HoverCardContent, HoverCardTrigger } from "@baby-ui/svelte";
</script>

<HoverCard>
	<HoverCardTrigger>
		<a href="/about">baby-ui</a>
	</HoverCardTrigger>
	<HoverCardContent>
		<p class="text-sm">A registry of React and Svelte components built from one spec.</p>
	</HoverCardContent>
</HoverCard>
