// packages/demos/src/react/projection-line.tsx
"use client";

import {
	buildProjection,
	CartesianGrid,
	type ChartConfig,
	ChartContainer,
	ChartTooltip,
	Line,
	LineChart,
	ProjectionLine,
	type ProjectionLineCurve,
	type ProjectionLineVariant,
	XAxis,
	YAxis,
} from "@baby-ui/react";
import { VISITORS, VISITORS_CONFIG } from "../data/visitors";

type Props = Record<string, unknown>;

const config = VISITORS_CONFIG satisfies ChartConfig;

export function ProjectionLineDemo({ props }: { props: Props }) {
	const projection = buildProjection({
		data: VISITORS,
		dataKey: "desktop",
		horizon: Number(props.horizon ?? 7),
	});
	return (
		<div className="w-full max-w-3xl">
			<ChartContainer config={config} title="Desktop visitors with forecast">
				<LineChart data={VISITORS}>
					<CartesianGrid />
					<YAxis />
					<XAxis />
					<Line dataKey="desktop" fadeEdges="left" />
					<ProjectionLine
						data={projection}
						variant={(props.variant as ProjectionLineVariant) ?? "dashed"}
						curve={(props.curve as ProjectionLineCurve) ?? "linear"}
						endMarker={props.endMarker !== false}
					/>
					<ChartTooltip />
				</LineChart>
			</ChartContainer>
		</div>
	);
}

// packages/demos/src/usage/svelte/projection-line.svelte
<script lang="ts">
import { buildProjection, ProjectionLine } from "@baby-ui/svelte";
import {
	CartesianGrid,
	type ChartConfig,
	ChartContainer,
	ChartTooltip,
	XAxis,
	YAxis,
} from "@baby-ui/svelte/chart";
import { Line, LineChart } from "@baby-ui/svelte/line-chart";

const data = [
	{ date: new Date("2026-06-01"), revenue: 4200 },
	{ date: new Date("2026-06-02"), revenue: 5100 },
	{ date: new Date("2026-06-03"), revenue: 4800 },
	{ date: new Date("2026-06-04"), revenue: 6200 },
];

const config = {
	revenue: { label: "Revenue", color: "var(--chart-1)" },
} satisfies ChartConfig;
const forecast = buildProjection({ data, dataKey: "revenue", horizon: 3 });
</script>

<ChartContainer {config} title="Revenue forecast">
	<LineChart {data}>
		<CartesianGrid />
		<YAxis />
		<XAxis />
		<Line dataKey="revenue" />
		<ProjectionLine data={forecast} curve="bezier" />
		<ChartTooltip />
	</LineChart>
</ChartContainer>
