// packages/demos/src/usage/react/radio-group.tsx
"use client";

import { RadioGroup } from "@baby-ui/react";
import { useState } from "react";

const options = [
	{ value: "hobby", label: "Hobby", description: "For side projects." },
	{ value: "pro", label: "Pro", description: "For teams shipping daily." },
];

export function Example() {
	const [value, setValue] = useState("hobby");

	return (
		<RadioGroup
			value={value}
			onValueChange={setValue}
			options={options}
			variant="card"
			name="plan"
		/>
	);
}

// packages/demos/src/usage/svelte/radio-group.svelte
<script lang="ts">
import { RadioGroup } from "@baby-ui/svelte";

let value = $state("hobby");
const options = [
	{ value: "hobby", label: "Hobby", description: "For side projects." },
	{ value: "pro", label: "Pro", description: "For teams shipping daily." },
];
</script>

<RadioGroup bind:value {options} variant="card" name="plan" />
