// packages/demos/src/react/records-table.tsx
"use client";

import { type RecordRow, type RecordsDensity, RecordsTable } from "@baby-ui/react";
import { useEffect, useState } from "react";

type Props = Record<string, unknown>;

const ROWS: RecordRow[] = [
	{
		id: "1",
		name: "Northwind Traders",
		tags: ["Retail", "Logistics"],
		last: "3 days ago",
		strength: "strong",
		website: "northwindtraders.com",
		aiValue: "Series B, $40M raised",
	},
	{
		id: "2",
		name: "Vantage Analytics",
		tags: ["Data", "B2B"],
		last: "2 weeks ago",
		strength: "weak",
		website: "vantageanalytics.io",
		aiValue: "Bootstrapped, profitable",
	},
	{
		id: "3",
		name: "Coral Reef Studio",
		tags: ["Design"],
		last: "No contact",
		strength: "none",
		aiValue: "Acquired by Adobe, 2024",
	},
	{
		id: "4",
		name: "Ferrous Robotics",
		tags: ["Hardware", "Manufacturing"],
		last: "1 month ago",
		strength: "veryweak",
		website: "ferrousrobotics.com",
		aiValue: "Series A, $12M raised",
	},
	{
		id: "5",
		name: "Lumen Health",
		tags: ["Healthcare", "AI"],
		last: "Yesterday",
		strength: "strong",
		website: "lumenhealth.co",
		aiValue: "Series C, $85M raised",
	},
];

const MODEL_OPTIONS = ["GPT-5", "Claude Sonnet 5", "Gemini 2.5 Pro"];

export function RecordsTableDemo({ props }: { props: Props }) {
	const [calculatingColumn, setCalculatingColumn] = useState<string | null>(null);
	const [resolvedCount, setResolvedCount] = useState(0);

	useEffect(() => {
		if (!calculatingColumn) return;
		if (resolvedCount >= ROWS.length) {
			setCalculatingColumn(null);
			return;
		}
		const timer = setTimeout(() => setResolvedCount((count) => count + 1), 110);
		return () => clearTimeout(timer);
	}, [calculatingColumn, resolvedCount]);

	return (
		<RecordsTable
			rows={ROWS}
			modelOptions={MODEL_OPTIONS}
			fill={props.fill as boolean | undefined}
			density={props.density as RecordsDensity | undefined}
			calculatingColumn={calculatingColumn}
			resolvedCount={resolvedCount}
			onCalculate={(column) => {
				setCalculatingColumn(column);
				setResolvedCount(0);
			}}
		/>
	);
}

// packages/demos/src/usage/svelte/records-table.svelte
<script lang="ts">
import { RecordsTable } from "@baby-ui/svelte";
</script>

<RecordsTable
	rows={[
		{
			id: "1",
			name: "Northwind Traders",
			tags: ["Retail"],
			last: "3 days ago",
			strength: "strong",
			website: "northwindtraders.com",
		},
		{ id: "2", name: "Coral Reef Studio", tags: ["Design"], last: "No contact", strength: "none" },
	]}
/>
