// packages/ui-svelte/src/lib/jumping-text/jumping-text.svelte
<script lang="ts">
import { cn } from "../lib/cn";
import { type JumpingTextMode, type JumpingTextSize, jumpingText } from "./variants";

let {
	text,
	mode = "word",
	stepMs: stepMsProp,
	durationMs = 500,
	size = "md",
	class: classProp,
}: {
	text: string;
	mode?: JumpingTextMode;
	stepMs?: number;
	durationMs?: number;
	size?: JumpingTextSize;
	class?: string;
} = $props();

const SPLIT = {
	word: (t: string) => t.split(/(?:\b)/u),
	character: (t: string) => t.split(/(?:)/u),
};

const nodes = $derived(SPLIT[mode](text));
const stepMs = $derived(stepMsProp ?? (mode === "word" ? 50 : 10));
</script>

<div data-slot="jumping-text" class={cn(jumpingText({ size }), classProp)}>
	{#key text}
		{#each nodes as node, index (index)}
			<span
				class="jump-in inline-block origin-center"
				style="animation-delay: {index * stepMs}ms; --jump-duration: {durationMs}ms;"
			>
				{node === " " ? " " : node}
			</span>
		{/each}
	{/key}
	<span class="sr-only">{text}</span>
</div>

// packages/ui-react/src/jumping-text/jumping-text.tsx
import type { CSSProperties } from "react";
import { cn } from "../lib/cn";
import { type JumpingTextMode, type JumpingTextSize, jumpingText } from "./variants";

export type { JumpingTextMode, JumpingTextSize };

export interface JumpingTextProps {
	text: string;
	/** Stagger per whole word, or per character. */
	mode?: JumpingTextMode;
	/** Delay step between units, in ms. Defaults to 50 for words, 10 for characters. */
	stepMs?: number;
	/** How long each unit's jump-in takes, in ms. */
	durationMs?: number;
	size?: JumpingTextSize;
	className?: string;
}

const SPLIT = {
	word: (text: string) => text.split(/(?:\b)/u),
	character: (text: string) => text.split(/(?:)/u),
};

export function JumpingText({
	text,
	mode = "word",
	stepMs,
	durationMs = 500,
	size = "md",
	className,
}: JumpingTextProps) {
	const nodes = SPLIT[mode](text);
	const step = stepMs ?? (mode === "word" ? 50 : 10);
	return (
		<div data-slot="jumping-text" className={cn(jumpingText({ size }), className)}>
			{nodes.map((node, index) => (
				<span
					key={`${text}-${index}`}
					className="jump-in inline-block origin-center"
					style={
						{
							animationDelay: `${index * step}ms`,
							"--jump-duration": `${durationMs}ms`,
						} as CSSProperties
					}
				>
					{node === " " ? " " : node}
				</span>
			))}
			<span className="sr-only">{text}</span>
		</div>
	);
}
