// packages/ui-svelte/src/lib/typing-text/typing-text.svelte
<script lang="ts">
import { cn } from "../lib/cn";
import { typingStumbleSteps } from "./stumble";
import { type TypingTextSize, typingText } from "./variants";

let {
	text,
	delay = 32,
	repeat = true,
	waitMs = 1000,
	smooth = false,
	fadeDurationMs = 300,
	grow = false,
	hideCursorOnComplete = false,
	stumbles = false,
	onComplete,
	size = "md",
	class: classProp,
}: {
	text: string;
	delay?: number;
	repeat?: boolean;
	waitMs?: number;
	smooth?: boolean;
	/** How long each word's fade-in takes, in ms. Only applies when `smooth` is true. */
	fadeDurationMs?: number;
	grow?: boolean;
	hideCursorOnComplete?: boolean;
	/** Types like a person: wrong keys appear and get corrected. `delay` scales the pace. */
	stumbles?: boolean;
	onComplete?: () => void;
	size?: TypingTextSize;
	class?: string;
} = $props();

const stumbling = $derived(stumbles && !smooth);
const words = $derived(text.split(/\s+/));
const total = $derived(smooth ? words.length : text.length);

let index = $state(0);
let direction = $state<1 | -1>(1);
let completed = false;
let blinkOn = $state(true);

// Stumble mode: frames timed at a 32ms reference delay, scaled by `delay`.
let pass = $state(0);
let step = $state(0);
let reduced = $state(false);
const steps = $derived(typingStumbleSteps(text, pass));
const stumbleDone = $derived(step >= steps.length);

$effect(() => {
	text; // re-run whenever the text prop changes, not just on mount
	index = 0;
	direction = 1;
	completed = false;
	pass = 0;
	step = 0;
});

$effect(() => {
	const id = setInterval(() => {
		blinkOn = !blinkOn;
	}, 500);
	return () => clearInterval(id);
});

$effect(() => {
	const query = matchMedia("(prefers-reduced-motion: reduce)");
	reduced = query.matches;
	const update = () => (reduced = query.matches);
	query.addEventListener("change", update);
	return () => query.removeEventListener("change", update);
});

const atEnd = $derived(index >= total);
const atStart = $derived(index <= 0);
const paused = $derived((atEnd && direction === 1) || (atStart && direction === -1));

$effect(() => {
	if (stumbling || paused) return;
	const tick = Math.max(1, delay);
	const id = setInterval(() => {
		const next = index + direction;
		index = direction === 1 ? Math.min(next, total) : Math.max(next, 0);
	}, tick);
	return () => clearInterval(id);
});

$effect(() => {
	if (stumbling) return;
	if (atEnd && direction === 1) {
		if (!repeat) {
			if (!completed) {
				completed = true;
				onComplete?.();
			}
			return;
		}
		const id = setTimeout(() => {
			direction = -1;
		}, waitMs);
		return () => clearTimeout(id);
	}
	if (atStart && direction === -1 && repeat) {
		const id = setTimeout(() => {
			direction = 1;
		}, waitMs);
		return () => clearTimeout(id);
	}
});

$effect(() => {
	if (!stumbling || reduced) return;
	if (stumbleDone) {
		onComplete?.();
		if (!repeat) return;
		const id = setTimeout(() => {
			pass += 1;
			step = 0;
		}, waitMs);
		return () => clearTimeout(id);
	}
	const id = setTimeout(() => (step += 1), (steps[step]?.wait ?? 0) * (delay / 32));
	return () => clearTimeout(id);
});

const shown = $derived(
	stumbling
		? reduced || stumbleDone
			? text
			: (steps[step]?.text ?? "")
		: text.slice(0, index),
);
const isComplete = $derived(
	stumbling ? stumbleDone && !repeat : index === total && !repeat,
);
const showCursor = $derived(!smooth && (!hideCursorOnComplete || !isComplete));
const cursorSolid = $derived(stumbling ? stumbleDone : atEnd || atStart);
const classes = $derived(typingText({ size }));
</script>

<div data-slot="typing-text" class={cn(classes, classProp)} style="--tt-fade-duration: {fadeDurationMs}ms;">
	{#if stumbling}<span class="sr-only">{text}</span>{/if}
	{#if !grow}
		<div aria-hidden={stumbling || undefined} class="invisible">{text}</div>
	{/if}
	<div aria-hidden={stumbling || undefined} class={!grow ? "absolute inset-0" : undefined}>
		{#if smooth}
			<span class="flex flex-wrap whitespace-pre">
				{#each words as word, i (i)}
					<span class={cn("transition-opacity duration-[var(--tt-fade-duration,300ms)] ease-[var(--ease-in-out)]", i < index ? "opacity-100" : "opacity-0")}>
						{word}{#if i < words.length - 1}<span>&nbsp;</span>{/if}
					</span>
				{/each}
			</span>
		{:else}
			{shown}
		{/if}
		{#if showCursor}<span class={blinkOn || cursorSolid ? "" : "opacity-0"}>|</span>{/if}
	</div>
</div>

// packages/ui-react/src/typing-text/typing-text.tsx
"use client";

import { type CSSProperties, useEffect, useMemo, useRef, useState } from "react";
import { cn } from "../lib/cn";
import { typingStumbleSteps } from "./stumble";
import { type TypingTextSize, typingText } from "./variants";

export type { TypingTextSize };

export interface TypingTextProps {
	text: string;
	/** Delay between typing each character (or word, in `smooth` mode), in ms. */
	delay?: number;
	/** Erase after typing, then type again. */
	repeat?: boolean;
	/** Time to hold before the next cycle. Only applies when `repeat` is true. */
	waitMs?: number;
	/** Fades whole words in instead of typing character by character. */
	smooth?: boolean;
	/** How long each word's fade-in takes, in ms. Only applies when `smooth` is true. */
	fadeDurationMs?: number;
	/** Grow the container to fit the text as it types, instead of reserving full width up front. */
	grow?: boolean;
	/** Hide the blinking cursor once typing completes. */
	hideCursorOnComplete?: boolean;
	/** Types like a person: wrong keys appear and get corrected. `delay` scales the pace. */
	stumbles?: boolean;
	onComplete?: () => void;
	size?: TypingTextSize;
	className?: string;
}

// The stumble frames are timed at a 32ms reference delay; `delay` scales them.
function StumbleTyping({
	text,
	delay,
	repeat,
	waitMs,
	grow,
	hideCursorOnComplete,
	onComplete,
	size,
	className,
}: Required<Pick<TypingTextProps, "text" | "delay" | "repeat" | "waitMs" | "grow">> &
	Pick<TypingTextProps, "hideCursorOnComplete" | "onComplete" | "size" | "className">) {
	const [pass, setPass] = useState(0);
	const [step, setStep] = useState(0);
	const [reduced, setReduced] = useState(false);
	const steps = useMemo(() => typingStumbleSteps(text, pass), [text, pass]);
	const onDone = useRef(onComplete);
	onDone.current = onComplete;
	const blinkOn = useBlink(500);
	const done = step >= steps.length;

	useEffect(() => {
		const query = matchMedia("(prefers-reduced-motion: reduce)");
		setReduced(query.matches);
		const update = () => setReduced(query.matches);
		query.addEventListener("change", update);
		return () => query.removeEventListener("change", update);
	}, []);

	useEffect(() => {
		setPass(0);
		setStep(0);
	}, [text]);

	useEffect(() => {
		if (reduced) return;
		if (done) {
			onDone.current?.();
			if (!repeat) return;
			const id = setTimeout(() => {
				setPass((p) => p + 1);
				setStep(0);
			}, waitMs);
			return () => clearTimeout(id);
		}
		const id = setTimeout(
			() => setStep((s) => s + 1),
			(steps[step]?.wait ?? 0) * (delay / 32),
		);
		return () => clearTimeout(id);
	}, [reduced, done, step, steps, repeat, waitMs, delay]);

	const shown = reduced || done ? text : (steps[step]?.text ?? "");
	const showCursor = !hideCursorOnComplete || !(done && !repeat);

	return (
		<div data-slot="typing-text" className={cn(typingText({ size }), className)}>
			<span className="sr-only">{text}</span>
			{!grow && (
				<div aria-hidden className="invisible">
					{text}
				</div>
			)}
			<div aria-hidden className={cn(!grow && "absolute inset-0")}>
				{shown}
				{showCursor ? (
					<span className={blinkOn || done ? "" : "opacity-0"}>|</span>
				) : null}
			</div>
		</div>
	);
}

function useBlink(intervalMs: number) {
	const [on, setOn] = useState(true);
	useEffect(() => {
		const id = setInterval(() => setOn((v) => !v), intervalMs);
		return () => clearInterval(id);
	}, [intervalMs]);
	return on;
}

export function TypingText({
	text,
	delay = 32,
	repeat = true,
	waitMs = 1000,
	smooth = false,
	fadeDurationMs = 300,
	grow = false,
	hideCursorOnComplete = false,
	stumbles = false,
	onComplete,
	size = "md",
	className,
}: TypingTextProps) {
	if (stumbles && !smooth)
		return (
			<StumbleTyping
				text={text}
				delay={delay}
				repeat={repeat}
				waitMs={waitMs}
				grow={grow}
				hideCursorOnComplete={hideCursorOnComplete}
				onComplete={onComplete}
				size={size}
				className={className}
			/>
		);
	return (
		<PlainTyping
			text={text}
			delay={delay}
			repeat={repeat}
			waitMs={waitMs}
			smooth={smooth}
			fadeDurationMs={fadeDurationMs}
			grow={grow}
			hideCursorOnComplete={hideCursorOnComplete}
			onComplete={onComplete}
			size={size}
			className={className}
		/>
	);
}

function PlainTyping({
	text,
	delay = 32,
	repeat = true,
	waitMs = 1000,
	smooth = false,
	fadeDurationMs = 300,
	grow = false,
	hideCursorOnComplete = false,
	onComplete,
	size = "md",
	className,
}: Omit<TypingTextProps, "stumbles">) {
	const words = useMemo(() => text.split(/\s+/), [text]);
	const total = smooth ? words.length : text.length;
	const [index, setIndex] = useState(0);
	const [direction, setDirection] = useState<1 | -1>(1);
	const onCompleteRef = useRef(onComplete);
	const completedRef = useRef(false);
	onCompleteRef.current = onComplete;
	const blinkOn = useBlink(500);

	useEffect(() => {
		setIndex(0);
		setDirection(1);
		completedRef.current = false;
	}, [text]);

	const atEnd = index >= total;
	const atStart = index <= 0;
	const paused = (atEnd && direction === 1) || (atStart && direction === -1);

	useEffect(() => {
		if (paused) return;
		const step = Math.max(1, delay);
		const id = setInterval(() => {
			setIndex((current) => {
				const next = current + direction;
				return direction === 1 ? Math.min(next, total) : Math.max(next, 0);
			});
		}, step);
		return () => clearInterval(id);
	}, [paused, direction, delay, total]);

	useEffect(() => {
		if (atEnd && direction === 1) {
			if (!repeat) {
				if (!completedRef.current) {
					completedRef.current = true;
					onCompleteRef.current?.();
				}
				return;
			}
			const id = setTimeout(() => setDirection(-1), waitMs);
			return () => clearTimeout(id);
		}
		if (atStart && direction === -1 && repeat) {
			const id = setTimeout(() => setDirection(1), waitMs);
			return () => clearTimeout(id);
		}
	}, [atEnd, atStart, direction, repeat, waitMs]);

	const isComplete = index === total && !repeat;
	const showCursor = !smooth && (!hideCursorOnComplete || !isComplete);

	return (
		<div
			data-slot="typing-text"
			className={cn(typingText({ size }), className)}
			style={{ "--tt-fade-duration": `${fadeDurationMs}ms` } as CSSProperties}
		>
			{!grow && <div className="invisible">{text}</div>}
			<div className={cn(!grow && "absolute inset-0")}>
				{smooth ? (
					<span className="flex flex-wrap whitespace-pre">
						{words.map((word, i) => (
							<span
								key={i}
								className={cn(
									"transition-opacity duration-[var(--tt-fade-duration,300ms)] ease-[var(--ease-in-out)]",
									i < index ? "opacity-100" : "opacity-0",
								)}
							>
								{word}
								{i < words.length - 1 ? <span>&nbsp;</span> : null}
							</span>
						))}
					</span>
				) : (
					text.slice(0, index)
				)}
				{showCursor ? (
					<span className={blinkOn || atEnd || atStart ? "" : "opacity-0"}>|</span>
				) : null}
			</div>
		</div>
	);
}
