// packages/ui-svelte/src/lib/art-gallery/art-gallery.svelte
<script lang="ts">
import { untrack } from "svelte";
import { cn } from "../lib/cn";
import Spinner from "../spinner/spinner.svelte";
import { type ArtGalleryItem, createGallery } from "./gallery";
import { ART_GALLERY_LABELS, type ArtGalleryLabels } from "./labels";
import { type ArtGalleryLens, artGallery, LENS_STRENGTH } from "./variants";

let {
	items,
	cellSize = 0.75,
	dragZoom = 1.25,
	lens = "barrel",
	showHint = true,
	labels,
	class: classProp,
}: {
	/** Tiles repeat endlessly in both directions; images need CORS headers if remote. */
	items: ArtGalleryItem[];
	/** Cell size in world units; the view is 2 units tall. */
	cellSize?: number;
	/** How far the view pulls back while dragging; 1 disables it. */
	dragZoom?: number;
	lens?: ArtGalleryLens;
	showHint?: boolean;
	labels?: Partial<ArtGalleryLabels>;
	class?: string;
} = $props();

let root: HTMLElement | undefined = $state();
let canvas: HTMLCanvasElement | undefined = $state();
let phase = $state<"loading" | "webgl" | "fallback">("loading");
let gallery: ReturnType<typeof createGallery> | undefined;
const l = $derived({ ...ART_GALLERY_LABELS, ...labels });
const s = $derived(artGallery({ lens }));
const options = $derived({ cellSize, dragZoom, lens: LENS_STRENGTH[lens] });

$effect(() => {
	const list = items;
	const el = root;
	const surface = canvas;
	if (!el || !surface) return;
	phase = "loading";
	// Options flow through update(); only new items rebuild the atlases.
	gallery = untrack(() =>
		createGallery(el, surface, list, options, (webgl) => {
			phase = webgl ? "webgl" : "fallback";
		}),
	);
	return () => gallery?.destroy();
});

$effect(() => {
	gallery?.update(options);
});
</script>

<!-- svelte-ignore a11y_no_noninteractive_tabindex -- focus is how arrow keys pan the grid -->
<section
	bind:this={root}
	data-slot="art-gallery"
	aria-label={l.label}
	aria-roledescription="gallery"
	aria-busy={phase === "loading"}
	tabindex="0"
	class={cn(s.root(), classProp)}
>
	<ul class="sr-only">
		{#each items as item (item.src)}
			<li>{item.title}{item.caption ? `, ${item.caption}` : ""}</li>
		{/each}
	</ul>
	<canvas bind:this={canvas} class={cn(s.canvas(), phase !== "webgl" && "opacity-0")}></canvas>
	{#if phase === "loading"}
		<div class={s.status()}><Spinner label={l.loading} /></div>
	{:else if phase === "fallback"}
		<div class={s.fallback()}>
			{#each items as item (item.src)}
				<figure>
					<img src={item.src} alt={item.alt ?? item.title} class={s.fallbackImage()} />
					<figcaption class={s.fallbackCaption()}>
						<span>{item.title}</span>
						{#if item.caption}<span>{item.caption}</span>{/if}
					</figcaption>
				</figure>
			{/each}
		</div>
	{:else if showHint}
		<p aria-hidden="true" class={s.hint()}>{l.hint}</p>
	{/if}
</section>

// packages/ui-react/src/art-gallery/art-gallery.tsx
"use client";

import { useEffect, useRef, useState } from "react";
import { cn } from "../lib/cn";
import { Spinner } from "../spinner/spinner";
import { type ArtGalleryItem, createGallery } from "./gallery";
import { ART_GALLERY_LABELS, type ArtGalleryLabels } from "./labels";
import { type ArtGalleryLens, artGallery, LENS_STRENGTH } from "./variants";

export type { ArtGalleryItem, ArtGalleryLabels, ArtGalleryLens };

export interface ArtGalleryProps {
	/** Tiles repeat endlessly in both directions; images need CORS headers if remote. */
	items: ArtGalleryItem[];
	/** Cell size in world units; the view is 2 units tall. */
	cellSize?: number;
	/** How far the view pulls back while dragging; 1 disables it. */
	dragZoom?: number;
	lens?: ArtGalleryLens;
	showHint?: boolean;
	labels?: Partial<ArtGalleryLabels>;
	className?: string;
}

export function ArtGallery({
	items,
	cellSize = 0.75,
	dragZoom = 1.25,
	lens = "barrel",
	showHint = true,
	labels,
	className,
}: ArtGalleryProps) {
	const rootRef = useRef<HTMLElement>(null);
	const canvasRef = useRef<HTMLCanvasElement>(null);
	const galleryRef = useRef<ReturnType<typeof createGallery>>(null);
	const [phase, setPhase] = useState<"loading" | "webgl" | "fallback">("loading");
	const l = { ...ART_GALLERY_LABELS, ...labels };
	const s = artGallery({ lens });
	const options = { cellSize, dragZoom, lens: LENS_STRENGTH[lens] };

	useEffect(() => {
		if (!rootRef.current || !canvasRef.current) return;
		setPhase("loading");
		const gallery = createGallery(
			rootRef.current,
			canvasRef.current,
			items,
			options,
			(webgl) => setPhase(webgl ? "webgl" : "fallback"),
		);
		galleryRef.current = gallery;
		return () => gallery.destroy();
		// Options flow through update(); only new items rebuild the atlases.
	}, [items]);

	useEffect(() => {
		galleryRef.current?.update(options);
	});

	return (
		<section
			ref={rootRef}
			data-slot="art-gallery"
			aria-label={l.label}
			aria-roledescription="gallery"
			aria-busy={phase === "loading"}
			// biome-ignore lint/a11y/noNoninteractiveTabindex: focus is how arrow keys pan the grid
			tabIndex={0}
			className={cn(s.root(), className)}
		>
			<ul className="sr-only">
				{items.map((item) => (
					<li key={item.src}>
						{item.title}
						{item.caption ? `, ${item.caption}` : ""}
					</li>
				))}
			</ul>
			<canvas
				ref={canvasRef}
				className={cn(s.canvas(), phase !== "webgl" && "opacity-0")}
			/>
			{phase === "loading" ? (
				<div className={s.status()}>
					<Spinner label={l.loading} />
				</div>
			) : null}
			{phase === "fallback" ? (
				<div className={s.fallback()}>
					{items.map((item) => (
						<figure key={item.src}>
							<img
								src={item.src}
								alt={item.alt ?? item.title}
								className={s.fallbackImage()}
							/>
							<figcaption className={s.fallbackCaption()}>
								<span>{item.title}</span>
								{item.caption ? <span>{item.caption}</span> : null}
							</figcaption>
						</figure>
					))}
				</div>
			) : null}
			{phase === "webgl" && showHint ? (
				<p aria-hidden="true" className={s.hint()}>
					{l.hint}
				</p>
			) : null}
		</section>
	);
}
