// packages/ui-svelte/src/lib/magnet-lines/magnet-lines.svelte
<script lang="ts">
import { untrack } from "svelte";
import { cn } from "../lib/cn";
import { type MagnetLinesOptions, mountMagnetLines } from "./magnet";
import { type MagnetLinesSize, type MagnetLinesTone, magnetLines } from "./variants";

let {
	rows = 9,
	columns = 9,
	size = "md",
	tone = "muted",
	baseAngle = 0,
	class: classProp,
}: {
	rows?: number;
	columns?: number;
	size?: MagnetLinesSize;
	tone?: MagnetLinesTone;
	/** Degrees added to every line's pointer angle; also the resting angle. */
	baseAngle?: number;
	class?: string;
} = $props();

let root: HTMLDivElement | undefined = $state();
let engine: ReturnType<typeof mountMagnetLines> | undefined;
const s = $derived(magnetLines({ size, tone }));
const r = $derived(Math.max(1, Math.floor(rows)));
const c = $derived(Math.max(1, Math.floor(columns)));
const options: MagnetLinesOptions = $derived({ baseAngle });

$effect(() => {
	const el = root;
	if (!el) return;
	const mounted = untrack(() => mountMagnetLines(el, options));
	engine = mounted;
	return () => {
		mounted.destroy();
		engine = undefined;
	};
});

$effect(() => {
	void r;
	void c;
	void size;
	engine?.update(options);
});
</script>

<div
	bind:this={root}
	aria-hidden="true"
	data-slot="magnet-lines"
	class={cn(s.root(), classProp)}
	style:grid-template-columns={`repeat(${c}, minmax(0, 1fr))`}
	style:grid-template-rows={`repeat(${r}, minmax(0, 1fr))`}
	style:--ml-base={`${baseAngle}deg`}
>
	{#each { length: r * c }, i (i)}
		<span data-slot="magnet-lines-line" class={s.line()}></span>
	{/each}
</div>

// packages/ui-react/src/magnet-lines/magnet-lines.tsx
"use client";

import { type CSSProperties, useEffect, useRef } from "react";
import { cn } from "../lib/cn";
import { type MagnetLinesOptions, mountMagnetLines } from "./magnet";
import { type MagnetLinesSize, type MagnetLinesTone, magnetLines } from "./variants";

export type { MagnetLinesSize, MagnetLinesTone };

export interface MagnetLinesProps {
	rows?: number;
	columns?: number;
	size?: MagnetLinesSize;
	tone?: MagnetLinesTone;
	/** Degrees added to every line's pointer angle; also the resting angle. */
	baseAngle?: number;
	className?: string;
}

/** A grid of short lines that turn to face the pointer. */
export function MagnetLines({
	rows = 9,
	columns = 9,
	size = "md",
	tone = "muted",
	baseAngle = 0,
	className,
}: MagnetLinesProps) {
	const root = useRef<HTMLDivElement>(null);
	const engine = useRef<ReturnType<typeof mountMagnetLines>>(null);
	const s = magnetLines({ size, tone });
	const r = Math.max(1, Math.floor(rows));
	const c = Math.max(1, Math.floor(columns));
	const options: MagnetLinesOptions = { baseAngle };
	const latest = useRef(options);
	latest.current = options;

	useEffect(() => {
		if (!root.current) return;
		const mounted = mountMagnetLines(root.current, latest.current);
		engine.current = mounted;
		return () => {
			mounted.destroy();
			engine.current = null;
		};
	}, []);

	useEffect(() => {
		engine.current?.update(latest.current);
	}, [baseAngle, r, c, size]);

	return (
		<div
			ref={root}
			aria-hidden
			data-slot="magnet-lines"
			className={cn(s.root(), className)}
			style={
				{
					gridTemplateColumns: `repeat(${c}, minmax(0, 1fr))`,
					gridTemplateRows: `repeat(${r}, minmax(0, 1fr))`,
					"--ml-base": `${baseAngle}deg`,
				} as CSSProperties
			}
		>
			{Array.from({ length: r * c }, (_, i) => (
				<span key={i} data-slot="magnet-lines-line" className={s.line()} />
			))}
		</div>
	);
}
