// packages/ui-svelte/src/lib/pricing-02/pricing-02.svelte
<script lang="ts">
import type { HTMLAttributes } from "svelte/elements";
import Button from "../button/button.svelte";
import Card from "../card/card.svelte";
import { cn } from "../lib/cn";
import ToggleGroup from "../toggle-group/toggle-group.svelte";
import ToggleGroupItem from "../toggle-group/toggle-group-item.svelte";
import {
	digitDelay,
	PRICING_02_LABELS,
	type Pricing02Labels,
	type Pricing02Period,
	type Pricing02Plan,
} from "./types";
import { type Pricing02Variant, pricing02 } from "./variants";

type Props = Omit<HTMLAttributes<HTMLElement>, "title"> & {
	plans: Pricing02Plan[];
	/** Billing periods; the toggle shows when there are two or more. */
	periods: Pricing02Period[];
	/** Bindable. */
	period?: string;
	onPeriodChange?: (period: string) => void;
	/** Called by a plan's button when the plan has no `href`. */
	onSelect?: (planId: string, period: string) => void;
	eyebrow?: string;
	/** Line breaks in the string are kept. */
	title?: string;
	description?: string;
	/** Small print under the plans. */
	footnotes?: string[];
	variant?: Pricing02Variant;
	labels?: Partial<Pricing02Labels>;
};

let {
	plans,
	periods,
	period = $bindable(),
	onPeriodChange,
	onSelect,
	eyebrow,
	title,
	description,
	footnotes,
	variant = "soft",
	labels,
	class: classProp,
	...rest
}: Props = $props();

const ARROW = ["M5 12l14 0", "M13 18l6 -6", "M13 6l6 6"];

const currentIndex = $derived(
	Math.max(
		0,
		periods.findIndex((p) => p.value === period),
	),
);
const current = $derived(periods[currentIndex]);
const l = $derived({ ...PRICING_02_LABELS, ...labels });
const s = $derived(pricing02({ variant }));

// Digits only roll once the period has changed, never on first paint.
let initial: string | undefined;
let seen = false;
let changed = false;
const moved = $derived.by(() => {
	const value = current?.value;
	if (!seen) {
		seen = true;
		initial = value;
	} else if (value !== initial) changed = true;
	return changed;
});

function setPeriod(next: string) {
	if (!next) return;
	period = next;
	onPeriodChange?.(next);
}
</script>

{#snippet arrow()}
	<svg
		viewBox="0 0 24 24"
		fill="none"
		stroke="currentColor"
		stroke-width="2"
		stroke-linecap="round"
		stroke-linejoin="round"
		aria-hidden="true"
		class={s.arrow()}
	>
		{#each ARROW as d (d)}<path {d} />{/each}
	</svg>
{/snippet}

<section data-slot="pricing-02" class={cn(s.root(), classProp)} {...rest}>
	<div class={s.inner()}>
		<div class={s.header()}>
			<div class={s.heading()}>
				{#if eyebrow}<p class={s.eyebrow()}>{eyebrow}</p>{/if}
				{#if title}<h2 class={s.title()}>{title}</h2>{/if}
			</div>
			<div class={s.aside()}>
				{#if description}<p class={s.description()}>{description}</p>{/if}
				{#if periods.length > 1}
					<ToggleGroup
						type="single"
						size="sm"
						bind:value={() => current?.value ?? "", (v) => setPeriod(v as string)}
						label={l.period}
					>
						{#each periods as p (p.value)}
							<ToggleGroupItem value={p.value}>{p.label}</ToggleGroupItem>
						{/each}
					</ToggleGroup>
				{/if}
			</div>
		</div>

		<div class={s.plans()}>
			{#each plans as plan (plan.id)}
				{@const f = pricing02({ variant, featured: plan.featured ?? false })}
				{@const price = current ? (plan.prices[current.value] ?? "") : ""}
				{@const chars = [...price]}
				{@const label = plan.cta ?? `${l.choose} ${plan.name}`}
				{@const buttonVariant = plan.featured ? "default" : "outline"}
				<Card class={s.plan()}>
					<div aria-hidden="true" class={s.glow()}></div>
					<div class={f.panel()}>
						<p class={s.name()}>{plan.name}</p>
						{#if plan.description}<p class={s.blurb()}>{plan.description}</p>{/if}
						<div class={s.price()}>
							<span class="sr-only">{price}</span>
							<span aria-hidden="true" class={s.amount()} style:--digit-dir={currentIndex > 0 ? 1 : -1}>
								{#key current?.value}
									{#each chars as char, i (i)}
										<span
											data-animate={moved ? "" : undefined}
											class={s.digit()}
											style:--digit-delay={digitDelay(i, chars.length)}>{char}</span
										>
									{/each}
								{/key}
							</span>
							{#if current}<span class={s.cadence()}>{current.cadence}</span>{/if}
						</div>
						{#if plan.href !== undefined}
							<Button href={plan.href} variant={buttonVariant} class={s.cta()}>
								{label}
								{@render arrow()}
							</Button>
						{:else if onSelect}
							<Button
								variant={buttonVariant}
								class={s.cta()}
								onclick={() => onSelect?.(plan.id, current?.value ?? "")}
							>
								{label}
								{@render arrow()}
							</Button>
						{/if}
					</div>
					<div class={s.list()}>
						{#if plan.featuresLabel}<p class={s.listLabel()}>{plan.featuresLabel}</p>{/if}
						<ul class={s.features()}>
							{#each plan.features as feature (feature)}
								<li class={s.feature()}>
									<span class={s.tick()}>
										<svg
											viewBox="0 0 24 24"
											fill="none"
											stroke="currentColor"
											stroke-width="2"
											stroke-linecap="round"
											stroke-linejoin="round"
											aria-hidden="true"
											class="size-3"
										>
											<path d="M5 12l5 5l10 -10" />
										</svg>
									</span>
									{feature}
								</li>
							{/each}
						</ul>
					</div>
				</Card>
			{/each}
		</div>

		{#if footnotes?.length}
			<div class={s.footnotes()}>
				{#each footnotes as note (note)}<p>{note}</p>{/each}
			</div>
		{/if}
	</div>
</section>

// packages/ui-react/src/pricing-02/pricing-02.tsx
"use client";

import { type CSSProperties, type HTMLAttributes, useRef, useState } from "react";
import { Button } from "../button/button";
import { Card } from "../card/card";
import { cn } from "../lib/cn";
import { ToggleGroup, ToggleGroupItem } from "../toggle-group/toggle-group";
import {
	digitDelay,
	PRICING_02_LABELS,
	type Pricing02Labels,
	type Pricing02Period,
	type Pricing02Plan,
} from "./types";
import { type Pricing02Variant, pricing02 } from "./variants";

export type { Pricing02Labels, Pricing02Period, Pricing02Plan, Pricing02Variant };

export interface Pricing02Props
	extends Omit<HTMLAttributes<HTMLElement>, "title" | "onSelect"> {
	plans: Pricing02Plan[];
	/** Billing periods; the toggle shows when there are two or more. */
	periods: Pricing02Period[];
	period?: string;
	defaultPeriod?: string;
	onPeriodChange?: (period: string) => void;
	/** Called by a plan's button when the plan has no `href`. */
	onSelect?: (planId: string, period: string) => void;
	eyebrow?: string;
	/** Line breaks in the string are kept. */
	title?: string;
	description?: string;
	/** Small print under the plans. */
	footnotes?: string[];
	variant?: Pricing02Variant;
	labels?: Partial<Pricing02Labels>;
}

function Icon({ paths, className }: { paths: string[]; className?: string }) {
	return (
		<svg
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth={2}
			strokeLinecap="round"
			strokeLinejoin="round"
			aria-hidden
			className={className}
		>
			{paths.map((d) => (
				<path key={d} d={d} />
			))}
		</svg>
	);
}

const ARROW = ["M5 12l14 0", "M13 18l6 -6", "M13 6l6 6"];
const CHECK = ["M5 12l5 5l10 -10"];

export function Pricing02({
	plans,
	periods,
	period: periodProp,
	defaultPeriod,
	onPeriodChange,
	onSelect,
	eyebrow,
	title,
	description,
	footnotes,
	variant = "soft",
	labels,
	className,
	...props
}: Pricing02Props) {
	const [internal, setInternal] = useState(defaultPeriod ?? periods[0]?.value ?? "");
	const period = periodProp ?? internal;
	const currentIndex = Math.max(
		0,
		periods.findIndex((p) => p.value === period),
	);
	const current = periods[currentIndex];
	const l = { ...PRICING_02_LABELS, ...labels };
	const s = pricing02({ variant });

	// Digits only roll once the period has changed, never on first paint.
	const initial = useRef(current?.value);
	const moved = useRef(false);
	if (current?.value !== initial.current) moved.current = true;

	function setPeriod(next: string) {
		if (!next) return;
		if (periodProp === undefined) setInternal(next);
		onPeriodChange?.(next);
	}

	return (
		<section data-slot="pricing-02" className={cn(s.root(), className)} {...props}>
			<div className={s.inner()}>
				<div className={s.header()}>
					<div className={s.heading()}>
						{eyebrow ? <p className={s.eyebrow()}>{eyebrow}</p> : null}
						{title ? <h2 className={s.title()}>{title}</h2> : null}
					</div>
					<div className={s.aside()}>
						{description ? <p className={s.description()}>{description}</p> : null}
						{periods.length > 1 ? (
							<ToggleGroup
								type="single"
								size="sm"
								value={current?.value ?? ""}
								onValueChange={(next) => setPeriod(next as string)}
								label={l.period}
							>
								{periods.map((p) => (
									<ToggleGroupItem key={p.value} value={p.value}>
										{p.label}
									</ToggleGroupItem>
								))}
							</ToggleGroup>
						) : null}
					</div>
				</div>

				<div className={s.plans()}>
					{plans.map((plan) => {
						const f = pricing02({ variant, featured: plan.featured ?? false });
						const price = current ? (plan.prices[current.value] ?? "") : "";
						const chars = [...price];
						const label = plan.cta ?? `${l.choose} ${plan.name}`;
						const buttonVariant = plan.featured ? "default" : "outline";
						return (
							<Card key={plan.id} className={s.plan()}>
								<div aria-hidden className={s.glow()} />
								<div className={f.panel()}>
									<p className={s.name()}>{plan.name}</p>
									{plan.description ? (
										<p className={s.blurb()}>{plan.description}</p>
									) : null}
									<div className={s.price()}>
										<span className="sr-only">{price}</span>
										<span
											aria-hidden
											className={s.amount()}
											style={
												{ "--digit-dir": currentIndex > 0 ? 1 : -1 } as CSSProperties
											}
										>
											{chars.map((char, i) => (
												<span
													key={`${current?.value}-${i}-${char}`}
													data-animate={moved.current ? "" : undefined}
													className={s.digit()}
													style={
														{
															"--digit-delay": digitDelay(i, chars.length),
														} as CSSProperties
													}
												>
													{char}
												</span>
											))}
										</span>
										{current ? (
											<span className={s.cadence()}>{current.cadence}</span>
										) : null}
									</div>
									{plan.href !== undefined ? (
										<Button href={plan.href} variant={buttonVariant} className={s.cta()}>
											{label}
											<Icon paths={ARROW} className={s.arrow()} />
										</Button>
									) : onSelect ? (
										<Button
											variant={buttonVariant}
											className={s.cta()}
											onClick={() => onSelect(plan.id, current?.value ?? "")}
										>
											{label}
											<Icon paths={ARROW} className={s.arrow()} />
										</Button>
									) : null}
								</div>
								<div className={s.list()}>
									{plan.featuresLabel ? (
										<p className={s.listLabel()}>{plan.featuresLabel}</p>
									) : null}
									<ul className={s.features()}>
										{plan.features.map((feature) => (
											<li key={feature} className={s.feature()}>
												<span className={s.tick()}>
													<Icon paths={CHECK} className="size-3" />
												</span>
												{feature}
											</li>
										))}
									</ul>
								</div>
							</Card>
						);
					})}
				</div>

				{footnotes?.length ? (
					<div className={s.footnotes()}>
						{footnotes.map((note) => (
							<p key={note}>{note}</p>
						))}
					</div>
				) : null}
			</div>
		</section>
	);
}
