// packages/ui-react/src/underline-hover-text/underline-hover-text.tsx
import type { CSSProperties } from "react";
import { cn } from "../lib/cn";
import { type UnderlineHoverTextTone, underlineHoverText } from "./variants";

export type { UnderlineHoverTextTone };

export interface UnderlineHoverTextProps {
	text: string;
	tone?: UnderlineHoverTextTone;
	/** How long the lift and stroke take, in ms. */
	durationMs?: number;
	className?: string;
}

export function UnderlineHoverText({
	text,
	tone = "default",
	durationMs = 500,
	className,
}: UnderlineHoverTextProps) {
	const { root, label, baseline, stroke } = underlineHoverText({ tone });
	return (
		<span
			data-slot="underline-hover-text"
			className={cn(root(), className)}
			style={{ "--uht-duration": `${durationMs}ms` } as CSSProperties}
		>
			<span className={label()}>{text}</span>
			<span aria-hidden className={baseline()} />
			<span aria-hidden className={stroke()} />
		</span>
	);
}

// packages/ui-svelte/src/lib/underline-hover-text/underline-hover-text.svelte
<script lang="ts">
import { cn } from "../lib/cn";
import { type UnderlineHoverTextTone, underlineHoverText } from "./variants";

let {
	text,
	tone = "default",
	durationMs = 500,
	class: classProp,
}: {
	text: string;
	tone?: UnderlineHoverTextTone;
	/** How long the lift and stroke take, in ms. */
	durationMs?: number;
	class?: string;
} = $props();

const classes = $derived(underlineHoverText({ tone }));
</script>

<span data-slot="underline-hover-text" class={cn(classes.root(), classProp)} style="--uht-duration: {durationMs}ms;">
	<span class={classes.label()}>{text}</span>
	<span aria-hidden="true" class={classes.baseline()}></span>
	<span aria-hidden="true" class={classes.stroke()}></span>
</span>
