// packages/ui-svelte/src/lib/mega-navbar/mega-navbar.svelte
<script lang="ts">
import type { Snippet } from "svelte";
import Collapsible from "../collapsible/collapsible.svelte";
import CollapsibleContent from "../collapsible/collapsible-content.svelte";
import { cn } from "../lib/cn";
import NotchedShelf from "../notched-shelf/notched-shelf.svelte";
import Sheet from "../sheet/sheet.svelte";
import SheetContent from "../sheet/sheet-content.svelte";
import SheetHeader from "../sheet/sheet-header.svelte";
import SheetTitle from "../sheet/sheet-title.svelte";
import type { MegaMenuGroup, MegaNavLink } from "./types";
import { type MegaNavbarVariant, megaNavbar } from "./variants";

let {
	brand,
	groups,
	links = [],
	actions,
	mobileActions,
	active,
	sticky = true,
	blur = true,
	variant = "solid",
	class: className,
}: {
	brand?: Snippet;
	groups: MegaMenuGroup[];
	links?: MegaNavLink[];
	actions?: Snippet;
	mobileActions?: Snippet;
	active?: string;
	sticky?: boolean;
	blur?: boolean;
	variant?: MegaNavbarVariant;
	class?: string;
} = $props();

function isCurrent(href: string) {
	if (!active) return false;
	return active === href || active.startsWith(`${href}/`);
}

let scrolled = $state(false);
const styles = $derived(
	megaNavbar({
		variant,
		sticky,
		surface: scrolled ? (blur ? "blurred" : "opaque") : "clear",
	}),
);
let mobileOpen = $state(false);
let openDesktopGroup = $state(-1);
let openMobileGroup = $state(0);
let box = $state({ width: 0, height: 0, left: 0 });

let row: HTMLDivElement | undefined = $state();
let panels: (HTMLDivElement | undefined)[] = $state([]);
let triggers: (HTMLButtonElement | undefined)[] = $state([]);
let closeTimer: ReturnType<typeof setTimeout> | null = null;

function measure() {
	if (openDesktopGroup < 0 || !row) return;
	const panel = panels[openDesktopGroup];
	const trigger = triggers[openDesktopGroup];
	if (!panel || !trigger) return;
	const rowRect = row.getBoundingClientRect();
	const triggerRect = trigger.getBoundingClientRect();
	const width = panel.scrollWidth;
	const ideal = triggerRect.left - rowRect.left + triggerRect.width / 2 - width / 2;
	box = { width, height: panel.scrollHeight, left: Math.max(0, ideal) };
}

$effect(() => {
	void openDesktopGroup;
	measure();
});

function cancelClose() {
	if (closeTimer) clearTimeout(closeTimer);
	closeTimer = null;
}
function scheduleClose() {
	cancelClose();
	closeTimer = setTimeout(() => (openDesktopGroup = -1), 140);
}

// Navigating from inside the sheet should leave it closed.
$effect(() => {
	void active;
	mobileOpen = false;
});

const footerActions = $derived(mobileActions ?? actions);
// The notched shelf drops its panel a little further, clearing the wing curve.
const drop = $derived(variant === "notched" ? 10 : 8);
</script>

<svelte:window
	onscroll={() => {
		if (sticky) scrolled = window.scrollY > 8;
	}}
	onresize={measure}
/>

{#snippet chevronDown(cls: string)}
	<svg viewBox="0 0 16 16" fill="none" aria-hidden="true" class={cls}>
		<path d="m4 6 4 4 4-4" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" />
	</svg>
{/snippet}

{#snippet arrowUpRight(cls: string)}
	<svg viewBox="0 0 16 16" fill="none" aria-hidden="true" class={cls}>
		<path d="M5 11 11 5M6 5h5v5" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" />
	</svg>
{/snippet}

{#snippet arrowRight(cls: string)}
	<svg viewBox="0 0 16 16" fill="none" aria-hidden="true" class={cls}>
		<path d="M3 8h10M9 4l4 4-4 4" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" />
	</svg>
{/snippet}

{#snippet brandSlot()}
	{#if brand}
		<span class="flex shrink-0 items-center gap-2.5 py-1 pr-2">{@render brand()}</span>
	{/if}
{/snippet}

{#snippet desktopMenu()}
	<div
		bind:this={row}
		class="relative hidden items-center gap-1 @3xl:flex"
		onmouseleave={scheduleClose}
		onmouseenter={cancelClose}
		role="presentation"
	>
		{#each groups as group, i (group.label)}
			{@const isOpen = openDesktopGroup === i}
			<button
				bind:this={triggers[i]}
				type="button"
				aria-expanded={isOpen}
				aria-controls="mega-navbar-panel"
				onmouseenter={() => {
					cancelClose();
					openDesktopGroup = i;
				}}
				onfocus={() => {
					cancelClose();
					openDesktopGroup = i;
				}}
				onclick={() => (openDesktopGroup = openDesktopGroup === i ? -1 : i)}
				onkeydown={(e) => {
					if (e.key === "Escape") {
						openDesktopGroup = -1;
						triggers[i]?.focus();
					} else if (e.key === "ArrowDown") {
						e.preventDefault();
						cancelClose();
						openDesktopGroup = i;
						// The pane is inert until the open state renders.
						requestAnimationFrame(() => panels[i]?.querySelector("a")?.focus());
					}
				}}
				class={styles.trigger({ current: isOpen || isCurrent(group.href) })}
			>
				{group.label}
				{@render chevronDown(styles.chevron({ open: isOpen }))}
			</button>
		{/each}

		<div
			id="mega-navbar-panel"
			aria-hidden={openDesktopGroup < 0}
			onmouseenter={cancelClose}
			onmouseleave={scheduleClose}
			onkeydown={(e) => {
				if (e.key !== "Escape" || openDesktopGroup < 0) return;
				triggers[openDesktopGroup]?.focus();
				openDesktopGroup = -1;
			}}
			role="presentation"
			class={styles.panel({ open: openDesktopGroup >= 0 })}
			style="width:{box.width}px;height:{box.height}px;transform:translate3d({box.left}px, {openDesktopGroup >= 0 ? drop : 2}px, 0) scale({openDesktopGroup >= 0 ? 1 : 0.98});"
		>
			{#each groups as group, i (group.label)}
				{@const isOpen = openDesktopGroup === i}
				<div
					bind:this={panels[i]}
					inert={!isOpen}
					class={styles.pane({ open: isOpen })}
				>
					<ul class={styles.list()}>
						{#each group.items as item (item.href)}
							<li>
								<a
									href={item.href}
									target={item.external ? "_blank" : undefined}
									rel={item.external ? "noreferrer" : undefined}
									onclick={() => (openDesktopGroup = -1)}
									aria-current={isCurrent(item.href) ? "page" : undefined}
									class="flex gap-3 rounded-lg p-3 transition-colors hover:bg-foreground/[0.06] aria-[current=page]:bg-foreground/[0.06] motion-reduce:transition-none"
								>
									{#if item.icon}
										<span class="mt-0.5 shrink-0 text-muted-foreground [&_svg]:size-4">
											{@render item.icon()}
										</span>
									{/if}
									<span class="min-w-0">
										<span class="flex items-center gap-1 font-medium text-foreground text-sm">
											{item.label}
											{#if item.external}
												{@render arrowUpRight("size-3 text-muted-foreground")}
											{/if}
										</span>
										{#if item.description}
											<span class="mt-0.5 block text-muted-foreground text-xs">{item.description}</span>
										{/if}
									</span>
								</a>
							</li>
						{/each}
					</ul>
					{#if group.footer}
						<a
							href={group.footer.href}
							onclick={() => (openDesktopGroup = -1)}
							class="group/cta flex items-center justify-between gap-4 border-border border-t bg-foreground/[0.02] px-5 py-3 transition-colors hover:bg-foreground/[0.06] motion-reduce:transition-none"
						>
							<span class="font-medium text-foreground text-sm">{group.footer.label}</span>
							<span class="flex items-center gap-1.5 text-muted-foreground text-xs">
								{group.footer.hint}
								{@render arrowRight("size-3.5 transition-transform group-hover/cta:translate-x-0.5 motion-reduce:transition-none")}
							</span>
						</a>
					{/if}
				</div>
			{/each}
		</div>
	</div>
{/snippet}

{#snippet linkList()}
	<ul class="flex items-center gap-1">
		{#each links as link (link.href)}
			<li>
				<a
					href={link.href}
					target={link.external ? "_blank" : undefined}
					rel={link.external ? "noreferrer" : undefined}
					aria-current={isCurrent(link.href) ? "page" : undefined}
					class={styles.link({ current: isCurrent(link.href) })}
				>
					{link.label}
				</a>
			</li>
		{/each}
	</ul>
{/snippet}

{#snippet menuButton()}
	<button
		type="button"
		onclick={() => (mobileOpen = true)}
		aria-expanded={mobileOpen}
		aria-label="Open menu"
		class={styles.menuButton()}
	>
		<svg viewBox="0 0 16 16" fill="none" aria-hidden="true" class="size-5">
			<path d="M2 4.5h12M2 8h12M2 11.5h12" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" />
		</svg>
	</button>
{/snippet}

<div data-slot="mega-navbar" data-variant={variant} class={cn(styles.root(), className)}>
	{#if variant === "notched"}
		<nav aria-label="Primary">
			<div class={styles.shelf()}>
				<NotchedShelf size="lg" fill="text-card">
					<div class={styles.shelfBar()}>
						{@render brandSlot()}
						{@render desktopMenu()}
						{@render linkList()}
						{#if actions}
							<span class="flex items-center gap-2">{@render actions()}</span>
						{/if}
					</div>
				</NotchedShelf>
			</div>
			<div class={styles.mobileBar()}>
				{@render brandSlot()}
				{@render menuButton()}
			</div>
			<span aria-hidden="true" class={styles.rule()}></span>
		</nav>
	{:else}
		<nav aria-label="Primary" class={styles.nav()}>
			{@render brandSlot()}
			<div class="hidden flex-1 items-center justify-center @3xl:flex">
				{@render desktopMenu()}
				{@render linkList()}
			</div>
			<div class="ml-auto flex shrink-0 items-center gap-2 @3xl:ml-0">
				{#if actions}
					<span class="hidden items-center gap-2 @3xl:flex">{@render actions()}</span>
				{/if}
				{@render menuButton()}
			</div>
		</nav>
	{/if}
</div>

<Sheet bind:open={mobileOpen}>
	<SheetContent side={variant === "notched" ? "top" : "right"} class={styles.sheet()}>
		<SheetHeader class="border-border border-b px-5 py-4">
			<SheetTitle class="flex items-center gap-2.5">
				{#if brand}{@render brand()}{/if}
			</SheetTitle>
		</SheetHeader>
		<nav aria-label="Mobile" class="flex-1 overflow-y-auto px-3 py-3">
			{#each groups as group, i (group.label)}
				{@const isOpen = openMobileGroup === i}
				<Collapsible
					open={isOpen}
					class="border-border border-b last:border-b-0"
				>
					<button
						type="button"
						aria-expanded={isOpen}
						onclick={() => (openMobileGroup = openMobileGroup === i ? -1 : i)}
						class="flex min-h-12 w-full items-center justify-between gap-4 px-2 text-left font-medium text-foreground"
					>
						{group.label}
						{@render chevronDown(styles.mobileChevron({ open: isOpen }))}
					</button>
					<CollapsibleContent class="px-0 pb-2">
						<ul>
							{#each group.items as item (item.href)}
								<li>
									<a
										href={item.href}
										target={item.external ? "_blank" : undefined}
										rel={item.external ? "noreferrer" : undefined}
										onclick={() => (mobileOpen = false)}
										aria-current={isCurrent(item.href) ? "page" : undefined}
										class={styles.mobileItem({ current: isCurrent(item.href) })}
									>
										{#if item.icon}
											<span class="shrink-0 text-muted-foreground [&_svg]:size-4">
												{@render item.icon()}
											</span>
										{/if}
										<span class="min-w-0 flex-1">
											<span class="flex items-center gap-1 font-medium text-foreground text-sm">
												{item.label}
												{#if item.external}
													{@render arrowUpRight("size-3 text-muted-foreground")}
												{/if}
											</span>
											{#if item.description}
												<span class="mt-0.5 block text-muted-foreground text-xs">{item.description}</span>
											{/if}
										</span>
									</a>
								</li>
							{/each}
						</ul>
					</CollapsibleContent>
				</Collapsible>
			{/each}
			<ul class="mt-1 pt-1">
				{#each links as link (link.href)}
					<li>
						<a
							href={link.href}
							target={link.external ? "_blank" : undefined}
							rel={link.external ? "noreferrer" : undefined}
							onclick={() => (mobileOpen = false)}
							aria-current={isCurrent(link.href) ? "page" : undefined}
							class={styles.mobileLink({ current: isCurrent(link.href) })}
						>
							{link.label}
						</a>
					</li>
				{/each}
			</ul>
		</nav>
		{#if footerActions}
			<div class="mt-auto flex flex-col gap-2 border-border border-t px-5 py-4">
				{@render footerActions()}
			</div>
		{/if}
	</SheetContent>
</Sheet>

// packages/ui-react/src/mega-navbar/mega-navbar.tsx
"use client";

import type { ReactNode } from "react";
import { useEffect, useRef, useState } from "react";
import { Collapsible, CollapsibleContent } from "../collapsible/collapsible";
import { cn } from "../lib/cn";
import { NotchedShelf } from "../notched-shelf/notched-shelf";
import { Sheet, SheetContent, SheetHeader, SheetTitle } from "../sheet/sheet";
import { type MegaNavbarVariant, megaNavbar } from "./variants";

export type { MegaNavbarVariant };

export type MegaNavLink = { label: string; href: string; external?: boolean };

export type MegaMenuItem = {
	label: string;
	href: string;
	description?: string;
	icon?: ReactNode;
	external?: boolean;
};

export type MegaMenuGroup = {
	label: string;
	href: string;
	items: MegaMenuItem[];
	footer?: { label: string; href: string; hint?: string };
};

function ChevronDown({ className }: { className?: string }) {
	return (
		<svg viewBox="0 0 16 16" fill="none" aria-hidden className={className}>
			<path
				d="m4 6 4 4 4-4"
				stroke="currentColor"
				strokeWidth="1.6"
				strokeLinecap="round"
				strokeLinejoin="round"
			/>
		</svg>
	);
}

function ArrowUpRight({ className }: { className?: string }) {
	return (
		<svg viewBox="0 0 16 16" fill="none" aria-hidden className={className}>
			<path
				d="M5 11 11 5M6 5h5v5"
				stroke="currentColor"
				strokeWidth="1.6"
				strokeLinecap="round"
				strokeLinejoin="round"
			/>
		</svg>
	);
}

function ArrowRight({ className }: { className?: string }) {
	return (
		<svg viewBox="0 0 16 16" fill="none" aria-hidden className={className}>
			<path
				d="M3 8h10M9 4l4 4-4 4"
				stroke="currentColor"
				strokeWidth="1.6"
				strokeLinecap="round"
				strokeLinejoin="round"
			/>
		</svg>
	);
}

function MenuIcon({ className }: { className?: string }) {
	return (
		<svg viewBox="0 0 16 16" fill="none" aria-hidden className={className}>
			<path
				d="M2 4.5h12M2 8h12M2 11.5h12"
				stroke="currentColor"
				strokeWidth="1.6"
				strokeLinecap="round"
			/>
		</svg>
	);
}

function isCurrent(href: string, active?: string) {
	if (!active) return false;
	return active === href || active.startsWith(`${href}/`);
}

/** Every trigger and panel share one measured box, so the panel morphs between
 * groups instead of a fresh popover mounting per item. */
function DesktopMegaMenu({
	groups,
	active,
	variant,
}: {
	groups: MegaMenuGroup[];
	active?: string;
	variant: MegaNavbarVariant;
}) {
	const [open, setOpen] = useState(-1);
	const styles = megaNavbar({ variant });
	// The notched shelf drops its panel a little further, clearing the wing curve.
	const drop = variant === "notched" ? 10 : 8;
	const [box, setBox] = useState({ width: 0, height: 0, left: 0 });
	const row = useRef<HTMLDivElement>(null);
	const panels = useRef<(HTMLDivElement | null)[]>([]);
	const triggers = useRef<(HTMLButtonElement | null)[]>([]);
	const closeTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

	function measure(index: number) {
		const rowEl = row.current;
		const panel = panels.current[index];
		const trigger = triggers.current[index];
		if (!rowEl || !panel || !trigger) return;
		const rowRect = rowEl.getBoundingClientRect();
		const triggerRect = trigger.getBoundingClientRect();
		const width = panel.scrollWidth;
		const ideal = triggerRect.left - rowRect.left + triggerRect.width / 2 - width / 2;
		setBox({ width, height: panel.scrollHeight, left: Math.max(0, ideal) });
	}

	useEffect(() => {
		if (open < 0) return;
		measure(open);
		const onResize = () => measure(open);
		window.addEventListener("resize", onResize);
		return () => window.removeEventListener("resize", onResize);
	}, [open]);

	function cancelClose() {
		if (closeTimer.current) clearTimeout(closeTimer.current);
		closeTimer.current = null;
	}
	function scheduleClose() {
		cancelClose();
		closeTimer.current = setTimeout(() => setOpen(-1), 140);
	}

	return (
		// biome-ignore lint/a11y/noStaticElementInteractions: hover region only; the triggers and links inside are the real controls
		<div
			ref={row}
			className="relative hidden items-center gap-1 @3xl:flex"
			onMouseLeave={scheduleClose}
			onMouseEnter={cancelClose}
		>
			{groups.map((group, index) => {
				const isOpen = open === index;
				return (
					<button
						key={group.label}
						ref={(el) => {
							triggers.current[index] = el;
						}}
						type="button"
						aria-expanded={isOpen}
						aria-controls="mega-navbar-panel"
						onMouseEnter={() => {
							cancelClose();
							setOpen(index);
						}}
						onFocus={() => {
							cancelClose();
							setOpen(index);
						}}
						onClick={() => setOpen((current) => (current === index ? -1 : index))}
						onKeyDown={(event) => {
							if (event.key === "Escape") {
								setOpen(-1);
								triggers.current[index]?.focus();
							} else if (event.key === "ArrowDown") {
								event.preventDefault();
								cancelClose();
								setOpen(index);
								// The pane is inert until the open state renders.
								requestAnimationFrame(() =>
									panels.current[index]?.querySelector<HTMLElement>("a")?.focus(),
								);
							}
						}}
						className={styles.trigger({
							current: isOpen || isCurrent(group.href, active),
						})}
					>
						{group.label}
						<ChevronDown className={styles.chevron({ open: isOpen })} />
					</button>
				);
			})}

			<div
				id="mega-navbar-panel"
				aria-hidden={open < 0}
				onMouseEnter={cancelClose}
				onMouseLeave={scheduleClose}
				onKeyDown={(event) => {
					if (event.key !== "Escape" || open < 0) return;
					triggers.current[open]?.focus();
					setOpen(-1);
				}}
				className={styles.panel({ open: open >= 0 })}
				style={{
					width: box.width,
					height: box.height,
					transform: `translate3d(${box.left}px, ${open >= 0 ? drop : 2}px, 0) scale(${open >= 0 ? 1 : 0.98})`,
				}}
			>
				{groups.map((group, index) => {
					const isOpen = open === index;
					return (
						<div
							key={group.label}
							ref={(el) => {
								panels.current[index] = el;
							}}
							inert={!isOpen}
							className={styles.pane({ open: isOpen })}
						>
							<ul className={styles.list()}>
								{group.items.map((item) => (
									<li key={item.href}>
										<a
											href={item.href}
											target={item.external ? "_blank" : undefined}
											rel={item.external ? "noreferrer" : undefined}
											onClick={() => setOpen(-1)}
											aria-current={isCurrent(item.href, active) ? "page" : undefined}
											className="flex gap-3 rounded-lg p-3 transition-colors hover:bg-foreground/[0.06] aria-[current=page]:bg-foreground/[0.06] motion-reduce:transition-none"
										>
											{item.icon ? (
												<span className="mt-0.5 shrink-0 text-muted-foreground [&_svg]:size-4">
													{item.icon}
												</span>
											) : null}
											<span className="min-w-0">
												<span className="flex items-center gap-1 font-medium text-foreground text-sm">
													{item.label}
													{item.external ? (
														<ArrowUpRight className="size-3 text-muted-foreground" />
													) : null}
												</span>
												{item.description ? (
													<span className="mt-0.5 block text-muted-foreground text-xs">
														{item.description}
													</span>
												) : null}
											</span>
										</a>
									</li>
								))}
							</ul>
							{group.footer ? (
								<a
									href={group.footer.href}
									onClick={() => setOpen(-1)}
									className="group/cta flex items-center justify-between gap-4 border-border border-t bg-foreground/[0.02] px-5 py-3 transition-colors hover:bg-foreground/[0.06] motion-reduce:transition-none"
								>
									<span className="font-medium text-foreground text-sm">
										{group.footer.label}
									</span>
									<span className="flex items-center gap-1.5 text-muted-foreground text-xs">
										{group.footer.hint}
										<ArrowRight className="size-3.5 transition-transform group-hover/cta:translate-x-0.5 motion-reduce:transition-none" />
									</span>
								</a>
							) : null}
						</div>
					);
				})}
			</div>
		</div>
	);
}

function MobileNav({
	open,
	onOpenChange,
	brand,
	groups,
	links,
	actions,
	active,
	variant,
}: {
	open: boolean;
	onOpenChange: (open: boolean) => void;
	brand?: ReactNode;
	groups: MegaMenuGroup[];
	links: MegaNavLink[];
	actions?: ReactNode;
	active?: string;
	variant: MegaNavbarVariant;
}) {
	const [openGroup, setOpenGroup] = useState(0);
	const styles = megaNavbar({ variant });

	return (
		<Sheet open={open} onOpenChange={onOpenChange}>
			<SheetContent
				side={variant === "notched" ? "top" : "right"}
				className={styles.sheet()}
			>
				<SheetHeader className="border-border border-b px-5 py-4">
					<SheetTitle className="flex items-center gap-2.5">{brand}</SheetTitle>
				</SheetHeader>
				<nav aria-label="Mobile" className="flex-1 overflow-y-auto px-3 py-3">
					{groups.map((group, index) => {
						const isOpen = openGroup === index;
						return (
							<Collapsible
								key={group.label}
								open={isOpen}
								className="border-border border-b last:border-b-0"
							>
								<button
									type="button"
									aria-expanded={isOpen}
									onClick={() =>
										setOpenGroup((current) => (current === index ? -1 : index))
									}
									className="flex min-h-12 w-full items-center justify-between gap-4 px-2 text-left font-medium text-foreground"
								>
									{group.label}
									<ChevronDown className={styles.mobileChevron({ open: isOpen })} />
								</button>
								<CollapsibleContent className="px-0 pb-2">
									<ul>
										{group.items.map((item) => (
											<li key={item.href}>
												<a
													href={item.href}
													target={item.external ? "_blank" : undefined}
													rel={item.external ? "noreferrer" : undefined}
													onClick={() => onOpenChange(false)}
													aria-current={isCurrent(item.href, active) ? "page" : undefined}
													className={styles.mobileItem({
														current: isCurrent(item.href, active),
													})}
												>
													{item.icon ? (
														<span className="shrink-0 text-muted-foreground [&_svg]:size-4">
															{item.icon}
														</span>
													) : null}
													<span className="min-w-0 flex-1">
														<span className="flex items-center gap-1 font-medium text-foreground text-sm">
															{item.label}
															{item.external ? (
																<ArrowUpRight className="size-3 text-muted-foreground" />
															) : null}
														</span>
														{item.description ? (
															<span className="mt-0.5 block text-muted-foreground text-xs">
																{item.description}
															</span>
														) : null}
													</span>
												</a>
											</li>
										))}
									</ul>
								</CollapsibleContent>
							</Collapsible>
						);
					})}
					<ul className="mt-1 pt-1">
						{links.map((link) => (
							<li key={link.href}>
								<a
									href={link.href}
									target={link.external ? "_blank" : undefined}
									rel={link.external ? "noreferrer" : undefined}
									onClick={() => onOpenChange(false)}
									aria-current={isCurrent(link.href, active) ? "page" : undefined}
									className={styles.mobileLink({ current: isCurrent(link.href, active) })}
								>
									{link.label}
								</a>
							</li>
						))}
					</ul>
				</nav>
				{actions ? (
					<div className="mt-auto flex flex-col gap-2 border-border border-t px-5 py-4">
						{actions}
					</div>
				) : null}
			</SheetContent>
		</Sheet>
	);
}

export interface MegaNavbarProps {
	brand?: ReactNode;
	groups: MegaMenuGroup[];
	links?: MegaNavLink[];
	actions?: ReactNode;
	mobileActions?: ReactNode;
	active?: string;
	sticky?: boolean;
	blur?: boolean;
	variant?: MegaNavbarVariant;
	className?: string;
}

export function MegaNavbar({
	brand,
	groups,
	links = [],
	actions,
	mobileActions,
	active,
	sticky = true,
	blur = true,
	variant = "solid",
	className,
}: MegaNavbarProps) {
	const [scrolled, setScrolled] = useState(false);
	const [mobileOpen, setMobileOpen] = useState(false);

	useEffect(() => {
		if (!sticky) return;
		const onScroll = () => setScrolled(window.scrollY > 8);
		onScroll();
		window.addEventListener("scroll", onScroll, { passive: true });
		return () => window.removeEventListener("scroll", onScroll);
	}, [sticky]);

	// Navigating from inside the sheet should leave it closed.
	useEffect(() => {
		setMobileOpen(false);
	}, [active]);

	const styles = megaNavbar({
		variant,
		sticky,
		surface: scrolled ? (blur ? "blurred" : "opaque") : "clear",
	});

	const brandSlot = brand ? (
		<span className="flex shrink-0 items-center gap-2.5 py-1 pr-2">{brand}</span>
	) : null;
	const linkList = (
		<ul className="flex items-center gap-1">
			{links.map((link) => (
				<li key={link.href}>
					<a
						href={link.href}
						target={link.external ? "_blank" : undefined}
						rel={link.external ? "noreferrer" : undefined}
						aria-current={isCurrent(link.href, active) ? "page" : undefined}
						className={styles.link({ current: isCurrent(link.href, active) })}
					>
						{link.label}
					</a>
				</li>
			))}
		</ul>
	);
	const menuButton = (
		<button
			type="button"
			onClick={() => setMobileOpen(true)}
			aria-expanded={mobileOpen}
			aria-label="Open menu"
			className={styles.menuButton()}
		>
			<MenuIcon className="size-5" />
		</button>
	);

	return (
		<div
			data-slot="mega-navbar"
			data-variant={variant}
			className={cn(styles.root(), className)}
		>
			{variant === "notched" ? (
				<nav aria-label="Primary">
					<div className={styles.shelf()}>
						<NotchedShelf size="lg" fill="text-card">
							<div className={styles.shelfBar()}>
								{brandSlot}
								<DesktopMegaMenu groups={groups} active={active} variant={variant} />
								{linkList}
								{actions ? (
									<span className="flex items-center gap-2">{actions}</span>
								) : null}
							</div>
						</NotchedShelf>
					</div>
					<div className={styles.mobileBar()}>
						{brandSlot}
						{menuButton}
					</div>
					<span aria-hidden className={styles.rule()} />
				</nav>
			) : (
				<nav aria-label="Primary" className={styles.nav()}>
					{brandSlot}
					<div className="hidden flex-1 items-center justify-center @3xl:flex">
						<DesktopMegaMenu groups={groups} active={active} variant={variant} />
						{linkList}
					</div>
					<div className="ml-auto flex shrink-0 items-center gap-2 @3xl:ml-0">
						{actions ? (
							<span className="hidden items-center gap-2 @3xl:flex">{actions}</span>
						) : null}
						{menuButton}
					</div>
				</nav>
			)}

			<MobileNav
				open={mobileOpen}
				onOpenChange={setMobileOpen}
				brand={brand}
				groups={groups}
				links={links}
				actions={mobileActions ?? actions}
				active={active}
				variant={variant}
			/>
		</div>
	);
}
