// packages/ui-react/src/projection-line/projection-line.tsx
"use client";

import { useId, useLayoutEffect, useMemo } from "react";
import { seriesVisibleInPhase } from "../chart/core";
import { useExtentRegistry, usePlot } from "../chart/time-series";
import { cn } from "../lib/cn";
import {
	bezierPath,
	type ProjectionPoint,
	projectionExtent,
	visibleEndX,
} from "./geometry";
import {
	type ProjectionLineCurve,
	type ProjectionLineVariant,
	projectionLine,
} from "./variants";

export interface ProjectionLineProps {
	/** Anchor plus horizon, e.g. from `buildProjection`; the chart widens to fit it. */
	data: ProjectionPoint[];
	variant?: ProjectionLineVariant;
	curve?: ProjectionLineCurve;
	stroke?: string;
	/** End colour when `variant` is gradient. */
	gradientEnd?: string;
	strokeWidth?: number;
	endMarker?: boolean;
	endRadius?: number;
	className?: string;
}

export function ProjectionLine({
	data,
	variant = "dashed",
	curve = "linear",
	stroke = "var(--chart-3)",
	gradientEnd = "var(--chart-5)",
	strokeWidth = 2,
	endMarker = true,
	endRadius = 5,
	className,
}: ProjectionLineProps) {
	const { xScale, yScale, innerWidth, phase, clipId } = usePlot();
	const register = useExtentRegistry();
	const id = useId().replace(/:/g, "");
	const extent = useMemo(() => projectionExtent(data), [data]);
	const extentKey = extent ? `${extent.x.join()}|${extent.y.join()}` : "";

	useLayoutEffect(() => {
		if (!extent) return;
		return register(id, extent);
	}, [register, id, extentKey]);

	const start = data[0];
	const end = data.at(-1);
	if (!(start && end) || data.length < 2) return null;
	const x0 = xScale(start.date);
	const y0 = yScale(start.value);
	const x1 = visibleEndX(
		xScale(end.date),
		innerWidth,
		endMarker ? endRadius : 0,
		strokeWidth,
	);
	const y1 = yScale(end.value);
	const d = curve === "bezier" ? bezierPath(x0, y0, x1, y1) : `M${x0},${y0}L${x1},${y1}`;
	const drawn = seriesVisibleInPhase(phase);
	const color = variant === "gradient" ? `url(#${id}-g)` : stroke;
	const styles = projectionLine({ variant, curve });

	return (
		<g data-slot="chart-projection" className={className}>
			{variant === "gradient" ? (
				<defs>
					<linearGradient
						id={`${id}-g`}
						gradientUnits="userSpaceOnUse"
						x1={x0}
						x2={x1}
						y1={y0}
						y2={y1}
					>
						<stop offset="0%" stopColor={stroke} />
						<stop offset="100%" stopColor={gradientEnd} />
					</linearGradient>
				</defs>
			) : null}
			<g clipPath={`url(#${clipId})`}>
				<path
					d={d}
					className={cn(styles.line())}
					stroke={drawn ? color : "transparent"}
					strokeWidth={strokeWidth}
				/>
			</g>
			{endMarker ? (
				<circle
					data-slot="chart-projection-end"
					cx={x1}
					cy={y1}
					r={endRadius * 0.85}
					fill={variant === "gradient" ? gradientEnd : stroke}
					className={styles.marker()}
					style={{ opacity: phase === "ready" ? 1 : 0 }}
				/>
			) : null}
		</g>
	);
}

// packages/ui-svelte/src/lib/projection-line/projection-line.svelte
<svelte:options namespace="svg" />

<script lang="ts">
import { untrack } from "svelte";
import { usePlot } from "../chart/context";
import { seriesVisibleInPhase } from "../chart/core";
import { useExtentRegistry } from "../chart/time-series-chart.svelte";
import {
	bezierPath,
	type ProjectionPoint,
	projectionExtent,
	visibleEndX,
} from "./geometry";
import {
	type ProjectionLineCurve,
	type ProjectionLineVariant,
	projectionLine,
} from "./variants";

let {
	data,
	variant = "dashed",
	curve = "linear",
	stroke = "var(--chart-3)",
	gradientEnd = "var(--chart-5)",
	strokeWidth = 2,
	endMarker = true,
	endRadius = 5,
	class: className,
}: {
	/** Anchor plus horizon, e.g. from `buildProjection`; the chart widens to fit it. */
	data: ProjectionPoint[];
	variant?: ProjectionLineVariant;
	curve?: ProjectionLineCurve;
	stroke?: string;
	/** End colour when `variant` is gradient. */
	gradientEnd?: string;
	strokeWidth?: number;
	endMarker?: boolean;
	endRadius?: number;
	class?: string;
} = $props();

const plot = usePlot();
const register = useExtentRegistry();
const uid = $props.id();
const id = `${uid}-projection`;
const extent = $derived(projectionExtent(data));

$effect(() => {
	const next = extent;
	if (!next) return;
	return untrack(() => register(id, next));
});

const start = $derived(data[0]);
const end = $derived(data.at(-1));
const geometry = $derived.by(() => {
	if (!(start && end) || data.length < 2) return null;
	const x0 = plot.xScale(start.date);
	const y0 = plot.yScale(start.value);
	const x1 = visibleEndX(
		plot.xScale(end.date),
		plot.innerWidth,
		endMarker ? endRadius : 0,
		strokeWidth,
	);
	const y1 = plot.yScale(end.value);
	return {
		x0,
		y0,
		x1,
		y1,
		d: curve === "bezier" ? bezierPath(x0, y0, x1, y1) : `M${x0},${y0}L${x1},${y1}`,
	};
});
const drawn = $derived(seriesVisibleInPhase(plot.phase));
const styles = $derived(projectionLine({ variant, curve }));
const color = $derived(variant === "gradient" ? `url(#${id}-g)` : stroke);
</script>

{#if geometry}
	<g data-slot="chart-projection" class={className}>
		{#if variant === "gradient"}
			<defs>
				<linearGradient
					id="{id}-g"
					gradientUnits="userSpaceOnUse"
					x1={geometry.x0}
					x2={geometry.x1}
					y1={geometry.y0}
					y2={geometry.y1}
				>
					<stop offset="0%" stop-color={stroke} />
					<stop offset="100%" stop-color={gradientEnd} />
				</linearGradient>
			</defs>
		{/if}
		<g clip-path="url(#{plot.clipId})">
			<path
				d={geometry.d}
				class={styles.line()}
				stroke={drawn ? color : "transparent"}
				stroke-width={strokeWidth}
			/>
		</g>
		{#if endMarker}
			<circle
				data-slot="chart-projection-end"
				cx={geometry.x1}
				cy={geometry.y1}
				r={endRadius * 0.85}
				fill={variant === "gradient" ? gradientEnd : stroke}
				class={styles.marker()}
				style:opacity={plot.phase === "ready" ? 1 : 0}
			/>
		{/if}
	</g>
{/if}
