// packages/ui-react/src/click-spark/click-spark.tsx
"use client";

import { useEffect, useRef } from "react";
import { cn } from "../lib/cn";
import { createSparks } from "./sparks";
import { type ClickSparkScope, type ClickSparkTone, clickSpark } from "./variants";

export type { ClickSparkScope, ClickSparkTone };

export interface ClickSparkProps {
	tone?: ClickSparkTone;
	/** `page` covers the viewport; `parent` fills and listens on a positioned parent only. */
	scope?: ClickSparkScope;
	/** Lines per burst. */
	count?: number;
	/** Starting line length, px. */
	size?: number;
	/** How far the lines travel, px. */
	radius?: number;
	durationMs?: number;
	className?: string;
}

/** Mount once near the root for page-wide bursts, or inside a positioned box with `scope="parent"`. */
export function ClickSpark({
	tone = "foreground",
	scope = "page",
	count = 8,
	size = 10,
	radius = 15,
	durationMs = 400,
	className,
}: ClickSparkProps) {
	const canvasRef = useRef<HTMLCanvasElement>(null);
	const sparksRef = useRef<ReturnType<typeof createSparks>>(null);
	const options = { count, size, radius, durationMs };

	useEffect(() => {
		if (!canvasRef.current) return;
		const sparks = createSparks(canvasRef.current, scope, options);
		sparksRef.current = sparks;
		return () => sparks.destroy();
	}, [scope]);

	useEffect(() => {
		sparksRef.current?.update(options);
	});

	return (
		<canvas
			ref={canvasRef}
			data-slot="click-spark"
			className={cn(clickSpark({ tone, scope }), className)}
		/>
	);
}

// packages/ui-svelte/src/lib/click-spark/click-spark.svelte
<script lang="ts">
import { untrack } from "svelte";
import { cn } from "../lib/cn";
import { createSparks } from "./sparks";
import { type ClickSparkScope, type ClickSparkTone, clickSpark } from "./variants";

let {
	tone = "foreground",
	scope = "page",
	count = 8,
	size = 10,
	radius = 15,
	durationMs = 400,
	class: classProp,
}: {
	tone?: ClickSparkTone;
	/** `page` covers the viewport; `parent` fills and listens on a positioned parent only. */
	scope?: ClickSparkScope;
	/** Lines per burst. */
	count?: number;
	/** Starting line length, px. */
	size?: number;
	/** How far the lines travel, px. */
	radius?: number;
	durationMs?: number;
	class?: string;
} = $props();

let canvas: HTMLCanvasElement | undefined = $state();
let sparks: ReturnType<typeof createSparks> | undefined;
const options = $derived({ count, size, radius, durationMs });

$effect(() => {
	const el = canvas;
	const area = scope;
	if (!el) return;
	sparks = untrack(() => createSparks(el, area, options));
	return () => sparks?.destroy();
});

$effect(() => {
	sparks?.update(options);
});
</script>

<canvas
	bind:this={canvas}
	data-slot="click-spark"
	class={cn(clickSpark({ tone, scope }), classProp)}
></canvas>
