// packages/ui-svelte/src/lib/npm-stats/npm-stats.svelte
<script lang="ts">
import Empty from "../empty/empty.svelte";
import EmptyDescription from "../empty/empty-description.svelte";
import EmptyHeader from "../empty/empty-header.svelte";
import EmptyTitle from "../empty/empty-title.svelte";
import { cn } from "../lib/cn";
import RollingDigits from "../rolling-digits/rolling-digits.svelte";
import ToggleGroup from "../toggle-group/toggle-group.svelte";
import ToggleGroupItem from "../toggle-group/toggle-group-item.svelte";
import {
	combineTotals,
	formatChange,
	formatCompact,
	formatDayTick,
	formatWeekday,
	NPM_STATS_LABELS,
	type NpmPackage,
	type NpmStatsLabels,
	npmFacts,
	rangeTrend,
	trailingSum,
} from "./core";
import NpmDownloadsChart from "./downloads-chart.svelte";
import NpmPackageBreakdown from "./package-breakdown.svelte";
import TrendBadge from "./trend-badge.svelte";
import {
	NPM_STATS_LAYOUT,
	type NpmStatsRange,
	type NpmStatsVariant,
	npmStats,
} from "./variants";

let {
	packages,
	locale,
	labels: labelsProp,
	variant = "default",
	range = $bindable("30d"),
	onRangeChange,
	class: classProp,
}: {
	packages: NpmPackage[];
	locale?: string;
	labels?: Partial<NpmStatsLabels>;
	variant?: NpmStatsVariant;
	/** Bindable window the hero, facts, chart and packages show. */
	range?: NpmStatsRange;
	onRangeChange?: (range: NpmStatsRange) => void;
	class?: string;
} = $props();

const styles = $derived(npmStats({ variant }));
const layout = $derived(NPM_STATS_LAYOUT[variant]);
const labels = $derived({ ...NPM_STATS_LABELS, ...labelsProp });
const totals = $derived(combineTotals(packages));
const rows = $derived(range === "30d" ? totals.last30Days : totals.last90Days);
const periodTotal = $derived(rows.reduce((sum, row) => sum + row.total, 0));
const unit = $derived(range === "30d" ? labels.chartLast30 : labels.chartLast90);
const trend = $derived(
	rangeTrend(
		rows.map((row) => row.total),
		range,
	),
);
const facts = $derived(npmFacts(packages, range));
const compact = (value: number) => formatCompact(value, locale);

function setRange(next: string | string[]) {
	if (next !== "30d" && next !== "90d") return;
	range = next;
	onRangeChange?.(next);
}
</script>

{#snippet figure(value: number, className: string)}
	{#if layout.animate}
		<RollingDigits variant="count" {value} format={compact} durationMs={900} size="md" class={cn("font-bold text-foreground", className)} />
	{:else}
		<span class={className}>{compact(value)}</span>
	{/if}
{/snippet}

<!-- npm downloads: the range total and its trend, the facts behind it, the chart and the packages. -->
<div
	data-slot="npm-stats"
	data-variant={variant}
	data-range={range}
	class={cn(styles.root(), classProp)}
>
	{#if packages.length === 0}
		<Empty variant="outline" size="sm" role="status">
			<EmptyHeader>
				<EmptyTitle>{labels.emptyTitle}</EmptyTitle>
				<EmptyDescription>{labels.emptyDescription}</EmptyDescription>
			</EmptyHeader>
		</Empty>
	{:else}
		<header class={styles.head()}>
			<div class="min-w-0">
				<p class={styles.eyebrow()}>{labels.eyebrow}</p>
				<p class={styles.hero()}>
					{@render figure(periodTotal, styles.heroValue())}
					<span class={styles.heroUnit()}>{unit}</span>
				</p>
				<p class={styles.trendRow()}>
					<TrendBadge change={trend} {locale} newLabel={labels.newLabel} class={styles.trend()} />
					<span class={styles.compare()}>
						{range === "30d" ? labels.compare30 : labels.compare90}
					</span>
				</p>
			</div>
			<ToggleGroup
				type="single"
				value={range}
				onValueChange={setRange}
				label={labels.rangeLabel}
				size="sm"
			>
				<ToggleGroupItem value="30d">{labels.range30}</ToggleGroupItem>
				<ToggleGroupItem value="90d">{labels.range90}</ToggleGroupItem>
			</ToggleGroup>
		</header>

		<dl class={styles.facts()}>
			<div class={styles.fact()}>
				<dt class={styles.factLabel()}>{labels.dailyAverage}</dt>
				<dd class={styles.factValue()}>{compact(facts.dailyAverage)}</dd>
			</div>
			<div class={styles.fact()}>
				<dt class={styles.factLabel()}>{range === "30d" ? labels.peakDay : labels.peakWeek}</dt>
				<dd class={styles.factValue()}>
					{#if facts.peak}
						{compact(facts.peak.value)}
						<span class={styles.factNote()}>{formatDayTick(facts.peak.date, locale)}</span>
					{:else}
						–
					{/if}
				</dd>
			</div>
			<div class={styles.fact()}>
				<dt class={styles.factLabel()}>{labels.busiestWeekday}</dt>
				<dd class={styles.factValue()}>
					{#if facts.weekday}
						{formatWeekday(facts.weekday.day, locale)}
						<span class={styles.factNote()}>
							{labels.overAverage(formatChange(facts.weekday.lift, locale))}
						</span>
					{:else}
						–
					{/if}
				</dd>
			</div>
			<div class={styles.fact()}>
				<dt class={styles.factLabel()}>{labels.fastestGrowing}</dt>
				<dd class={styles.factValue()}>
					{#if facts.leader}
						<span class="font-mono">{facts.leader.name}</span>
						<span class={styles.factNote()}>{formatChange(facts.leader.ratio, locale)}</span>
					{:else}
						–
					{/if}
				</dd>
			</div>
		</dl>

		<NpmDownloadsChart
			data={rows}
			title="{labels.eyebrow} {unit}"
			{locale}
			fillOpacity={variant === "minimal" ? 0 : 0.22}
			grid={layout.grid}
			class={styles.chart()}
		/>

		<dl class={styles.counts()}>
			<div class={styles.count()}>
				<dt class={styles.countLabel()}>{labels.allTime}</dt>
				<dd class="order-first">{@render figure(totals.allTime, styles.countValue())}</dd>
			</div>
			<div class={styles.count()}>
				<dt class={styles.countLabel()}>{labels.last7Days}</dt>
				<dd class="order-first">
					{@render figure(trailingSum(totals.last30Days, 7), styles.countValue())}
				</dd>
			</div>
			<div class={styles.count()}>
				<dt class={styles.countLabel()}>{labels.packages}</dt>
				<dd class="order-first"><span class={styles.countValue()}>{packages.length}</span></dd>
			</div>
		</dl>

		{#if layout.packages}
			<section class={styles.footer()}>
				<h3 class={styles.sectionTitle()}>{labels.breakdownHeading}</h3>
				<NpmPackageBreakdown {packages} {range} {variant} {locale} {labels} />
			</section>
		{/if}
	{/if}
</div>

// packages/ui-react/src/npm-stats/npm-stats.tsx
import { type ReactNode, useState } from "react";
import { Empty, EmptyDescription, EmptyHeader, EmptyTitle } from "../empty/empty";
import { cn } from "../lib/cn";
import { RollingDigits } from "../rolling-digits/rolling-digits";
import { ToggleGroup, ToggleGroupItem } from "../toggle-group";
import {
	combineTotals,
	formatChange,
	formatCompact,
	formatDayTick,
	formatWeekday,
	NPM_STATS_LABELS,
	type NpmPackage,
	type NpmStatsLabels,
	npmFacts,
	rangeTrend,
	trailingSum,
} from "./core";
import { NpmDownloadsChart } from "./downloads-chart";
import { NpmPackageBreakdown } from "./package-breakdown";
import { TrendBadge } from "./trend-badge";
import {
	NPM_STATS_LAYOUT,
	type NpmStatsRange,
	type NpmStatsVariant,
	npmStats,
} from "./variants";

export type { NpmPackage, NpmStatsLabels, NpmStatsRange, NpmStatsVariant };

export interface NpmStatsProps {
	packages: NpmPackage[];
	locale?: string;
	labels?: Partial<NpmStatsLabels>;
	variant?: NpmStatsVariant;
	/** Controlled window; pair with `onRangeChange`. */
	range?: NpmStatsRange;
	defaultRange?: NpmStatsRange;
	onRangeChange?: (range: NpmStatsRange) => void;
	className?: string;
}

/** npm downloads: the range total and its trend, the facts behind it, the chart and the packages. */
export function NpmStats({
	packages,
	locale,
	labels: labelsProp,
	variant = "default",
	range: rangeProp,
	defaultRange = "30d",
	onRangeChange,
	className,
}: NpmStatsProps) {
	const styles = npmStats({ variant });
	const layout = NPM_STATS_LAYOUT[variant];
	const labels = { ...NPM_STATS_LABELS, ...labelsProp };
	const [ownRange, setOwnRange] = useState<NpmStatsRange>(defaultRange);
	const range = rangeProp ?? ownRange;
	const totals = combineTotals(packages);
	const rows = range === "30d" ? totals.last30Days : totals.last90Days;
	const periodTotal = rows.reduce((sum, row) => sum + row.total, 0);
	const unit = range === "30d" ? labels.chartLast30 : labels.chartLast90;
	const trend = rangeTrend(
		rows.map((row) => row.total),
		range,
	);
	const facts = npmFacts(packages, range);
	const compact = (value: number) => formatCompact(value, locale);

	const setRange = (next: string | string[]) => {
		if (next !== "30d" && next !== "90d") return;
		if (rangeProp === undefined) setOwnRange(next);
		onRangeChange?.(next);
	};

	if (packages.length === 0) {
		return (
			<div
				data-slot="npm-stats"
				data-variant={variant}
				className={cn(styles.root(), className)}
			>
				<Empty variant="outline" size="sm" role="status">
					<EmptyHeader>
						<EmptyTitle>{labels.emptyTitle}</EmptyTitle>
						<EmptyDescription>{labels.emptyDescription}</EmptyDescription>
					</EmptyHeader>
				</Empty>
			</div>
		);
	}

	return (
		<div
			data-slot="npm-stats"
			data-variant={variant}
			data-range={range}
			className={cn(styles.root(), className)}
		>
			<header className={styles.head()}>
				<div className="min-w-0">
					<p className={styles.eyebrow()}>{labels.eyebrow}</p>
					<p className={styles.hero()}>
						<Figure
							value={periodTotal}
							format={compact}
							animate={layout.animate}
							className={styles.heroValue()}
						/>
						<span className={styles.heroUnit()}>{unit}</span>
					</p>
					<p className={styles.trendRow()}>
						<TrendBadge
							change={trend}
							locale={locale}
							newLabel={labels.newLabel}
							className={styles.trend()}
						/>
						<span className={styles.compare()}>
							{range === "30d" ? labels.compare30 : labels.compare90}
						</span>
					</p>
				</div>
				<ToggleGroup
					type="single"
					value={range}
					onValueChange={setRange}
					aria-label={labels.rangeLabel}
					size="sm"
				>
					<ToggleGroupItem value="30d">{labels.range30}</ToggleGroupItem>
					<ToggleGroupItem value="90d">{labels.range90}</ToggleGroupItem>
				</ToggleGroup>
			</header>

			<dl className={styles.facts()}>
				<Fact label={labels.dailyAverage} styles={styles}>
					{compact(facts.dailyAverage)}
				</Fact>
				<Fact label={range === "30d" ? labels.peakDay : labels.peakWeek} styles={styles}>
					{facts.peak ? (
						<>
							{compact(facts.peak.value)}{" "}
							<span className={styles.factNote()}>
								{formatDayTick(facts.peak.date, locale)}
							</span>
						</>
					) : (
						"–"
					)}
				</Fact>
				<Fact label={labels.busiestWeekday} styles={styles}>
					{facts.weekday ? (
						<>
							{formatWeekday(facts.weekday.day, locale)}{" "}
							<span className={styles.factNote()}>
								{labels.overAverage(formatChange(facts.weekday.lift, locale))}
							</span>
						</>
					) : (
						"–"
					)}
				</Fact>
				<Fact label={labels.fastestGrowing} styles={styles}>
					{facts.leader ? (
						<>
							<span className="font-mono">{facts.leader.name}</span>{" "}
							<span className={styles.factNote()}>
								{formatChange(facts.leader.ratio, locale)}
							</span>
						</>
					) : (
						"–"
					)}
				</Fact>
			</dl>

			<NpmDownloadsChart
				data={rows}
				title={`${labels.eyebrow} ${unit}`}
				locale={locale}
				fillOpacity={variant === "minimal" ? 0 : 0.22}
				grid={layout.grid}
				className={styles.chart()}
			/>

			<dl className={styles.counts()}>
				<Count label={labels.allTime} styles={styles}>
					<Figure
						value={totals.allTime}
						format={compact}
						animate={layout.animate}
						className={styles.countValue()}
					/>
				</Count>
				<Count label={labels.last7Days} styles={styles}>
					<Figure
						value={trailingSum(totals.last30Days, 7)}
						format={compact}
						animate={layout.animate}
						className={styles.countValue()}
					/>
				</Count>
				<Count label={labels.packages} styles={styles}>
					<span className={styles.countValue()}>{packages.length}</span>
				</Count>
			</dl>

			{layout.packages ? (
				<section className={styles.footer()}>
					<h3 className={styles.sectionTitle()}>{labels.breakdownHeading}</h3>
					<NpmPackageBreakdown
						packages={packages}
						range={range}
						variant={variant}
						locale={locale}
						labels={labels}
					/>
				</section>
			) : null}
		</div>
	);
}

type Styles = ReturnType<typeof npmStats>;

function Fact({
	label,
	styles,
	children,
}: {
	label: string;
	styles: Styles;
	children: ReactNode;
}) {
	return (
		<div className={styles.fact()}>
			<dt className={styles.factLabel()}>{label}</dt>
			<dd className={styles.factValue()}>{children}</dd>
		</div>
	);
}

function Count({
	label,
	styles,
	children,
}: {
	label: string;
	styles: Styles;
	children: ReactNode;
}) {
	return (
		<div className={styles.count()}>
			<dt className={styles.countLabel()}>{label}</dt>
			<dd className="order-first">{children}</dd>
		</div>
	);
}

/** A number that counts up once in view, or sits still when the variant is quiet. */
function Figure({
	value,
	format,
	animate,
	className,
}: {
	value: number;
	format: (value: number) => string;
	animate: boolean;
	className: string;
}) {
	return animate ? (
		<RollingDigits
			variant="count"
			value={value}
			format={format}
			durationMs={900}
			size="md"
			className={cn("font-bold text-foreground", className)}
		/>
	) : (
		<span className={className}>{format(value)}</span>
	);
}
