// packages/ui-react/src/og-spotlight/og-spotlight.tsx
import { cn } from "../lib/cn";
import { OG_SPOTLIGHT_TILES, type OgSpotlightMode, ogSpotlight } from "./variants";

export type { OgSpotlightMode };

export interface OgSpotlightProps {
	/** Centred headline; clamps to two lines. */
	title: string;
	/** Portrait URLs for the eight tiles around the headline; they repeat to fill. */
	images: string[];
	/** Product name under the headline. */
	site?: string;
	logo?: string;
	mode?: OgSpotlightMode;
	className?: string;
}

/** A 1200x630 card: a centred headline and brand on a faint grid, ringed by portraits. */
export function OgSpotlight({
	title,
	images,
	site,
	logo,
	mode = "light",
	className,
}: OgSpotlightProps) {
	const s = ogSpotlight({ mode });
	const pics = images.filter(Boolean);
	return (
		<div data-slot="og-spotlight" className={cn(s.root(), className)}>
			<div className={s.grid()} />
			{pics.length
				? OG_SPOTLIGHT_TILES.map((tile, i) => (
						<img
							key={`${tile.left}-${tile.top}`}
							src={pics[i % pics.length]}
							alt=""
							className={s.face()}
							style={{
								left: tile.left,
								top: tile.top,
								width: tile.width,
								height: tile.height,
							}}
						/>
					))
				: null}
			<h1 className={s.title()}>{title}</h1>
			{logo || site ? (
				<div className={s.brand()}>
					{logo ? <img src={logo} alt="" className={s.logo()} /> : null}
					{site ? <span className={s.site()}>{site}</span> : null}
				</div>
			) : null}
		</div>
	);
}

// packages/ui-svelte/src/lib/og-spotlight/og-spotlight.svelte
<script lang="ts">
import { cn } from "../lib/cn";
import { OG_SPOTLIGHT_TILES, type OgSpotlightMode, ogSpotlight } from "./variants";

let {
	title,
	images,
	site,
	logo,
	mode = "light",
	class: className,
}: {
	/** Centred headline; clamps to two lines. */
	title: string;
	/** Portrait URLs for the eight tiles around the headline; they repeat to fill. */
	images: string[];
	/** Product name under the headline. */
	site?: string;
	logo?: string;
	mode?: OgSpotlightMode;
	class?: string;
} = $props();

const s = $derived(ogSpotlight({ mode }));
const pics = $derived(images.filter(Boolean));
</script>

<div data-slot="og-spotlight" class={cn(s.root(), className)}>
	<div class={s.grid()}></div>
	{#if pics.length}
		{#each OG_SPOTLIGHT_TILES as tile, i (`${tile.left}-${tile.top}`)}
			<img
				src={pics[i % pics.length]}
				alt=""
				class={s.face()}
				style="left:{tile.left}px;top:{tile.top}px;width:{tile.width}px;height:{tile.height}px"
			/>
		{/each}
	{/if}
	<h1 class={s.title()}>{title}</h1>
	{#if logo || site}
		<div class={s.brand()}>
			{#if logo}<img src={logo} alt="" class={s.logo()} />{/if}
			{#if site}<span class={s.site()}>{site}</span>{/if}
		</div>
	{/if}
</div>
