// packages/ui-react/src/label/label.tsx
import type { LabelHTMLAttributes, ReactNode } from "react";
import { cn } from "../lib/cn.js";

export interface LabelProps extends LabelHTMLAttributes<HTMLLabelElement> {
	children: ReactNode;
	required?: boolean;
	disabled?: boolean;
}

export function Label({ children, className, required, disabled, ...rest }: LabelProps) {
	return (
		<label
			{...rest}
			className={cn(
				"inline-flex items-center gap-1 font-medium text-foreground text-sm",
				disabled && "pointer-events-none opacity-50",
				className,
			)}
		>
			{children}
			{required ? (
				<span aria-hidden className="text-[var(--destructive)]">
					*
				</span>
			) : null}
		</label>
	);
}

// packages/ui-svelte/src/lib/label/label.svelte
<script lang="ts">
	import type { Snippet } from "svelte";
	import { cn } from "../lib/cn.js";

	let {
		children,
		for: htmlFor,
		class: classProp,
		required = false,
		disabled = false,
	}: {
		children: Snippet;
		for?: string;
		class?: string;
		required?: boolean;
		disabled?: boolean;
	} = $props();
</script>

<label
	for={htmlFor}
	class={cn(
		"inline-flex items-center gap-1 font-medium text-foreground text-sm",
		disabled && "pointer-events-none opacity-50",
		classProp,
	)}
>
	{@render children()}
	{#if required}<span aria-hidden="true" class="text-[var(--destructive)]">*</span>{/if}
</label>
