// packages/ui-react/src/accordion/accordion.tsx
"use client";

import { Accordion as AccordionPrimitive } from "@base-ui/react/accordion";
import type { ComponentProps } from "react";
import { cn } from "../lib/cn";

type AccordionType = "single" | "multiple";

export type AccordionProps = Omit<
	ComponentProps<typeof AccordionPrimitive.Root>,
	"value" | "defaultValue" | "onValueChange" | "multiple"
> & {
	type?: AccordionType;
	/** Ignored: Base UI's single mode always allows closing the open item. Kept so
	 * existing callers passing `collapsible={false}` still compile. */
	collapsible?: boolean;
	/** The open item in single mode, the open items in multiple mode. */
	value?: string | string[];
	defaultValue?: string | string[];
	onValueChange?: (value: string | string[]) => void;
};

const toList = (v: string | string[] | undefined) =>
	v === undefined ? undefined : Array.isArray(v) ? v : [v];

export function Accordion({
	type = "single",
	collapsible: _collapsible,
	value,
	defaultValue,
	onValueChange,
	className,
	...props
}: AccordionProps) {
	return (
		<AccordionPrimitive.Root
			data-slot="accordion"
			multiple={type === "multiple"}
			value={toList(value)}
			defaultValue={toList(defaultValue)}
			onValueChange={(next: string[]) =>
				onValueChange?.(type === "multiple" ? next : (next[0] ?? ""))
			}
			keepMounted
			className={cn(
				"divide-y divide-border overflow-hidden rounded-xl border border-border",
				className,
			)}
			{...props}
		/>
	);
}

export function AccordionItem({
	className,
	...props
}: ComponentProps<typeof AccordionPrimitive.Item>) {
	return (
		<AccordionPrimitive.Item
			data-slot="accordion-item"
			className={cn(className)}
			{...props}
		/>
	);
}

export function AccordionTrigger({
	className,
	children,
	...props
}: ComponentProps<typeof AccordionPrimitive.Trigger>) {
	return (
		<AccordionPrimitive.Header data-slot="accordion-header" className="flex">
			<AccordionPrimitive.Trigger
				data-slot="accordion-trigger"
				className={cn(
					"flex flex-1 items-center justify-between gap-4 px-4 py-3 text-left font-medium text-foreground text-sm outline-none transition-colors hover:bg-foreground/[0.03] focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-inset disabled:pointer-events-none disabled:opacity-50",
					"[&>svg]:transition-[transform,scale,translate] [&>svg]:duration-[var(--duration-dropdown)] [&>svg]:ease-[var(--ease-out)] [&[data-open]>svg]:rotate-180 motion-reduce:[&>svg]:transition-none",
					className,
				)}
				{...props}
			>
				{children}
				<svg
					viewBox="0 0 16 16"
					fill="none"
					aria-hidden
					className="size-4 shrink-0 text-muted-foreground"
				>
					<path
						d="m4 6 4 4 4-4"
						stroke="currentColor"
						strokeWidth="1.4"
						strokeLinecap="round"
						strokeLinejoin="round"
					/>
				</svg>
			</AccordionPrimitive.Trigger>
		</AccordionPrimitive.Header>
	);
}

export function AccordionContent({
	className,
	children,
	...props
}: ComponentProps<typeof AccordionPrimitive.Panel>) {
	return (
		<AccordionPrimitive.Panel
			data-slot="accordion-content"
			className="grid grid-rows-[0fr] transition-[grid-template-rows] duration-[var(--duration-dropdown)] ease-[var(--ease-out)] data-[open]:grid-rows-[1fr] motion-reduce:transition-none"
			{...props}
		>
			<div className="overflow-hidden">
				<div
					className={cn(
						"px-4 pb-3 text-muted-foreground text-sm leading-relaxed",
						className,
					)}
				>
					{children}
				</div>
			</div>
		</AccordionPrimitive.Panel>
	);
}

// packages/ui-svelte/src/lib/accordion/accordion.svelte
<script lang="ts">
import { Accordion as AccordionPrimitive } from "bits-ui";
import type { Snippet } from "svelte";
import { cn } from "../lib/cn";

let {
	children,
	type = "single",
	collapsible: _collapsible,
	value = $bindable(),
	onValueChange,
	class: classProp,
	...rest
}: {
	children?: Snippet;
	type?: "single" | "multiple";
	/** Ignored: bits-ui's single mode always allows closing the open item. Kept so
	 * existing callers passing `collapsible={false}` still compile. */
	collapsible?: boolean;
	/** The open item in single mode, the open items in multiple mode. Bindable. */
	value?: string | string[];
	onValueChange?: (value: string | string[]) => void;
	class?: string;
} = $props();

const rootClass = $derived(
	cn("divide-y divide-border overflow-hidden rounded-xl border border-border", classProp),
);

function commit(next: string | string[]) {
	value = next;
	onValueChange?.(next);
}
</script>

<!-- bits-ui fixes `type` when the root mounts, so each mode is its own root with its own value shape. -->
{#if type === "multiple"}
	<AccordionPrimitive.Root
		{...rest}
		type="multiple"
		bind:value={() => (Array.isArray(value) ? value : value ? [value] : []), commit}
		data-slot="accordion"
		class={rootClass}
	>
		{@render children?.()}
	</AccordionPrimitive.Root>
{:else}
	<AccordionPrimitive.Root
		{...rest}
		type="single"
		bind:value={() => (Array.isArray(value) ? (value[0] ?? "") : (value ?? "")), commit}
		data-slot="accordion"
		class={rootClass}
	>
		{@render children?.()}
	</AccordionPrimitive.Root>
{/if}
