// packages/ui-react/src/split-text/split-text.tsx
"use client";

import { useRef, useState } from "react";
import { cn } from "../lib/cn";
import { type SplitTextSize, splitText } from "./variants";

export type { SplitTextSize };

export interface SplitTextProps {
	/** Each letter splits into two halves that fan out around the hovered one. */
	text: string;
	/** How long the fan-out transition takes, in ms. */
	durationMs?: number;
	size?: SplitTextSize;
	className?: string;
}

const HALF_CLASS =
	"inline h-1/2 select-none overflow-y-hidden whitespace-pre leading-none transition-transform ease-[var(--ease-out)]";

function offset(index: number, active: number | undefined) {
	if (active === undefined) return 0;
	const distance = Math.abs(index - active);
	if (distance === 0) return 5;
	if (distance === 1) return 3;
	if (distance === 2) return 1;
	return 0;
}

export function SplitText({
	text,
	durationMs = 300,
	size = "lg",
	className,
}: SplitTextProps) {
	const [activeIndex, setActiveIndex] = useState<number>();
	const timer = useRef<ReturnType<typeof setTimeout>>(undefined);

	return (
		<div data-slot="split-text" className={cn(splitText({ size }), className)}>
			<div className="invisible leading-none">{text}</div>
			<div className="absolute top-0 flex h-full">
				{text.split("").map((letter, index) => {
					const shift = offset(index, activeIndex);
					return (
						<div
							key={`${letter}-${index}`}
							onMouseEnter={() => {
								clearTimeout(timer.current);
								setActiveIndex(index);
							}}
							onMouseLeave={() => {
								timer.current = setTimeout(() => setActiveIndex(undefined));
							}}
							className="relative inline-flex h-full flex-col leading-none"
							aria-hidden
						>
							<span
								className={HALF_CLASS}
								style={{
									transform: `translateY(-${shift * 4}px)`,
									transitionDuration: `${durationMs}ms`,
								}}
							>
								{letter}
							</span>
							<span
								className={HALF_CLASS}
								style={{
									transform: `translateY(${shift * 4}px)`,
									transitionDuration: `${durationMs}ms`,
								}}
							>
								<span className="absolute -translate-y-1/2 leading-none">{letter}</span>
							</span>
						</div>
					);
				})}
			</div>
			<span className="sr-only">{text}</span>
		</div>
	);
}

// packages/ui-svelte/src/lib/split-text/split-text.svelte
<script lang="ts">
import { cn } from "../lib/cn";
import { type SplitTextSize, splitText } from "./variants";

let {
	text,
	durationMs = 300,
	size = "lg",
	class: classProp,
}: {
	text: string;
	/** How long the fan-out transition takes, in ms. */
	durationMs?: number;
	size?: SplitTextSize;
	class?: string;
} = $props();

let activeIndex = $state<number | undefined>(undefined);
let timer: ReturnType<typeof setTimeout> | undefined;

function offset(index: number) {
	if (activeIndex === undefined) return 0;
	const distance = Math.abs(index - activeIndex);
	if (distance === 0) return 5;
	if (distance === 1) return 3;
	if (distance === 2) return 1;
	return 0;
}

const HALF_CLASS =
	"inline h-1/2 select-none overflow-y-hidden whitespace-pre leading-none transition-transform ease-[var(--ease-out)]";
</script>

<div data-slot="split-text" class={cn(splitText({ size }), classProp)}>
	<div class="invisible leading-none">{text}</div>
	<div class="absolute top-0 flex h-full">
		{#each text.split("") as letter, index (`${letter}-${index}`)}
			{@const shift = offset(index)}
			<div
				aria-hidden="true"
				onmouseenter={() => {
					clearTimeout(timer);
					activeIndex = index;
				}}
				onmouseleave={() => {
					timer = setTimeout(() => {
						activeIndex = undefined;
					});
				}}
				class="relative inline-flex h-full flex-col leading-none"
			>
				<span
					class={HALF_CLASS}
					style="transform: translateY(-{shift * 4}px); transition-duration: {durationMs}ms"
					>{letter}</span
				>
				<span
					class={HALF_CLASS}
					style="transform: translateY({shift * 4}px); transition-duration: {durationMs}ms"
				>
					<span class="absolute -translate-y-1/2 leading-none">{letter}</span>
				</span>
			</div>
		{/each}
	</div>
	<span class="sr-only">{text}</span>
</div>
