// packages/ui-svelte/src/lib/og-showcase/og-showcase.svelte
<script lang="ts">
import { cn } from "../lib/cn";
import { OG_SHOWCASE_COLUMNS, type OgShowcaseMode, ogShowcase } from "./variants";

let {
	title,
	images,
	site,
	logo,
	description,
	mode = "light",
	class: className,
}: {
	/** Headline, bottom left; clamps to four lines. */
	title: string;
	/** Screenshot URLs for the two columns of framed shots; they repeat to fill. */
	images: string[];
	/** Product name beside the logo. */
	site?: string;
	logo?: string;
	description?: string;
	mode?: OgShowcaseMode;
	class?: string;
} = $props();

const s = $derived(ogShowcase({ mode }));
const pics = $derived(images.filter(Boolean));
</script>

<div data-slot="og-showcase" class={cn(s.root(), className)}>
	{#if pics.length}
		{#each OG_SHOWCASE_COLUMNS as col, c (col.left)}
			<div class={s.column()} style="left:{col.left}px;top:{col.top}px">
				{#each col.heights as height, i (`${height}-${i}`)}
					<div class={s.frame()} style="height:{height}px">
						<img src={pics[(c * 3 + i) % pics.length]} alt="" class={s.shot()} />
					</div>
				{/each}
			</div>
		{/each}
	{/if}
	{#if logo || site}
		<div class={s.brand()}>
			{#if logo}<img src={logo} alt="" class={s.logo()} />{/if}
			{#if site}<span class={s.site()}>{site}</span>{/if}
		</div>
	{/if}
	<h1 class={s.title()}>{title}</h1>
	{#if description}<p class={s.description()}>{description}</p>{/if}
</div>

// packages/ui-react/src/og-showcase/og-showcase.tsx
import { cn } from "../lib/cn";
import { OG_SHOWCASE_COLUMNS, type OgShowcaseMode, ogShowcase } from "./variants";

export type { OgShowcaseMode };

export interface OgShowcaseProps {
	/** Headline, bottom left; clamps to four lines. */
	title: string;
	/** Screenshot URLs for the two columns of framed shots; they repeat to fill. */
	images: string[];
	/** Product name beside the logo. */
	site?: string;
	logo?: string;
	description?: string;
	mode?: OgShowcaseMode;
	className?: string;
}

/** A 1200x630 product card: headline left, two offset columns of framed screenshots right. */
export function OgShowcase({
	title,
	images,
	site,
	logo,
	description,
	mode = "light",
	className,
}: OgShowcaseProps) {
	const s = ogShowcase({ mode });
	const pics = images.filter(Boolean);
	return (
		<div data-slot="og-showcase" className={cn(s.root(), className)}>
			{pics.length
				? OG_SHOWCASE_COLUMNS.map((col, c) => (
						<div
							key={col.left}
							className={s.column()}
							style={{ left: col.left, top: col.top }}
						>
							{col.heights.map((height, i) => (
								<div key={`${height}-${i}`} className={s.frame()} style={{ height }}>
									<img
										src={pics[(c * 3 + i) % pics.length]}
										alt=""
										className={s.shot()}
									/>
								</div>
							))}
						</div>
					))
				: null}
			{logo || site ? (
				<div className={s.brand()}>
					{logo ? <img src={logo} alt="" className={s.logo()} /> : null}
					{site ? <span className={s.site()}>{site}</span> : null}
				</div>
			) : null}
			<h1 className={s.title()}>{title}</h1>
			{description ? <p className={s.description()}>{description}</p> : null}
		</div>
	);
}
