// packages/ui-react/src/closing-plasma/closing-plasma.tsx
"use client";

import { type ReactNode, useEffect, useRef, useState } from "react";
import { cn } from "../lib/cn";
import { type ClosingPlasmaOptions, mountClosingPlasma } from "./plasma";
import {
	CLOSING_PLASMA_COLORS,
	CLOSING_PLASMA_SPEED,
	type ClosingPlasmaPosition,
	type ClosingPlasmaSpeed,
	type ClosingPlasmaTone,
	closingPlasma,
} from "./variants";

export type { ClosingPlasmaPosition, ClosingPlasmaSpeed, ClosingPlasmaTone };

export interface ClosingPlasmaProps {
	tone?: ClosingPlasmaTone;
	speed?: ClosingPlasmaSpeed;
	position?: ClosingPlasmaPosition;
	/** Noise frequency growth per octave, 0 to 2. */
	turbulence?: number;
	/** Sparkle strength, 0 to 2. */
	sparkle?: number;
	/** Film grain, 0 to 2. */
	grain?: number;
	/** The field leans toward the pointer. */
	interactive?: boolean;
	className?: string;
	children?: ReactNode;
}

/** A ridged simplex plasma in WebGL that follows the theme between dark and light. */
export function ClosingPlasma({
	tone = "chart",
	speed = "normal",
	position = "absolute",
	turbulence = 1,
	sparkle = 1,
	grain = 1,
	interactive = true,
	className,
	children,
}: ClosingPlasmaProps) {
	const root = useRef<HTMLDivElement>(null);
	const canvas = useRef<HTMLCanvasElement>(null);
	const engine = useRef<ReturnType<typeof mountClosingPlasma>>(null);
	const [webgl, setWebgl] = useState(false);
	const s = closingPlasma({ tone, speed, position, webgl });
	const options: ClosingPlasmaOptions = {
		colors: CLOSING_PLASMA_COLORS[tone],
		speed: CLOSING_PLASMA_SPEED[speed],
		turbulence,
		sparkle,
		grain,
		interactive,
	};
	const latest = useRef(options);
	latest.current = options;

	useEffect(() => {
		if (!root.current || !canvas.current) return;
		const mounted = mountClosingPlasma(
			root.current,
			canvas.current,
			latest.current,
			setWebgl,
		);
		engine.current = mounted;
		return () => {
			mounted.destroy();
			engine.current = null;
		};
	}, []);

	useEffect(() => {
		engine.current?.update(latest.current);
	}, [tone, speed, turbulence, sparkle, grain, interactive]);

	return (
		<div ref={root} data-slot="closing-plasma" className={cn(s.root(), className)}>
			<div aria-hidden className={s.fallback()} />
			<canvas ref={canvas} aria-hidden className={s.canvas()} />
			{children ? <div className={s.content()}>{children}</div> : null}
		</div>
	);
}

// packages/ui-svelte/src/lib/closing-plasma/closing-plasma.svelte
<script lang="ts">
import { type Snippet, untrack } from "svelte";
import { cn } from "../lib/cn";
import { type ClosingPlasmaOptions, mountClosingPlasma } from "./plasma";
import {
	CLOSING_PLASMA_COLORS,
	CLOSING_PLASMA_SPEED,
	type ClosingPlasmaPosition,
	type ClosingPlasmaSpeed,
	type ClosingPlasmaTone,
	closingPlasma,
} from "./variants";

let {
	tone = "chart",
	speed = "normal",
	position = "absolute",
	turbulence = 1,
	sparkle = 1,
	grain = 1,
	interactive = true,
	class: classProp,
	children,
}: {
	tone?: ClosingPlasmaTone;
	speed?: ClosingPlasmaSpeed;
	position?: ClosingPlasmaPosition;
	/** Noise frequency growth per octave, 0 to 2. */
	turbulence?: number;
	/** Sparkle strength, 0 to 2. */
	sparkle?: number;
	/** Film grain, 0 to 2. */
	grain?: number;
	/** The field leans toward the pointer. */
	interactive?: boolean;
	class?: string;
	children?: Snippet;
} = $props();

let root: HTMLDivElement | undefined = $state();
let canvas: HTMLCanvasElement | undefined = $state();
let webgl = $state(false);
let engine: ReturnType<typeof mountClosingPlasma> | undefined;
const s = $derived(closingPlasma({ tone, speed, position, webgl }));
const options: ClosingPlasmaOptions = $derived({
	colors: CLOSING_PLASMA_COLORS[tone],
	speed: CLOSING_PLASMA_SPEED[speed],
	turbulence,
	sparkle,
	grain,
	interactive,
});

$effect(() => {
	const el = root;
	const surface = canvas;
	if (!el || !surface) return;
	const mounted = untrack(() =>
		mountClosingPlasma(el, surface, options, (ok) => {
			webgl = ok;
		}),
	);
	engine = mounted;
	return () => {
		mounted.destroy();
		engine = undefined;
	};
});

$effect(() => {
	engine?.update(options);
});
</script>

<div bind:this={root} data-slot="closing-plasma" class={cn(s.root(), classProp)}>
	<div aria-hidden="true" class={s.fallback()}></div>
	<canvas bind:this={canvas} aria-hidden="true" class={s.canvas()}></canvas>
	{#if children}
		<div class={s.content()}>{@render children()}</div>
	{/if}
</div>
