// packages/ui-svelte/src/lib/response-stream/response-stream.svelte
<script lang="ts">
import { prefersReducedMotion } from "svelte/motion";
import { cn } from "../lib/cn";
import { type ResponseStreamSize, responseStream } from "./variants";

let {
	text,
	speed = 60,
	streaming = true,
	size = "md",
	class: classProp,
}: {
	text: string;
	speed?: number;
	streaming?: boolean;
	size?: ResponseStreamSize;
	class?: string;
} = $props();

const styles = $derived(responseStream({ size }));

let shown = $state(0);

$effect(() => {
	if (prefersReducedMotion.current) {
		shown = text.length;
		return;
	}
	shown = 0;
	const perTick = Math.max(1, Math.round(speed / 30));
	const id = setInterval(() => {
		shown = Math.min(text.length, shown + perTick);
		if (shown >= text.length) clearInterval(id);
	}, 1000 / 30);
	return () => clearInterval(id);
});

const visible = $derived(text.slice(0, shown));
const done = $derived(shown >= text.length);
</script>

<p
	aria-live="polite"
	aria-busy={!done || undefined}
	data-slot="response-stream"
	class={cn(styles.root(), classProp)}
>{visible}{#if streaming && !done}<span aria-hidden="true" class={styles.caret()}></span>{/if}</p>

// packages/ui-react/src/response-stream/response-stream.tsx
"use client";

import { useEffect, useState } from "react";
import { cn } from "../lib/cn";
import { type ResponseStreamSize, responseStream } from "./variants";

export type { ResponseStreamSize };

export interface ResponseStreamProps {
	text: string;
	speed?: number;
	streaming?: boolean;
	size?: ResponseStreamSize;
	className?: string;
}

const reduced = () =>
	typeof matchMedia === "function" &&
	matchMedia("(prefers-reduced-motion: reduce)").matches;

export function ResponseStream({
	text,
	speed = 60,
	streaming = true,
	size = "md",
	className,
}: ResponseStreamProps) {
	const styles = responseStream({ size });
	const [shown, setShown] = useState(0);

	useEffect(() => {
		if (reduced()) {
			setShown(text.length);
			return;
		}
		setShown(0);
		const perTick = Math.max(1, Math.round(speed / 30));
		const id = setInterval(() => {
			setShown((prev) => {
				const next = Math.min(text.length, prev + perTick);
				if (next >= text.length) clearInterval(id);
				return next;
			});
		}, 1000 / 30);
		return () => clearInterval(id);
	}, [text, speed]);

	const done = shown >= text.length;

	return (
		<p
			aria-live="polite"
			aria-busy={!done || undefined}
			data-slot="response-stream"
			className={cn(styles.root(), className)}
		>
			{text.slice(0, shown)}
			{streaming && !done ? <span aria-hidden className={styles.caret()} /> : null}
		</p>
	);
}
