// packages/ui-svelte/src/lib/loading-screen/loading-screen.svelte
<script lang="ts">
import type { Snippet } from "svelte";
import { cn } from "../lib/cn";
import Progress from "../progress/progress.svelte";
import Spinner from "../spinner/spinner.svelte";
import {
	type LoadingScreenIndicator,
	type LoadingScreenLogoMotion,
	type LoadingScreenPosition,
	loadingScreen,
	statusLabel,
} from "./variants";

let {
	logo,
	open = true,
	progress,
	indicator = "bar",
	logoMotion,
	position,
	caption,
	label = "Loading",
	class: className,
}: {
	/** Your mark, e.g. an inline SVG. Omit for an indicator-only screen. */
	logo?: Snippet;
	/** Visible while true; false fades it out and makes it inert. */
	open?: boolean;
	/** 0-100 for a determinate bar; omit for an indeterminate one. */
	progress?: number;
	indicator?: LoadingScreenIndicator;
	logoMotion?: LoadingScreenLogoMotion;
	/** `fixed` covers the page; `absolute` covers the nearest positioned container. */
	position?: LoadingScreenPosition;
	/** Short visible line under the indicator. */
	caption?: Snippet;
	/** Screen-reader status text. */
	label?: string;
	class?: string;
} = $props();

const s = $derived(loadingScreen({ position, logoMotion, indicator, open }));
</script>

<div
	data-slot="loading-screen"
	role="status"
	inert={!open}
	class={cn(s.root(), className)}
>
	<span class={s.srOnly()}>{statusLabel(label, progress)}</span>
	{#if logo}
		<div aria-hidden="true" class={s.logo()}>{@render logo()}</div>
	{/if}
	{#if indicator !== "none"}
		<div aria-hidden="true" class={s.indicator()}>
			{#if indicator === "bar"}
				<Progress value={progress ?? 0} indeterminate={progress === undefined} size="sm" class="w-28" />
			{:else if indicator === "spinner"}
				<Spinner size="md" {label} />
			{:else}
				<span class={s.dots()}>
					{#each [0, 1, 2] as i (i)}
						<span class={s.dot()} style:animation-delay="{i * 160}ms"></span>
					{/each}
				</span>
			{/if}
		</div>
	{/if}
	{#if caption}
		<p class={s.caption()}>{@render caption()}</p>
	{/if}
</div>

// packages/ui-react/src/loading-screen/loading-screen.tsx
"use client";

import type { ReactNode } from "react";
import { cn } from "../lib/cn";
import { Progress } from "../progress/progress";
import { Spinner } from "../spinner/spinner";
import {
	type LoadingScreenIndicator,
	type LoadingScreenLogoMotion,
	type LoadingScreenPosition,
	loadingScreen,
	statusLabel,
} from "./variants";

export type { LoadingScreenIndicator, LoadingScreenLogoMotion, LoadingScreenPosition };

export interface LoadingScreenProps {
	/** Your mark, e.g. an inline SVG. Omit for an indicator-only screen. */
	logo?: ReactNode;
	/** Visible while true; false fades it out and makes it inert. */
	open?: boolean;
	/** 0-100 for a determinate bar; omit for an indeterminate one. */
	progress?: number;
	indicator?: LoadingScreenIndicator;
	logoMotion?: LoadingScreenLogoMotion;
	/** `fixed` covers the page; `absolute` covers the nearest positioned container. */
	position?: LoadingScreenPosition;
	/** Short visible line under the indicator. */
	caption?: ReactNode;
	/** Screen-reader status text. */
	label?: string;
	className?: string;
}

/** A full-page or container loading overlay: your logo, an indicator and an optional caption. */
export function LoadingScreen({
	logo,
	open = true,
	progress,
	indicator = "bar",
	logoMotion,
	position,
	caption,
	label = "Loading",
	className,
}: LoadingScreenProps) {
	const s = loadingScreen({ position, logoMotion, indicator, open });
	return (
		<div
			data-slot="loading-screen"
			role="status"
			inert={!open}
			className={cn(s.root(), className)}
		>
			<span className={s.srOnly()}>{statusLabel(label, progress)}</span>
			{logo ? (
				<div aria-hidden className={s.logo()}>
					{logo}
				</div>
			) : null}
			{indicator !== "none" ? (
				<div aria-hidden className={s.indicator()}>
					{indicator === "bar" ? (
						<Progress
							value={progress ?? 0}
							indeterminate={progress === undefined}
							size="sm"
							className="w-28"
						/>
					) : indicator === "spinner" ? (
						<Spinner size="md" label={label} />
					) : (
						<span className={s.dots()}>
							{[0, 1, 2].map((i) => (
								<span
									key={i}
									className={s.dot()}
									style={{ animationDelay: `${i * 160}ms` }}
								/>
							))}
						</span>
					)}
				</div>
			) : null}
			{caption ? <p className={s.caption()}>{caption}</p> : null}
		</div>
	);
}
