// packages/ui-svelte/src/lib/og-brand/og-brand.svelte
<script lang="ts">
import { cn } from "../lib/cn";
import {
	OG_BRAND_MOSAIC,
	OG_BRAND_PIPES,
	OG_BRAND_SCATTER,
	OG_BRAND_WAVES,
	type OgBrandMode,
	type OgBrandVariant,
	ogBrand,
	ogBrandBand,
} from "./variants";

let {
	name,
	logo,
	tagline,
	images,
	mode = "light",
	variant = "plain",
	class: className,
}: {
	/** Brand name, set as the wordmark. */
	name: string;
	/** Logo image URL beside (or, in `mosaic`, above) the name. */
	logo?: string;
	/** One quiet line under the wordmark. */
	tagline?: string;
	/** Image URLs for `scatter` tiles, `mosaic` columns and the `split` panel; they cycle. */
	images?: string[];
	mode?: OgBrandMode;
	variant?: OgBrandVariant;
	class?: string;
} = $props();

const s = $derived(ogBrand({ mode, variant }));
const pics = $derived(images?.filter(Boolean) ?? []);
const pick = (i: number) => pics[i % pics.length];
const box = (b: { left: number; top: number; width: number; height: number }) =>
	`left:${b.left}px;top:${b.top}px;width:${b.width}px;height:${b.height}px`;
</script>

<div data-slot="og-brand" class={cn(s.root(), className)}>
	{#if variant === "waves"}
		<svg
			viewBox="0 0 1200 630"
			fill="none"
			stroke="currentColor"
			stroke-width="1.25"
			class={s.field()}
			aria-hidden="true"
		>
			{#each OG_BRAND_WAVES as d (d)}<path {d} />{/each}
		</svg>
		<div class={s.hairX()}></div>
		<div class={s.hairY()}></div>
	{:else if variant === "pipes"}
		<div class={s.dots()}></div>
		{#each OG_BRAND_PIPES as band (`${band.left}-${band.top}`)}
			<div
				class={ogBrandBand({ side: band.side, slot: band.slot })}
				style="{box(band)};border-{band.side === 'lb' ? 'bottom' : 'top'}-left-radius:{band.radius}px"
			></div>
		{/each}
	{:else if variant === "mesh" || variant === "blur"}
		<div class={s.blobA()}></div>
		<div class={s.blobB()}></div>
		<div class={s.blobC()}></div>
		{#if variant === "mesh"}
			<div class={s.sheen()}></div>
			<div class={s.veil()}></div>
		{/if}
	{:else if pics.length && variant === "scatter"}
		{#each OG_BRAND_SCATTER as tile, i (`${tile.left}-${tile.top}`)}
			<img src={pick(i)} alt="" class={cn(s.tile(), tile.soft && s.softTile())} style={box(tile)} />
		{/each}
	{:else if pics.length && variant === "mosaic"}
		{#each OG_BRAND_MOSAIC as tile, i (`${tile.left}-${tile.top}`)}
			<img src={pick(i)} alt="" class={s.tile()} style={box(tile)} />
		{/each}
	{:else if pics.length && variant === "split"}
		<img src={pick(0)} alt="" class={s.panel()} />
	{/if}
	<div class={s.mark()}>
		<div class={s.wordmark()}>
			{#if logo}<img src={logo} alt="" class={s.logo()} />{/if}
			<span class={s.name()}>{name}</span>
		</div>
		{#if tagline}<p class={s.tagline()}>{tagline}</p>{/if}
	</div>
</div>

// packages/ui-react/src/og-brand/og-brand.tsx
import { cn } from "../lib/cn";
import {
	OG_BRAND_MOSAIC,
	OG_BRAND_PIPES,
	OG_BRAND_SCATTER,
	OG_BRAND_WAVES,
	type OgBrandMode,
	type OgBrandVariant,
	ogBrand,
	ogBrandBand,
} from "./variants";

export type { OgBrandMode, OgBrandVariant };

export interface OgBrandProps {
	/** Brand name, set as the wordmark. */
	name: string;
	/** Logo image URL beside (or, in `mosaic`, above) the name. */
	logo?: string;
	/** One quiet line under the wordmark. */
	tagline?: string;
	/** Image URLs for `scatter` tiles, `mosaic` columns and the `split` panel; they cycle. */
	images?: string[];
	mode?: OgBrandMode;
	variant?: OgBrandVariant;
	className?: string;
}

/** A 1200x630 brand card: the wordmark over one of eight backgrounds. Render it with takumi-js. */
export function OgBrand({
	name,
	logo,
	tagline,
	images,
	mode = "light",
	variant = "plain",
	className,
}: OgBrandProps) {
	const s = ogBrand({ mode, variant });
	const pics = images?.filter(Boolean) ?? [];
	const pick = (i: number) => pics[i % pics.length];
	return (
		<div data-slot="og-brand" className={cn(s.root(), className)}>
			{variant === "waves" ? (
				<>
					<svg
						viewBox="0 0 1200 630"
						fill="none"
						stroke="currentColor"
						strokeWidth="1.25"
						className={s.field()}
						aria-hidden="true"
					>
						{OG_BRAND_WAVES.map((d) => (
							<path key={d} d={d} />
						))}
					</svg>
					<div className={s.hairX()} />
					<div className={s.hairY()} />
				</>
			) : null}
			{variant === "pipes" ? (
				<>
					<div className={s.dots()} />
					{OG_BRAND_PIPES.map((band) => (
						<div
							key={`${band.left}-${band.top}`}
							className={ogBrandBand({ side: band.side, slot: band.slot })}
							style={{
								left: band.left,
								top: band.top,
								width: band.width,
								height: band.height,
								[band.side === "lb" ? "borderBottomLeftRadius" : "borderTopLeftRadius"]:
									band.radius,
							}}
						/>
					))}
				</>
			) : null}
			{variant === "mesh" || variant === "blur" ? (
				<>
					<div className={s.blobA()} />
					<div className={s.blobB()} />
					<div className={s.blobC()} />
				</>
			) : null}
			{variant === "mesh" ? (
				<>
					<div className={s.sheen()} />
					<div className={s.veil()} />
				</>
			) : null}
			{pics.length && variant === "scatter"
				? OG_BRAND_SCATTER.map((tile, i) => (
						<img
							key={`${tile.left}-${tile.top}`}
							src={pick(i)}
							alt=""
							className={cn(s.tile(), tile.soft && s.softTile())}
							style={{
								left: tile.left,
								top: tile.top,
								width: tile.width,
								height: tile.height,
							}}
						/>
					))
				: null}
			{pics.length && variant === "mosaic"
				? OG_BRAND_MOSAIC.map((tile, i) => (
						<img
							key={`${tile.left}-${tile.top}`}
							src={pick(i)}
							alt=""
							className={s.tile()}
							style={{
								left: tile.left,
								top: tile.top,
								width: tile.width,
								height: tile.height,
							}}
						/>
					))
				: null}
			{pics.length && variant === "split" ? (
				<img src={pick(0)} alt="" className={s.panel()} />
			) : null}
			<div className={s.mark()}>
				<div className={s.wordmark()}>
					{logo ? <img src={logo} alt="" className={s.logo()} /> : null}
					<span className={s.name()}>{name}</span>
				</div>
				{tagline ? <p className={s.tagline()}>{tagline}</p> : null}
			</div>
		</div>
	);
}
